### ISSUE TITLE
New releases don't show up on F-Droid

### ISSUE THREAD

**Issue by billie80** [slapperwan/gh4a#1007]
Starting with release 4.6.1 the updates are not seen on F-Droid. I think the problem is the change from not using using the "v" prefix for the releases anymore.

In the [F-Droid data repository](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.gh4a.yml) the prefix is still used.

Strangely for 4.6.0 there was a [fix](https://gitlab.com/fdroid/fdroiddata/-/commit/d12ca1001c8100d9c828d64f6a530580cf4936e7) removing the "v" although this tag still contains it.

For [4.6.1](https://gitlab.com/fdroid/fdroiddata/-/commit/1b6157ea1f08d73310555b5fdd386bea046380de) and [4.6.2](https://gitlab.com/fdroid/fdroiddata/-/commit/199c7f9086c764ed16903c45ee9d124807e4c9d7) the prefixed "v" was added again an automated version bump.

**Comment by billie80** [comment]
Since today 4.6.2 is available on F-Droid.

**Comment by maniac103** [comment]
Yeah, somebody adapted the naming scheme. That's nice, that way I can keep my numbering style. I wasn't even aware of the difference so far. If they hadn't updated, I would have released 4.6.3 with the old tag format.
