### ISSUE TITLE
[Feature Request] Multi Translator

### ISSUE THREAD

**Issue by zpcol** [slapperwan/gh4a#1012]
Google
Bing
Yandex

**Comment by maniac103** [comment]
Can you please describe the request a bit more detailed? At the moment I don't understand what you're asking for.

**Comment by zpcol** [comment]
add translator button features, such as twitter or this addon.
https://addons.mozilla.org/id/android/addon/traduzir-paginas-web/

**Comment by zpcol** [comment]
many people are more comfortable using the browser because they can use a translator, maybe the future of this feature is mandatory in every application, if you can make a separate offline SDK buildin :-)
