### ISSUE TITLE
[Question] API rate limit exceeded

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#1013]
Hello,

> `API rate limit exceeded for user ID 21284089 (403)`

I'm getting a lot of these lately, while I didn't used to in my first months using OctoDroid.

What changed ?

Thanks

**Comment by maniac103** [comment]
I don't think anything specific has changed ... at least I never saw that error in my own Octodroid usage. [The docs](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) say you have 5000 requests per hour shared among all apps you're logged into ... do you maybe use more than one app that uses a GH token for your account?

**Comment by KaKi87** [comment]
I've just discovered that OctoDroid make a lot of these requests
| ![](https://cdn.discordapp.com/attachments/493524617714204672/749154910502780939/Screenshot_20200829-083334.jpg) | ![](https://cdn.discordapp.com/attachments/493524617714204672/749154911157223504/Screenshot_20200829-083236.jpg) |
| ------------- | ------------- |

**Comment by maniac103** [comment]
Interesting. I assume you have notifications enabled? If so, this almost feels like the notifications worker is retriggered over and over again.
Can you reproduce this at will? If so, I assume the issue goes away when disabling notifications?

**Comment by KaKi87** [comment]
You guessed **everything** right.

**Comment by maniac103** [comment]
OK, in that case I'll double check the notifications code and maybe add some debug logging. Would you be willing to test drive a build with more debug output?

**Comment by KaKi87** [comment]
Yes, preferably built as an APK and outputting logs in a local file. Thanks

**Comment by KaKi87** [comment]
So you fixed it anyway ? ^^
Did you found out why it only happened to me ?
When will the fix be released in Google Play ?

**Comment by maniac103** [comment]
>  Did you found out why it only happened to me ?

I have no idea why you had *that* many workers running, but when adding debug logging I found that I also had 4 or 5 running simultaneously.

> When will the fix be released in Google Play ?

In the next 1 or 2 weeks, I want to test drive the new code for check run support for a few days.

**Comment by mqus** [comment]
I'm not entirely sure because I did not check the logs but I think this bug took up most of my mobile data volume eventhough I was barely outside last month. Now after I applied the update I also noticed that my battery also lasts twice to thrice as long as before, probably due to the frequent waking.
All I want to say is thank you! You postponed my decision to buy a new phone at least a year :D

**Comment by KaKi87** [comment]
I'd believe you regarding baterry because loops and requests do take energy, however, they're just API calls so they only contain text, they're lightweight. What's your data plan size?

**Comment by mqus** [comment]
It took up about 750mb of mostly backgrounddata over at most 24 hour in total, stretched over a month? I know it's ridiculous.

**Comment by KaKi87** [comment]
Alright 🙂
