### ISSUE TITLE
Feature request: Subscribe to issues

### ISSUE THREAD

**Issue by Zaseth** [slapperwan/gh4a#1047]
Please add the option to subscribe and unsubscribe from issues. Example when you comment on an issue for the first time, you automatically subscribe to the issue, but this isn't shown on the app. I also can't unsubscribe from an issue either.

**Comment by Offerel** [comment]
I searched this function also several times. At least in my eyes it's a little bit annoying to leave a short comment, only for the reason to subscribe to an issue. I only want to be informed if there is something new to the issue.
