### ISSUE TITLE
Not Able To Login With User Name And Password Method

### ISSUE THREAD

**Issue by landry314** [slapperwan/gh4a#1056]
Login with user name and password never works for me.

I am 100% sure the user name and password are correct. I confirmed it and entered it so many times. I tried both the user name and the email I use with github. I confirmed the email on their page.

I had to use an access token to log in which is fine, it works great, but I wasted a lot of time and it caused stress. I noticed that I already had an access token for my old phone then it made me remember I was not able to log in to octodroid there either and that is why I created this old access token. I have not EVER been able to use user name and password for octodroid.

If the login with user name and password doesn't work, shouldn't that method be removed?

If it does work but only in a particular way I am not clear on, then I suggest a clearer explanation of what is actually going on with this method.

Is anyone else having this issue?

**Comment by Fs00** [comment]
Support for login with username/password [was removed by GitHub on 13th November 2020](https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/), so that's why it didn't work.
The option in the app will be removed in #1165.
