### ISSUE TITLE
[BUG] News feed display

### ISSUE THREAD

**Issue by duggalsu** [slapperwan/gh4a#1060]
The news feed shows the following error on app launch - 
```
You need at least read:org scope or user scope to list your organizations (403)
```
The app does not have either permissions.

However, the news feed displays if you go to 'My issues' and then press the back button.

**Comment by maniac103** [comment]
Did this occur once or is it reproducible?

**Comment by duggalsu** [comment]
It is reproducible. Tested on Android 11

**Comment by maniac103** [comment]
Can you try removing Octodroid from the list of Oauth apps in your Github settings and try again (basically a forced logout)? I want to find out if it's specific to the current state in your account or a general thing.

**Comment by duggalsu** [comment]
Works perfectly now! Possibly some issue at my end.
