### ISSUE TITLE
crash when attempting to view merged PRs: base_ref_deleted

### ISSUE THREAD

**Issue by casperdcl** [slapperwan/gh4a#1064]
`# logcat -b crash`
`01-11 20:17:10.179   555   555 E AndroidRuntime: FATAL EXCEPTION: main`
`...`
`01-11 20:17:10.179   555   555 E AndroidRuntime:com.squareup.moshi.JsonDataException: Expected one of [added_to_project, assigned, base_ref_changed, base_ref_force_pushed, closed, comment_deleted, commented, committed, connected, convert_to_draft, converted_note_to_issue, cross-referenced, demilestoned, deployed, disconnected, head_ref_deleted, head_ref_force_pushed, head_ref_restored, labeled, locked, marked_as_duplicate, mentioned, merged, moved_columns_in_project, milestoned, pinned, ready_for_review, referenced, removed_from_project, renamed, reopened, reviewed, review_dismissed, review_requested, review_request_removed, subscribed, transferred, unassigned, unlabeled, unlocked, unmarked_as_duplicate, unpinned, unsubscribed, user_blocked] but was base_ref_deleted at path $.items[17].event`
`...`

[gh4a-base_ref_deleted.log](https://github.com/slapperwan/gh4a/files/5798195/gh4a-base_ref_deleted.log)

**Comment by Unpublished** [comment]
```
Subject: [PATCH] Add more issue event types

---
 .../com/meisolsson/githubsdk/model/IssueEventType.java     | 7 +++++++
 1 file changed, 7 insertions(+)

diff --git a/library/src/main/java/com/meisolsson/githubsdk/model/IssueEventType.java b/library/src/main/java/com/meisolsson/githubsdk/model/IssueEventType.java
index 3b5b28e..f0a23c1 100644
--- a/library/src/main/java/com/meisolsson/githubsdk/model/IssueEventType.java
+++ b/library/src/main/java/com/meisolsson/githubsdk/model/IssueEventType.java
@@ -21,7 +21,14 @@
 public enum IssueEventType {
     @Json(name = "added_to_project") AddedToProject,
     @Json(name = "assigned") Assigned,
+    @Json(name = "auto_merge_disabled") AutoMergeDisbled,
+    @Json(name = "auto_merge_enabled") AutoMergeEnabled,
+    @Json(name = "auto_rebase_enabled") AutoRebaseEnabled,
+    @Json(name = "auto_squash_enabled") AutoSquashEnabled,
+    @Json(name = "automatic_base_change_failed") AutomaticBaseChangeFailed,
+    @Json(name = "automatic_base_change_succeeded") AutomaticBaseChangeSucceeded,
     @Json(name = "base_ref_changed") BaseRefChanged,
+    @Json(name = "base_ref_deleted") BaseRefDeleted,
     @Json(name = "base_ref_force_pushed") BaseRefForcePushed,
     @Json(name = "closed") Closed,
     @Json(name = "comment_deleted") CommentDeleted,
```

Some more event types I found [here](https://docs.github.com/en/graphql/reference/objects) and encountered in the wild. Feel free to pick them up @maniac103

**Comment by maniac103** [comment]
> Some more event types I found here and encountered in the wild. Feel free to pick them up @maniac103

[Done](https://github.com/maniac103/GitHubSdk/commit/204002675bd735810806a1b1d17850dd8a394f92), thank you!
I'll do a new Octodroid release soon as well.

**Comment by casperdcl** [comment]
fixed by 2040026

**Comment by maniac103** [comment]
It'll be only really fixed once I update Octodroid to use the new bindings ;-)

**Comment by Fs00** [comment]
@maniac103 This has been fixed now, right?

**Comment by maniac103** [comment]
@Fs00 Yes. The above mentioned commit is in bindings release 0.7.0.2, which the app [is using](https://github.com/slapperwan/gh4a/commit/a9b575c6083bacb32c1c3e0f49b78fe73bb16a36).

I completely forgot to close this issue, thanks for the pointer.
