### ISSUE TITLE
[Bug] Negative one (-1) issue count

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#1065]
![](https://i.goopics.net/3odra.jpg)

Unfortunately, it only happened once, and I couldn't reproduce it.

Good luck 😉

**Comment by maniac103** [comment]
That one is filled directly from an API response, so this must be a glitch in the API. I don't see anything we could change there.

**Comment by KaKi87** [comment]
Well, as you can see, I'm also still experiencing #886 too, and that one I can reproduce, quite regularly ^^
