### ISSUE TITLE
Github: Deprecating API authentication through query parameters

### ISSUE THREAD

**Issue by pappou99** [slapperwan/gh4a#1068]
Today an warning reached me with the topic  ["Deprecating API authentication through query parameters"
](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/) after downloading a release file through octodroid.

It still to works, but they seem to switch it off on May 5, 2021 at 16:00 UTC.

Please change authoritation method like described in link.

**Comment by maniac103** [comment]
It's already fixed (see #972), I just need to do a new Play Store release.

**Comment by pappou99** [comment]
I got it from F-Droid.
Please do a new Release there too.
Thanks

**Comment by gadgetguy08** [comment]
Yes, please do a new release for F-Droid (and github?).

**Comment by farfromrefug** [comment]
@maniac103 sorry to bump this but could you release 4.6.5 on github at least?

**Comment by maniac103** [comment]
@farfromrefug I actually pushed 4.6.5 to the Play Store, but forgot to push the tag (which is then picked up by F-Droid as well). Sorry for that, I pushed the tag now.
