### ISSUE TITLE
When you are following a user it still displays the follow button

### ISSUE THREAD

**Issue by ccuser44** [slapperwan/gh4a#1072]
Also follow might not work sometimes

**Comment by ccuser44** [comment]
following doesnt seem to work at all

**Comment by Fs00** [comment]
I can confirm that text for follow/unfollow button in Followers screen is swapped (it displays "Unfollow" when you are *not* following the user, and viceversa). @ccuser44 Could you maybe rename the issue accordingly?
Following works without any problem for me.

**Comment by ccuser44** [comment]
closed this due to dublicate
