### ISSUE TITLE
Font Color

### ISSUE THREAD

**Issue by sick13** [slapperwan/gh4a#1079]
Can we get a option to change the green font color,its  hard to see on black background when uskng night theme

**Comment by maniac103** [comment]
An option for free color changing won't happen (see #936), but if you have concrete improvement suggestions I'll consider it.

**Comment by sick13** [comment]
well i don't have a concrete suggestion,just pointing out that it's hard to see

**Comment by sick13** [comment]
well i don't have a concrete suggestion,just pointing out that it's hard to see

**Comment by sick13** [comment]
Well thank you very much for this improvement kind sir.
