### ISSUE TITLE
Upload images to GitHub

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [slapperwan/gh4a#1084]
Is it possible to automatically upload images to GitHub like in the browser instead of uploading to a 3rd party host like Imgur? I can imagine GH not allowing it because of abuse but just in case I'll ask.

**Comment by maniac103** [comment]
Dupe of #297, I guess?

**Comment by IHateTheProgrammingClass** [comment]
@maniac103 Yes, I'll close. Btw wouldn't the uploaded photos to Imgur stay there forever? Let's say I accidentally upload a photo of my ID wouldn't it stay there?
