### ISSUE TITLE
[Bug] markdown mailto links not working

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#1090]
Example :

```markdown
You can contact me by [email](mailto:foo@bar.com)
```

Expected :
```
mailto:foo@bar.com
```

Actual :
```
https://raw.githubusercontent.com/user-or-org/repo/main/mailto:foo@bar.com
```

Thanks

**Comment by Fs00** [comment]
I couldn't reproduce this issue (see e.g. Fs00/gh4a#1), how did you encounter it?

**Comment by KaKi87** [comment]
Oh, time has passed, I'm afraid I forgot already. 😅

**Comment by KaKi87** [comment]
Also I can't try anything right now, until #1101 is released.

**Comment by maniac103** [comment]
I plan to do the release tomorrow. Until then, you can use search to navigate to a given repository.
