### ISSUE TITLE
Not possible to login on Android 11

### ISSUE THREAD

**Issue by AsciiWolf** [slapperwan/gh4a#1091]
Pixel 5 with latest Android 11. When trying to login using OAuth, I get a "no browser was found on your device" error; when trying to login using username/password, I get a "Loading the data from Github failed (404)" error. It worked without any issue on Android 10.

**Comment by sunng87** [comment]
I have the same issue on Android 11 when multiple browsers are installed on my device.

**Comment by SeanChengN** [comment]
The same problem occurred in the [official app](https://play.google.com/store/apps/details?id=com.github.android)

**Comment by Saramagrean** [comment]
Same here v4.6.6 can't login, but v4.6.5 it work fine.

**Comment by KaKi87** [comment]
Here's an email from the developer of Kiwi Browser to Google (source : Discord).

![](https://cdn.discordapp.com/attachments/494814211579445274/880870814512189460/Screenshot_20210827-204602.jpg)

I think the situation is more complicated than it looks.

**Comment by SynapseScribe** [comment]
still having error "no browser was found on your device" when tryin to open an issue in browser
