### ISSUE TITLE
[Bug] "Open in browser" no longer working (same one as before)

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#1098]
![](https://i.goopics.net/9nxol.jpeg)

Used to work, some time ago, with the same browser I'm still using today, which is Kiwi Browser (Chromium-based).

**Comment by KaKi87** [comment]
Well, it seem so.

**Comment by SynapseScribe** [comment]
still having error "no browser was found on your device" when tryin to open an issue in browser
