### ISSUE TITLE
[Bug] Direct wiki article links always redirects to "recent wiki updates"

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#1127]

**Comment by Fs00** [comment]
Do you have an example of such a link?

**Comment by KaKi87** [comment]
Easy.

For example, clicking this link : https://github.com/slapperwan/gh4a/wiki/Information-hierarchy

Leads here :

![](https://cdn.discordapp.com/attachments/493524617714204672/914203765983313971/Screenshot_20211127-181909.png)

Instead of leading here :

![](https://media.discordapp.net/attachments/493524617714204672/914203765698089011/Screenshot_20211127-181913.png)

Thanks
