### ISSUE TITLE
Cannot search issues

### ISSUE THREAD

**Issue by JohnVeness** [slapperwan/gh4a#113]
It would be great if we could search issues (title, description, and, I guess, comments).

**Comment by moshpirit** [comment]
:+1:

**Comment by Sohalt** [comment]
+1 searching issues is really important to check whether an issue already exists before opening a new one. This greatly helps avoiding duplicates. (Also it would be cool if when creating a new issue the app could automatically search for similar issues based on the title and description and show them to help avoid duplicates)
