### ISSUE TITLE
Search in Readme

### ISSUE THREAD

**Issue by yephny** [slapperwan/gh4a#1138]
It's currently not possible to search in readme, the one that appears when you go to a repository, in the about page. There are quite long and informative [readmes](https://github.com/VR-25/acc) that I like referencing, where I feel the need to search, so I open the page in a browser.

**Comment by maniac103** [comment]
Why not open the readme in the files list to get search? The one in the repo overview is just meant to get a quick overview.

**Comment by yephny** [comment]
Makes sense.
