### ISSUE TITLE
Back button issues

### ISSUE THREAD

**Issue by yephny** [slapperwan/gh4a#1142]
1. Click a link to a Github repository to open with OctoDroid.
2. Go to issues and search for a keyword.
3. Open one of the issues in the search results.
4. Press the back button on the top left corner to go back to the search results.
5. The default issues page will appear instead of search results, making it difficult to find an issue.

**Comment by maniac103** [comment]
This is intentional. See discussion in #1085. Solution: use the device's back button if you just want to go back in temporal navigation.

**Comment by smichel17** [comment]
Yes, but this *has* been a source of regular issues. Maybe we could use a different icon for the back button (like an up arrow instead of a left-arrow) to indicate that it does something different.

**Comment by yephny** [comment]
@maniac103 That is incorrect. Using the device's back button results in going back to the app where you clicked the github link.

**Comment by smichel17** [comment]
I cannot reproduce that :(. I used an F-Droid "source code" link; the back button took me back to my search. (Android 7.0, Galaxy S6)

**Comment by yephny** [comment]
Wouldn't you rather re-open it?

**Comment by maniac103** [comment]
For what reason? We surely can't change whatever that app is doing.

**Comment by yephny** [comment]
Because it still has to do with OctoDroid even if the action is triggered by another app in this particular case. No matter what app I use to open github links in OctoDroid, the app's back feature should work as expected.

**Comment by maniac103** [comment]
Hmm, maybe you're right. I thought the app somehow triggers activity closes, but it rather seems like it's triggering task brokenness ... that is, I get to some other random Octodroid window once I press back in your scenario.
I'll need to check this.
