### ISSUE TITLE
Opening a Github link doesn't work when you're already viewing a page

### ISSUE THREAD

**Issue by yephny** [slapperwan/gh4a#1163]
I was checking out the releases section of some software, then I went back to my browser without closing OctoDroid and clicked on a Github link to the issues page of a different repository, but OctoDroid stayed on the same releases page. This happened until I hit the back button (system back, not the in-app back button) a few times and tried again.

**Comment by maniac103** [comment]
This sounds like a dupe of #1145?

**Comment by yephny** [comment]
That seems to be it, forgot to check closed issues as well. I'll be waiting for the release that includes the fix to test it, thanks.
