### ISSUE TITLE
Create widget or app name in settings to rename app

### ISSUE THREAD

**Issue by realmebran38** [slapperwan/gh4a#1189]
For better or worse somehow I am unable to remember the name this app? (Sorry). I would rather prefer it to be the name of this website :-) 
Would it be possible to add an option that would say "Rename launcher as user-chosen-string". Or add a shortcut or via widget... 
Thanks

**Comment by maniac103** [comment]
Renaming the launcher icon is not possible as app feature, but there are some launchers that allow renaming of app entries.
