### ISSUE TITLE
Paged lists stop loading new items after the screen gets rotated

### ISSUE THREAD

**Issue by Fs00** [slapperwan/gh4a#1194]
I've encountered a bug in all paged lists (releases list, commits list, stargazers list... actually all those inheriting from `PagedDataBaseFragment`) caused by screen rotation.
Basically, after the user rotates the screen, scrolling at the bottom of the paged list doesn't trigger the loading of the next page. The _Loading..._ indicator is shown but nothing happens.

**Comment by maniac103** [comment]
Initial inspection shows this is due to `RxLoader` not subscribing to the upstream observable if it can deliver a previously loaded value, which is why `mPageSubject.onNext(mNextPage)` becomes a no-op because `mPageSubject` does not have any observers.
Not sure about the correct fix though...
