### ISSUE TITLE
Starred repos of another user

### ISSUE THREAD

**Issue by maliayas** [slapperwan/gh4a#1198]
Is it currently possible to see some other user's starred repos?

The only way I see is going to the list of user's repos and then filtering by "starred" which gives no response at all.

**Comment by maliayas** [comment]
Screenshot:

![IMG_20220420_194253](https://user-images.githubusercontent.com/844008/164288421-b4f876ab-f22c-46fd-ac3c-588e8911272e.jpg)

**Comment by Fs00** [comment]
The bug has been fixed in #1190. The fix will be included in the next release.
