### ISSUE TITLE
Break color highlight after " ' "

### ISSUE THREAD

**Issue by hummermania** [slapperwan/gh4a#120]
I read content on some Erlang projects, and see that after symbol " ' " in the comment area (%) we have breaking color highlight. 
For example: 
https://github.com/erlang/otp/blob/maint/lib/appmon/src/appmon_web.erl ,  line: 185.
Browser highlight it normally, but in the OctoDroid we see wrong color.

**Comment by maniac103** [comment]
Fixed with https://github.com/slapperwan/gh4a/commit/c6fb045d4f022369f809554b38706aea00ff8b15
