### ISSUE TITLE
Opened issues do not get marked as read anymore

### ISSUE THREAD

**Issue by ltGuillaume** [slapperwan/gh4a#1227]
This used to work fine, but since a couple of months OctoDroid seems to have become unable to mark an issue as read after opening it. 

Perhaps GitHub has changed their API, possibly to incorporate the distinction between "read" and "done"? 

Manually marking an issue as read from the Notifications screen (either via the context menu or the double checkmarks) still works, though. 

OctoDroid 4.6.8 F-Droid
Android 11

**Comment by Fs00** [comment]
The bug has already been fixed in #1214, the fix will be included in the next release.
