### ISSUE TITLE
Version 4.6.9 is not on the Play Store yet

### ISSUE THREAD

**Issue by Fs00** [slapperwan/gh4a#1251]
It seems that version 4.6.9 hasn't been released on the Play Store yet.
After November 1 the Play Store [won't accept anymore apps targeting SDK < 31](https://developer.android.com/google/play/requirements/target-sdk), so there isn't much time left to release this update :running_man:

**Comment by maniac103** [comment]
I needed to update some bureaucratic stuff (e.g. add a privacy policy), and apparently I had to click a button to submit both the app update and those other updates. I've clicked it now.

**Comment by maniac103** [comment]
And, FWIW, that policy BS is due to the permission added in #1130.

**Comment by maniac103** [comment]
```
Issue found: Permission use is not directly related to your app's core purpose.

We found that your app is not compliant with how REQUEST_INSTALL_PACKAGES permission is allowed to be used. Specifically, the use of the permission is not directly related to the core purpose of the app.

Additionally, follow these steps to bring your app into compliance:

    Please remove the use of [REQUEST_INSTALL_PACKAGES](https://notifications.google.com/g/p/AKWoLQhM9gcdlYSuKcWN7hwZPw5PzMQzH0ZQo3T30nH69C_GqVWyFQN-EuC3TfFE55FCO4ykXMRsLqnFtfYT1gNRfa7uGXLrjz6P2i22gMZS2oloF-ru2Dfap78rD1xO-b2mE7sd2HzRPeS__bbZOW79frDv4pnVmdXu4GUv8-LPd3wushrfxwEvOCej) permission from your app.

About the Request Install Packages Permission

The [REQUEST_INSTALL_PACKAGES](https://notifications.google.com/g/p/AKWoLQhM9gcdlYSuKcWN7hwZPw5PzMQzH0ZQo3T30nH69C_GqVWyFQN-EuC3TfFE55FCO4ykXMRsLqnFtfYT1gNRfa7uGXLrjz6P2i22gMZS2oloF-ru2Dfap78rD1xO-b2mE7sd2HzRPeS__bbZOW79frDv4pnVmdXu4GUv8-LPd3wushrfxwEvOCej) permission allows an application to request the installation of app packages. To use this permission, your app’s core functionality must include:

    Sending or receiving app packages, AND
    Enabling user-initiated installation of app packages.

Permitted functionalities include any of the following:

    Web browsing or search
    Communication services that support attachments
    File sharing, transfer or management
    Enterprise device management
    Backup and restore
    Device migration / phone transfer

The [REQUEST_INSTALL_PACKAGES](https://notifications.google.com/g/p/AKWoLQjtrVQGiDcMz7WsJjWBJOv6qUouXyS8q2idypwvvcc4E9q5AzHSPJ7oQgzZtHlVqm0T23sQgC7p7IKWr8n8ifn3jj1oYMe68NL7igYUPfoj7YZebKp8U1srYeWM00WhpwlET0a4jQAVG5gsgkDhmji8lxYk) permission may not be used to perform self updates, modifications, or the bundling of other APKs in the asset file unless for device management purposes. All updates or installing of packages must abide by Google Play’s Device and Network Abuse policy and must be initiated and driven by the user.
```

-> https://github.com/slapperwan/gh4a/commit/f6f325e25ac826f09aee21e79dcd63ccd9562436

**Comment by Fs00** [comment]
I need to say it this time: f*ck Google and their absurdly restrictive policies. 😤

Could we have a different flavor of the app for the Play Store that doesn't have this permission, so that APKs on GitHub and F-Droid can have it?
IMO that permission greatly improves the user experience when downloading APKs and we also had an issue related to that (#1067)

**Comment by maniac103** [comment]
> Can we have a different flavor of the app for the Play Store that doesn't have this permission, so that APKs on GitHub and F-Droid can have it?

Fine with me, I guess ... I just didn't have the time to do this setup *now*.
I tried to explain our usage of that permission to them, including a screen cast and links to #1067 and #1130, but it seems that wasn't sufficient. In a way they're right with `is not directly related to your app's core purpose`, but I agree it feels overly restrictive.

**Comment by Fs00** [comment]
4.6.10 is now available on the Play Store, so I'm going to close this.
I'll open another issue for the possible reintroduction of the REQUEST_INSTALL_PACKAGES permission on GH and F-Droid builds.
Thanks for trying to convince Google reviewers 🙏

**Comment by elig0n** [comment]
The app looks missing from the play store now, any update on this ?
