### ISSUE TITLE
[Bug] Markdown hyperlink working in browser but not in OctoDroid

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#1265]
Hello,

The "Available for Chromium" picture link on [this README](https://github.com/libredirect/libredirect) works in browser but returns 404 on OctoDroid.

Thanks

**Comment by Fs00** [comment]
Everything works fine on my side, could you check again?

**Comment by KaKi87** [comment]
One and a half year later, obviously it does :sweat_smile:
