### ISSUE TITLE
[Bug] Crash when trying to open issue

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#1269]
That one : https://github.com/zitadel/zitadel/issues/3598#issuecomment-1412146105

Error stack : https://paste.crdroid.net/e1LyMM

Thanks

**Comment by Fs00** [comment]
Could you please check on version 4.6.11? It doesn't crash on my side.

**Comment by KaKi87** [comment]
I confirm it's no longer crashing.
