### ISSUE TITLE
Add ability to copy release file download link

### ISSUE THREAD

**Issue by the-blank-x** [slapperwan/gh4a#1275]
I want to use a different downloader, so I'd like to be able to copy the download URL for a file. This could be implemented by holding down on the file, or adding a copy link button.

![](https://files.catbox.moe/r6naki.jpg)

**Comment by Bnyro** [comment]
In my opinion, it makes a lot more sense to use the permanent one, as you likely want to use the copy function for sharing the link to others.

**Comment by Vethya** [comment]
Alright, I got it. I would like to give this a try.
