### ISSUE TITLE
Default view

### ISSUE THREAD

**Issue by meviox** [slapperwan/gh4a#128]
Currently, after launching the app the initial start view is always the "About" page. However, I usually first check the "News Feed". Thus, I would really like to have an option to choose a preferred default start view.

**Comment by maniac103** [comment]
This will be fixed when the navigation-reorg branch is merged back. @slapperwan Opinions on doing that ASAP and releasing a 3.9? :)

**Comment by slapperwan** [comment]
So the 3.9 release is from master?

**Comment by maniac103** [comment]
@slapperwan I don't understand the question...what do you mean exactly?

**Comment by maniac103** [comment]
Fixed with commit 4fdb02b713403c209e112d7f81c1b4fdb2726e17
