### ISSUE TITLE
Need a confirmation when closing an issue.

### ISSUE THREAD

**Issue by klieber** [slapperwan/gh4a#129]
I can't tell you how many times I've accidentally closed an issue just by putting my phone in my pocket. It would be great if you could add a confirmation before actually closing it. It might eveb make sense to have it be a configurable setting for those that like the current behavior. Thanks!

**Comment by Tunous** [comment]
Working on this.

**Comment by JohnVeness** [comment]
Actually, the modern way is to have an undo feature rather than a confirmation.

**Comment by Tunous** [comment]
Well the undo feature is just reopening if you closed or closing again if you reopened. These actions aren't final. I think it's good to add confirmation here though as these actions are logged in the issue activity and delaying sending them to server to implement not-logging doesn't sound good for me.
