### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by sebastien46** [slapperwan/gh4a#1302]
Hi,
There's been 37 commits to the master branch since the [last release](https://github.com/slapperwan/gh4a/compare/4.6.10...master), which is from a year ago.
There's a lot of nice bug fixes & QoL improvement, such as the SDK bump.
If these new changes could be released I think this application's users, including myself, would greatly appreciate it.

**Comment by seirdotexe** [comment]
+1 would be very nice.

**Comment by Joshndroid** [comment]
Its been another few months and it no real update....

**Comment by sebastien46** [comment]
https://github.com/slapperwan/gh4a/releases/tag/4.6.11
