### ISSUE TITLE
Issue's templates does not show to choose 

### ISSUE THREAD

**Issue by hetszunyukapanyanyimonyok** [slapperwan/gh4a#1315]
When opening new issues on any GitHub repo there is a problem that we can't see the issue templates.
What the user has to choose from!
Example
![Screenshot_20240125-123335_1](https://github.com/slapperwan/gh4a/assets/148961071/40619658-614d-454e-bb3a-d2e3db77aff4)

Please if you have time implement this ability to choose from templates.

**Comment by Fs00** [comment]
This is a known issue: see #1159

**Comment by maniac103** [comment]
Indeed, that's a dupe of #1159
