### ISSUE TITLE
App is missing on Google Play Store 

### ISSUE THREAD

**Issue by elig0n** [slapperwan/gh4a#1319]

**Comment by maniac103** [comment]
See discussion [here](https://github.com/maniac103/GitHubSdk/pull/17#issuecomment-1794272751) ... I don't see how I could fulfill their request.

**Comment by elig0n** [comment]
well in the meantime maybe you can add a memo of it on the README because I was trying to find updates for the app since it was misbehaving and not being able to find in the Google Play Store was alarming

**Comment by Fs00** [comment]
If keeping up with Google demands has become too much of a hassle, why not just release the app only on F-Droid and here on GitHub and call it a day?

**Comment by ds84182** [comment]
It's also not possible to migrate from the play store version to the fdroid version without uninstalling because fdroid signs the APK themselves.

**Comment by maniac103** [comment]
That's right, but I don't see any chance of a Play Store release because I don't see how to fulfill their request in a legally proper way.

**Comment by ds84182** [comment]
The past GitHub releases are signed with the same key as the play store version.

**Comment by maniac103** [comment]
Yes, indeed. What exactly is your point though? I can't sign the GH release with F-Droid's keys.

**Comment by ds84182** [comment]
There wasn't a GitHub release, just a release tag. But I see you just added a new release, thanks.

**Comment by maniac103** [comment]
OK, I didn't get that link ... Nevermind then ;-)

**Comment by Fs00** [comment]
Since new releases aren't going to be released on the Play Store anymore, I guess that this issue can be closed?
Also, the Readme still displays the Play Store badge, which should probably be removed at this point.

**Comment by geotheory** [comment]
This repo needs to be updated to make clear the project is retired.

**Comment by maniac103** [comment]
> to make clear the project is retired.

Except it isn't. New development is unlikely at this point, but bug fixes still happen.
