### ISSUE TITLE
Android notifications are no longer individually actionable

### ISSUE THREAD

**Issue by Terrance** [slapperwan/gh4a#1358]
Before version 4.6.11, each GitHub notification produced a corresponding Android notification, and tapping it would take you to the relevant place.  As of 4.6.11, multiple GitHub notifications seem to be grouped into one Android notification:

<img src="https://github.com/slapperwan/gh4a/assets/4025899/5391f12c-63cd-4461-9fc6-3aebff7dc0f7" width="400"> <img src="https://github.com/slapperwan/gh4a/assets/4025899/1428983e-7a60-4f53-a131-59b4b17e895e" width="400">

Tapping anywhere on this notification just takes you to the Notifications screen and dismisses the notification.

I'm not sure if this was changed intentionally or just as part of other refactoring (as the last release was close to 2 years ago I'm not sure when exactly this changed), but it is useful to have individual notifications -- Android already groups and collapses multiple of them per application, and I like to keep certain notifications present as a reminder until I action them.

**Comment by maniac103** [comment]
That was an issue due to Android target SDK bump. I fixed this earlier today: https://github.com/slapperwan/gh4a/commit/6fbade402b5e164a1c47b55814ba93b425c19576
