### ISSUE TITLE
Support Github Android account

### ISSUE THREAD

**Issue by JohnVeness** [slapperwan/gh4a#147]
The official Github Android client adds a Github "account" into the Android system settings window. I don't know if it's technically possible for OctoDroid to do this, but it would be useful if OctoDroid could use this account when logging into Github, rather than having to type in the username/password again.

**Comment by jayvdb** [comment]
Fwiw, it is now https://github.com/pockethub/PocketHub/ , but it looks like they will re-release soon

**Comment by maniac103** [comment]
Given PocketHub is not any more official than we are (and has a much smaller installation base), closing this one.
