### ISSUE TITLE
Bigger button for submitting comments on issues

### ISSUE THREAD

**Issue by JohnVeness** [slapperwan/gh4a#148]
When writing a comment on an issue, to the right of the textbox is a button the can be pressed to submit the comment. As the comment gets longer (multiple lines), it would be good if you could click anywhere in the righthand area to submit the comment, rather than having to click exactly on the rather small icon. In other words, keep the app looking visually the same as it does currently, but with a larger area that will react to presses.

**Comment by LumenTeun** [comment]
I have to disagree with this. Designating an activity to a blank area just seems strange to me, and would probably cause more accidentally sent comments than is justifiable.

**Comment by JohnVeness** [comment]
Yes, you're probably right. I'm happy for this issue to be closed.
