### ISSUE TITLE
Add 2FA Support

### ISSUE THREAD

**Issue by agilob** [slapperwan/gh4a#160]
Currently I'm not able to login with enabled 2FA on GH account.

http://developer.github.com/v3/auth/#working-with-two-factor-authentication

![screenshot_2014-03-10-18-44-42](https://f.cloud.github.com/assets/2544251/2377601/af5c42ea-a884-11e3-804f-0cc250bcc964.png)

**Comment by LongJohn-Silver** [comment]
I still can't log in?
