### ISSUE TITLE
Implement GitHub Notifications

### ISSUE THREAD

**Issue by LeoColomb** [slapperwan/gh4a#175]
It should be really useful to add a panel with GitHub notifications, near the news feed.
The API seems simple to use: https://developer.github.com/v3/activity/notifications/

In a second round, it can help to solve #42.

**Comment by tsdh** [comment]
That's indeed the thing I'm missing most.

**Comment by LumenTeun** [comment]
+1

I'm not too familiar with the Android notification system, but if this is implemented, would it be possible get system notifications either directly or at set intervals of time?

**Comment by alorma** [comment]
The only wa to display into statusbar, is making request in a specific interval of time, and check if there are some notifications.

**Comment by LumenTeun** [comment]
I thought that might be the case. Still, that would be useful.

**Comment by geovanisouza92** [comment]
Please, don't poll, push it.

**Comment by alorma** [comment]
It cannot be push(ed), because Github doesn't provide an extension for that.

But, using SyncAdapter should not affect tle battery life, is just one poll each.... hour?

**Comment by KAMiKAZOW** [comment]
This bug report is not about Github notifications in the Android status bar. It's about notifications support in-app.

**Comment by JohnMaguire** [comment]
@alorma Push is still possible by offloading polling and pushing to a cloud server. Whether it's worth it or not is a different question.

**Comment by alorma** [comment]
Gitskarios will support push notifications soon

**Comment by maniac103** [comment]
#shamelessplug

**Comment by TR4Android** [comment]
:+1: Github Notifications are one of the few things I'm currently missing.

**Comment by julmot** [comment]
:+1:

**Comment by fountaingeyser** [comment]
:+1:

**Comment by kevinkhill** [comment]
:+1:

**Comment by Nxt3** [comment]
Any plans for this?

**Comment by laughedelic** [comment]
Any news?

**Comment by KAMiKAZOW** [comment]
https://github.com/gitskarios/Gitskarios implemented that feature, btw.

**Comment by alorma** [comment]
Since a long time ago ;)

**Comment by maniac103** [comment]
Yeah, with an own server etc., which I certainly don't plan to have/use. We concentrated on other stuff, so I'm not sure what the Gitskarios reference is supposed to tell us.

**Comment by alorma** [comment]
It's just a heroku instance.

**Comment by Tunous** [comment]
I'm working on this one. Going to implement a new screen for viewing notifications and marking them as read together with the API part. System notifications won't be a part of it. Just manual checking.

**Comment by maniac103** [comment]
:+1:

**Comment by julmot** [comment]
Instead of posting 👍 start adding "reactions"!

**Comment by maniac103** [comment]
If the reactions API were out of preview, I perhaps would do that...

**Comment by sbrl** [comment]
@maniac103 It is in preview? I think @ julmot is talking about using the web version of GitHub to react to this issue rather than posting a comment.

**Comment by maniac103** [comment]
@sbrl I interpreted it as a subtle (?) hint to implement reactions in OctoDroid.

**Comment by maniac103** [comment]
Implemented in #462.
