### ISSUE TITLE
Add fast scrolling again

### ISSUE THREAD

**Issue by marco-dev** [slapperwan/gh4a#233]
You switched layout of issue content to fast scrolling some time ago. It is not working anymore. Any reason why? If has long content you need to scroll a long time.

**Comment by Tunous** [comment]
Some libraries I found:

- https://github.com/timusus/RecyclerView-FastScroll
- https://github.com/FutureMind/recycler-fast-scroll
- https://github.com/plusCubed/recycler-fast-scroll
- https://github.com/danoz73/RecyclerViewFastScroller
- https://github.com/AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller

**Comment by maniac103** [comment]
The FutureMind and danoz73 ones look good on first sight, but the latter seems to be abandonware.

**Comment by Tunous** [comment]
I've implemented 4 of them and here you can see the results:

1) https://github.com/Tunous/gh4a/commit/04d59ce24b1fc7dabffe664c63e3f8bbc1afded2
2) https://github.com/Tunous/gh4a/commit/4fafac36e7bbda4762a3c1aae6d23a4d4d34a9ad
3) https://github.com/Tunous/gh4a/commit/49100edee7e62f38b3355729c4cb74c65c55be06
4) https://github.com/Tunous/gh4a/commit/49100edee7e62f38b3355729c4cb74c65c55be06

The option 4) is the best in my opinion. The scrolling is not laggy and the scrollbar correctly adapts to items of varying heights (unlike the other libraries). There are many customization options so we can make it look how it want and it looks like it could be also possible to integrate it with AppBarLayout scrolling (that's not necessary based on my tests).

*I've numbered libraries in my previous comment so you can match them with above implementations.*

**Comment by maniac103** [comment]
Indeed. Shows how misleading judgement from only reading the readme can be ;-)
When implementing this 'for real', I'd like to see it being enabled only selectively though - in particular I think it's not suited well for paging lists. Large issue/PR conversations really are the most compelling use case for it.

**Comment by Tunous** [comment]
I don't entirely agree. IMO it's useful to have it available in News Feed which is a paging list. The reason for that is that I could have that screen already open and scrolled and would like to refresh data. Right now I would have to do a lot of scrolling or close and open the app again. 
Similarly it could be also useful to quickly reach the position where I recently stopped reading news feed but closed the app. 

I think that these use cases might also work for other paging screens like notifications, repository commits.

**Comment by maniac103** [comment]
I wouldn't necessarily oppose it, but we'd need to make its appearance much more subtle then. I just don't like that 'blocky' scrollbar. Maybe only make it appear when touching its touch target or something?

**Comment by Tunous** [comment]
![peek 2017-03-23 18-45](https://cloud.githubusercontent.com/assets/5156340/24261970/f20fb7e6-0ff8-11e7-83e1-fe524f93b009.gif)

It looks exactly like the current scrollbar but is wider to allow for easy touching.

> Maybe only make it appear when touching its touch target or something?

This would make it so hardly anyone will know that this feature exists.

I'm myself happy with what you can see in above gif. Maybe only the pressed colors could be a bit improved... (especially purple)
