### ISSUE TITLE
provide capabilities to use octodroid with gogs code hosting software

### ISSUE THREAD

**Issue by robinpaulson** [slapperwan/gh4a#239]
It is free software and does not rely on a third-party as Github does.
http://gogs.io

Also (but less important) support for Gitlab would be great, although this is already supported by GitLabAndroid
http://gitlab.org
https://github.com/ekx/GitLabAndroid

**Comment by maniac103** [comment]
Octodroid is tied pretty strongly to the Github Java bindings and its data types. Support for other code hosting services is unlikely to happen.

**Comment by robinpaulson** [comment]
Hmm, it's a shame more people don't follow the unix philosophy, then problems like this wouldn't crop up - we'd have a bunch of interchangeable modules which interlinked. Rather, a series of monolithic app and API combinations, each of which are completely distinct from all other combinations. Are we going backwards?

**Comment by ocdtrekkie** [comment]
@robinpaulson We are absolutely going backwards. (Especially when things like "Material Design" come up.) But effectively the scope of this app has been set, and asking a developer to massively extend it is probably not going to go anywhere.

**Comment by maniac103** [comment]
This app already follows the Unix philosophy, which is 'do one thing and do it right'. Increasing the scope of the app would directly contradict that.
