### ISSUE TITLE
Clarify license of code

### ISSUE THREAD

**Issue by ocdtrekkie** [slapperwan/gh4a#242]
Is Octodroid "proprietary"? The NOTICE file doesn't seem to assign any license to the Octodroid code other then a Copyright date, and the README refers to open source packages in use, but again, not that the code is open source.

**Comment by krt16s** [comment]
The sourcecode refers to Apache2, however there are some files without an explicit notice, e.g.

https://github.com/slapperwan/gh4a/tree/master/src/com/gh4a
https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/TwoFactorAuthException.java
https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/BasePagerActivity.java
https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/BackgroundTask.java
https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/BrowseFilter.java
https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/ClientForAuthorization.java
https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/ColorPickerDialog.java
https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/DefaultClient.java
https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/ProgressDialogTask.java

If this wasn't intenionally done so, it would be good to add a overall LICENSE or COPYING file or even just add a note to the readme to calrify things.

**Comment by maniac103** [comment]
At least for the parts of the code I contributed, the intention was to put it under Apache2. I believe the missing license on some files was just an oversight. @slapperwan Any comments?

**Comment by slapperwan** [comment]
Yes, all source codes are under Apache2.  I will a LICENSE file.

**Comment by slapperwan** [comment]
Added license file
