### ISSUE TITLE
Dividers between tabs

### ISSUE THREAD

**Issue by KDB223** [slapperwan/gh4a#245]
In the Material Design theme, there shouldn't be dividers between tabs of the viewpager.
So I think
```<color name="divider_bg">#bdbdbd</color>```should be```<color name="divider_bg">#00000000</color>```

**Comment by maniac103** [comment]
Yeah, that's a valid point.

**Comment by maniac103** [comment]
The tab labels can also get a little larger font (comparing to e.g. the Lollipop contacts app or Play Music)

**Comment by KDB223** [comment]
Official specs say 14sp Roboto Medium for the tabs.

**Comment by maniac103** [comment]
Yeah, and currently it's 12sp IIRC.
