### ISSUE TITLE
Bad theming in dropdown on search screen

### ISSUE THREAD

**Issue by cjleighton** [slapperwan/gh4a#248]
On the search screen, the dropdown with "Repositories" and "Users" is black and very hard to read. Very minor, just thought I'd point it out.

**Comment by maniac103** [comment]
I don't see a problem. For me, the popup is black-on-white for the light theme and white-on-very-dark-grey for the dark one. Do you have a screenshot?

**Comment by cjleighton** [comment]
![screenshot_2015-05-20-17-23-22](https://cloud.githubusercontent.com/assets/12013117/7738745/1aca5b2e-ff15-11e4-9b66-05278551c8d6.png)
My device is on KitKat, which may be causing it.

**Comment by maniac103** [comment]
Huh, that's the dark popup background. I wonder whether your phone's manufacturer screwed up the theme. What device is that?
In any case, I'll try with the Kitkat emulator.

**Comment by maniac103** [comment]
I can repro it in the Kitkat emulator; I'll look into it.
