### ISSUE TITLE
Reduce header size for issues

### ISSUE THREAD

**Issue by dmolineus** [slapperwan/gh4a#250]
Great new material design. Struggled with a small issue. If issues have some details which are displayed in the header it's get to big so reading the comments is hard.

Works be nice if some information will be hidden if the use starts to scroll.

https://www.dropbox.com/s/iyh3uicl2j2f79j/Screenshot_2015-05-22-19-54-17.png?dl=0

**Comment by maniac103** [comment]
I noticed the same thing in the meantime, hence https://github.com/slapperwan/gh4a/commit/17505e044177b6105395e450a5b84f1169c6e0cb ;) At first I thought it's a good idea, but it was a bit overdone that way.

This is how it looks now: https://docs.google.com/file/d/0B0hmLAh3l4oHZmdJcTZaTDFFVTA/edit?usp=docslist_api

**Comment by maniac103** [comment]
(And I wanted to hide it on scroll instead of moving it out of the header as well, but that's very hard to do in a way that is backwards compatible up to Gingerbread)

**Comment by dmolineus** [comment]
Okay, good to know. 

I only checked the issues and not your commit log. ;)
