### ISSUE TITLE
allow selection of text

### ISSUE THREAD

**Issue by KOLANICH** [slapperwan/gh4a#251]
It'd be good to be able to select the text and copy it

**Comment by maniac103** [comment]
I'd think one would want to enable this only selectively though. Do you have anything specific in mind? Issue description and comments, commit message comes to my mind, anything else?

**Comment by alorma** [comment]
Readme content?

Source content?

**Comment by maniac103** [comment]
Readme is a good point, source should be copyable anyway (because it's a WebView).

**Comment by jawshooah** [comment]
> I'd think one would want to enable this only selectively though.

Why? Can you think of a situation where you explicitly *don't* want someone copy/pasting text?

**Comment by maniac103** [comment]
As this is something that is off by default, the question is backwards ;) I'm having a hard time imagining that somebody wants to copy e.g. the timestamp text or the name of a commenter.

**Comment by jawshooah** [comment]
Timestamp text, probably not. Commenter seems likely though for @mentions.

**Comment by jawshooah** [comment]
Most important though are source (already taken care of, as you said) and issue/PR description and comments.
