### ISSUE TITLE
Quoting

### ISSUE THREAD

**Issue by KOLANICH** [slapperwan/gh4a#252]
It would be nice if it was possible to select the text in issue and quote it without clipboard.

**Comment by maniac103** [comment]
How is quoting done normally (e.g. in Github's web frontend)?

**Comment by jawshooah** [comment]
Use the `>` character before the line.

```
For example:

> This is a quoted line.
> And another.
```

[Source](https://guides.github.com/features/mastering-markdown/).

**Comment by KOLANICH** [comment]
>Use the > character before the line.
I mean that when I select the text in an issue there should appere abutton which immediately quotes selected text.

**Comment by Tunous** [comment]
Might be possible to do this using https://developer.android.com/reference/android/widget/TextView.html#setCustomSelectionActionModeCallback(android.view.ActionMode.Callback)
