### ISSUE TITLE
Replace green with black in black theme

### ISSUE THREAD

**Issue by KOLANICH** [slapperwan/gh4a#253]
Black themes are for devices with amoled screens, because more screen area is black, less is power consumption and display wear.

**Comment by maniac103** [comment]
I'm not sure where the notion that the dark theme is meant for AMOLED screens comes from. It's purpose is just to please people would prefer to read white-on-black text, nothing else. Given we're talking about a negligible difference in power consumption, we're not likely to change anything in the header color, especially as it contains information in some cases (e.g. issue state). See also the discussion in issue #246 - it also contains a like where the power consumption is measured. The difference between black and white is about 30%, but a) the header is 20% of the screen size max, b) there's more to a device's power consumption than just the screen and c) Octodroid follows the platform theme, thus isn't purely black anyway.
