### ISSUE TITLE
Only public organizations shown

### ISSUE THREAD

**Issue by jomo** [slapperwan/gh4a#256]
I'm in some organizations that I haven't set to public. They don't show up in OctoDroid, would be nice to have these, too.

------

*All in all the app has a very clean interface and works great. Thanks and awesome job!*

**Comment by maniac103** [comment]
I noticed the same thing, but only recently. Can you confirm that this behaviour is new?

Anyway, I'll check this.

**Comment by jomo** [comment]
just started using octodroid today so I don't know, sorry
