### ISSUE TITLE
Wrap long lines

### ISSUE THREAD

**Issue by jomo** [slapperwan/gh4a#257]
Long lines don't break, so you need to scroll sideways, which is quite annoying:
![screenshot](https://i.imgur.com/pSBAXYZ.png)

Not wrapping lines may be useful in some cases (e.g. alignment, ascii-art, tables, etc) so it would be nice to have an option to toggle this, perhaps in the menu (top right) in the file view.

**Comment by maniac103** [comment]
I'll see whether this is possible with the WebView. You do know about the font size option though, right?

**Comment by jomo** [comment]
yes, you can also pinch to zoom in/out, but some lines are so long that they're too small to read then.

if you can manipulate the CSS in the webview, you could change the `white-space` and `break-word ` attributes.

**Comment by maniac103** [comment]
It's easier than I thought :)
