### ISSUE TITLE
Scrolling in 'Downloads' section of 'Releases'

### ISSUE THREAD

**Issue by mfonville** [slapperwan/gh4a#260]
Under the releases-view, the downloads are shown in a very small frame. If there is (too much) text for the release itself, this frame cannot be scrolled at all, and you only see 1 download. If there is no text, and there are more downloads, you can only still see 1 download at the time when scrolling.

I would suggest to enlarge the combine the area of the text and the downloads together, and make the whole scrollable.

**Comment by maniac103** [comment]
Can you name an example repo that shows this issue?

**Comment by mfonville** [comment]
e.g. https://github.com/opengapps/opengapps/releases

**Comment by maniac103** [comment]
I don't think it's related to the length of the text. I can confirm the issue though, I'll look into it.

**Comment by mfonville** [comment]
Thank you! :)
