### ISSUE TITLE
Handle marked lines in urls

### ISSUE THREAD

**Issue by Sohalt** [slapperwan/gh4a#261]
Github supports marking code sections when sharing a link to a file. This is very useful when talking about a specific part of the code and you want other to immediately find that part. It would be great if octodroid supported this feature and correctly marked the specified lines.

**Comment by maniac103** [comment]
Can you give an example of such an URL?

**Comment by Sohalt** [comment]
Oh, sorry of course. Should've done that in the description right away.
Example: https://github.com/slapperwan/gh4a/blob/39d9a30cfb6229fb1d514600211ef31d1b485e86/src/com/gh4a/Gh4Application.java#L49-51 (the#Ln-m part where n and m are line numbers. Also works for single lines with #Ln where n is the line number. It appears to only work when the commit is specified in the URL, so the line numbers have a consistent meaning)

**Comment by maniac103** [comment]
Ah, OK. I only knew the #Ln syntax so far and thought of it as kind of a jump-to mark.
I'll see whether it's possible to do this with some CSS hackery.

**Comment by maniac103** [comment]
Just for testing:
https://github.com/slapperwan/gh4a/blob/39d9a30cfb6229fb1d514600211ef31d1b485e86/src/com/gh4a/Gh4Application.java#L50
