### ISSUE TITLE
PR commit statuses

### ISSUE THREAD

**Issue by jimmidyson** [slapperwan/gh4a#262]
Would love to see something similar to https://github.com/blog/2040-clearer-mergability-information-for-pull-requests in the PR view. Makes it much easier to evaluate a PR for merge knowing the statuses of your automated checks.

**Comment by maniac103** [comment]
Makes sense.

Some notes to self:
- field 'mergeable_state' denotes 'color' (unstable/unknown/clean/dirty)
- field 'statuses_url' returns a list of statuses -> https://developer.github.com/v3/repos/statuses/; use newest for each context

**Comment by maniac103** [comment]
statuses_url can also be derived by inserting head.sha as :ref into https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref
