### ISSUE TITLE
No way to access issues from a repository

### ISSUE THREAD

**Issue by itsmartin** [slapperwan/gh4a#263]
(Nexus 5)

There doesn't seem to be any way in OctoDroid to get access to the issues for a repo without following a direct external link to repo/issues. It really should be possible to navigate to it from the main screen for a repository, surely?

**Comment by TR4Android** [comment]
@itsmartin Clicking on the count of open issues does the trick for me. I know it's kind of counterintuitive, but once you get it, it works just fine the way it is. Same goes for pull requests etc.

**Comment by itsmartin** [comment]
@TR4Android Thank you! It's obvious when you know it's there, but that has been bugging me for so long!

I'll close this then since it's not really valid.
