### ISSUE TITLE
Theme and font size Changing

### ISSUE THREAD

**Issue by Bloody-Badboy** [slapperwan/gh4a#264]
Theme selection dialog and font selection dialog radio buttons are not working.

**Comment by maniac103** [comment]
Please define 'not working'. What exactly happens when you use them?

**Comment by Bloody-Badboy** [comment]
Dialogue box actions are non-clickable.It's a AppCompat library issue for 4.0.3 devices.Please change the AppCompat Support library version.

**Comment by maniac103** [comment]
Got any reference for that (e.g. what support library version fixes this)?

**Comment by Bloody-Badboy** [comment]
No..I have not tried..

**Comment by Bloody-Badboy** [comment]
No..I have not tried..

**Comment by maniac103** [comment]
So what did tell you it's an appcompat bug and newer versions have this fixed?
