### ISSUE TITLE
Wrong conversation message when an issue is assigned

### ISSUE THREAD

**Issue by raboof** [slapperwan/gh4a#265]
In the 'conversation', I saw "Issue was self-assigned by <assignee>", but the assigner was actually someone else.

**Comment by raboof** [comment]
This is on 3.8.1

**Comment by raboof** [comment]
The code in src/com/gh4a/adapter/IssueEventAdapter.java looks pretty solid:
```
String actorLogin = event.getActor() != null ? event.getActor().getLogin() : null;
            String assigneeLogin = event.getAssignee() != null ? event.getAssignee().getLogin() : null;
            if (assigneeLogin != null && assigneeLogin.equals(actorLogin)) {
                textResId = R.string.issue_event_assigned_self;
            }
```

(this is the only place where issue_event_assigned_self is used)

**Comment by raboof** [comment]
Interestingly, this seems to be an upstream issue: when I query the github API myself, I indeed also get the same user as 'actor' and 'assignee', which is wrong.

**Comment by raboof** [comment]
Correct:
* https://api.github.com/repos/xxx/blaze-account-service-nl/issues/events/403256271
* https://api.github.com/repos/xxx/blaze-account-service-nl/issues/events

Incorrect:
* https://api.github.com/repos/xxx/blaze-account-service-nl/issues/3/events

(company name redacted)

**Comment by maniac103** [comment]
Yeah, I mailed them about it and they don't want to fix it because they fear backwards incompatibility issues. They said they'll look for a solution, but they're looking for a long time now :(

I'll have a look at the URL variants you mentioned.

**Comment by maniac103** [comment]
I just came around to testing your mentioned URL variants (sorry it took so long), but they aren't helpful, as the issues/events one doesn't contain all needed events (as it's a superset of all events for all issues) and the issues/events/<id> one has the same problem as the issues/<id>/events one for the repos I've tried this on.
