### ISSUE TITLE
README's code-block styles are missing

### ISSUE THREAD

**Issue by epitron** [slapperwan/gh4a#267]
Hi there!

First off, I have to say that OctoDroid is amazing! It's so slick! Waaaay better than github's web interface.

Unfortunately, I noticed a small glitch when rendering READMEs where codeblocks don't have styles applied to them.

"About" tab's README viewer:

![About screen](http://i.imgur.com/dj02raV.png)

"Files" tab's README viewer:

![Files screen](http://i.imgur.com/0wIINWA.png)

The second one looks a lot better, imo.

**Comment by maniac103** [comment]
Doing that frame is difficult to do, but I'll give it a light grey background like Github's web UI does.
