### ISSUE TITLE
"No releases were created for this repository yet" - when there are in fact releases!

### ISSUE THREAD

**Issue by flipsa** [slapperwan/gh4a#268]
Not sure what's going on, but for some repos, octodroid does not show any releases, but instead only gives me a "No releases were created for this repository yet" notification. Those repos have releases, as can be seen in a web browser. 

I am using Octodroid 3.8.1 from FDroid.

Example / reproduce: 
1. Open e.g. github.com/baedert/corebird in Octodroid (there are currently 10 releases in that repo)
2. Scroll to bottom and tap "Releases"
3. "No releases were created for this repository yet"

**Comment by maniac103** [comment]
This seems to be a bug of the Github API.

Running
```
curl https://api.github.com/repos/baedert/corebird/releases
```

yields this:
```
[

]
```

while it should yield a list of releases, see https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

**Comment by maniac103** [comment]
Github support answered and said that this repo indeed doesn't have any releases. The Github web page just shows created tags as releases as well.

**Comment by julmot** [comment]
I'd like to request this as a feature. I'd like to see tags if there aren't any releases, like GitHub does.
