### ISSUE TITLE
Feature Request Code Editor

### ISSUE THREAD

**Issue by garretyoder** [slapperwan/gh4a#270]
It'd be nice to be able to edit/create files and push to the repo from the app.

**Comment by Lrs121** [comment]
As much as this would be appreciated, I personally don't see it happening. While the ability to edit files may not take too much work to implement, adding just the basic ability to push and pull a non-ssh repo would take significant effort to implement let alone maintain. 

I'm not saying it won't happen, I'm just saying it's significantly unlikely unless someone wants to take up the effort and contribute to the project. And, that depends on if slapperwan thinks it's within the confines of the goal of what the app is attempting to achieve.

**Comment by JohnVeness** [comment]
I too think it would be very useful to be able to do simple edits to source. Not to turn OctoDroid into a full git app with local (on Android device) repos, but the same type of editing that github.com allows in browser.

Even better if editing a file in someone else's repo would automatically fork the repo and start a pull request, again just like on github.com. I realise forking itself is already requested in #123.

**Comment by Tunous** [comment]
@Lrs121 summarized this well. Adding this would require also adding more git features like cloning repositories, stagging, pushing, etc. There are other applications which are made exactly for this. (Like [MGit](https://github.com/maks/mgit)). I'd recommend using them instead. 

Closing because it's unlikely that this application will receive these features.

**Comment by KaKi87** [comment]
Since GitHub allows editing text-based files from browser, there is an API endpoint to just send the file, without having to handle git client-side. Why not using this feature ?

**Comment by KaKi87** [comment]
Any news on this ?

**Comment by JeffRockatansky** [comment]
Any updates?

**Comment by maniac103** [comment]
Unless somebody steps up and sends a patch for that feature (which probably involves a nontrivial amount of effort), probably not.
