### ISSUE TITLE
Add lock symbol to distinguish private repos

### ISSUE THREAD

**Issue by bkimminich** [slapperwan/gh4a#274]
In OctoDroid I find no visual hint that a repo is public or private. They look all alike in the repo list and details. Adding a small lock icon (similar to how GitHub does) would be helpful to tell them apart.

**Comment by maniac103** [comment]
I have implemented that for a future release: https://github.com/slapperwan/gh4a/commit/daa6551b0ab623cc8e33f05d310662d59b387ead
