### ISSUE TITLE
Add support for animated GIFs in the README files. 

### ISSUE THREAD

**Issue by mikeyxkcd** [slapperwan/gh4a#275]
A lot of Android libraries lately have animated GIFs within  their README.
It would be nice if we could render them natively.  I think an android library like "Glide"  should make this integration fairly possible.

**Comment by maniac103** [comment]
Got an example for such a repo?
(Glide seems to do quite a bit more than we need, but the android-gif-drawable library seems suitable)

**Comment by maniac103** [comment]
I added a toggle for the GIF loading (defaulting to 'load only via WiFi'), as animated GIFs can reach ridiculous sizes. I tested with the atmos/camo repo, they include a GIF with almost 7.5MB.

**Comment by codebymikey** [comment]
Sorry, just saw your message. Thanks for implementing the feature.

In regards to a sample repo, I've picked a random library from android-arsenal.com  - https://github.com/yayaa/Rotatable.

Just a random question: Why not load the markdown files inside a webview, add a javascript interface and then render it using one of the many markdown libraries, that way you also get gif rendering for free as well as native rendering and table support (e.g. the README at https://github.com/vokal/pg-table-markdown).

**Comment by mikeyxkcd** [comment]
Sorry, just saw your message. Thanks for implementing the feature.

In regards to a sample repo, I've picked a random library from android-arsenal.com  - https://github.com/yayaa/Rotatable.

Just a random question: Why not load the markdown files inside a webview, add a javascript interface and then render it using one of the many markdown libraries, that way you also get gif rendering for free as well as native rendering and table support (e.g. the README at https://github.com/vokal/pg-table-markdown).

**Comment by maniac103** [comment]
For the readme that would probably work, but it wouldn't work for issue comments where one also can use markdown: having a list of WebViews as issue comment list would perform horribly. As we need code to render markdown to a TextView anyway because of that, we use that to also render the readme to not have two different techniques. Tables are the only large problem left with that approach.
