### ISSUE TITLE
Ability to view issues from the repository page. 

### ISSUE THREAD

**Issue by mikeyxkcd** [slapperwan/gh4a#276]
There's currently no way to directly view repository specific issues from the repository page.

We could add it within with the option menu or as part of the "other information" card at the bottom of the README screen.

**Comment by mikeyxkcd** [comment]
Same with pull requests

**Comment by maniac103** [comment]
Try touching the 'x issues' button on the top of the page ;)

**Comment by mikeyxkcd** [comment]
Aah, thanks very much!
