### ISSUE TITLE
Open in browser: no browser found?!

### ISSUE THREAD

**Issue by DavidWiesner** [slapperwan/gh4a#278]
Can´t open a file in a browser.

When I have opened a file in OctoDroid e.g.: the README.md in this repository and I click the "Open in browser" icon in the toolbar. A Toast will be shown "The link could not be opened: no browser was found on the device". But there are two browsers installed.
May it´s a specific Bug on Android Marshmallow?! 
--
Android 6.0 Marshmallow
OctoDroid: v3.8.1

**Comment by DavidWiesner** [comment]
Actually when I disable to Open all github links in OctoDroid the "Open in browser" will work. I [found a  workaround](https://movieos.org/blog/2015/working-around-android-m-intent-resolving/) but I haven´t tested that. The main idea is to query the IntentActivities  for an other url than the intent should actually open.

**Comment by alorma** [comment]
maybe this code helps you

```
private List<ResolveInfo> getBrowserList() {

        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("http://sometesturl.com"));


        return getActivity().getPackageManager().queryIntentActivities(intent, 0);

    }


 ```

**Comment by maniac103** [comment]
That code won't help, as one needs to exclude the own application. We have code that does that already, but I think the problem here is that the browser invocation is done via framework code (URLSpan).

**Comment by DavidWiesner** [comment]
@maniac103 the proposed code snippet of @alorma indeed won´t work, as you noticed. 
In my comment https://github.com/slapperwan/gh4a/issues/278#issuecomment-154011153 i [linked](https://movieos.org/blog/2015/working-around-android-m-intent-resolving/) a workaround that does two thinks:
>  First, I ask for a list of apps that can handle a “normal” URL. 
> Then when I build the Intent list I’ll substitute the “real” URL

So it will exclude the own app from the resolved intents.

**Comment by maniac103** [comment]
Got it now. I was missing the fact that you're clicking the 'open in browser' toolbar item and thought you directly linked on a link in the readme preview. We already have code in place similar to your link (https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/utils/IntentUtils.java#L163), adding the 'fake URL' handling should be no real problem.

**Comment by DavidWiesner** [comment]
That would be great! May there is also an other solution for this in Marshmallow but this was the first i find. And the solution fit in your implementation.
