### ISSUE TITLE
Suggestion: Show starred repo list

### ISSUE THREAD

**Issue by 1ace** [slapperwan/gh4a#281]
I'd love to be able to see the list of repos I've `star`red (with the same sort options as the web page), as I use that list as a sort of bookmarks/read-it-later (without having to `watch` everything that happens to the repo in the mean time).

Thanks for the awesome work so far!

**Comment by marksev1** [comment]
+1 I'd like that too. And awesome app slapperwan!

**Comment by maniac103** [comment]
You can already show your starred repos under my repositories -> right side drawer -> starred. So it's only the sort options that you're missing?

**Comment by marksev1** [comment]
Thanks for the tip didn't know that, would be nice if a direct button on the lef side drawer would be made.

**Comment by maniac103** [comment]
Merged navigation-reorg back to master, so issue is fixed with the above commits: You can now select 'my repositories' as start page, and 'my repositories' remembers the last selected filter item.
