### ISSUE TITLE
golang syntax highlighting

### ISSUE THREAD

**Issue by neilscudder** [slapperwan/gh4a#285]
I love this app except my .go files are murder to read

**Comment by maniac103** [comment]
Can you define 'murder to read'?

In general, we're using prettify [1] for the formatting. If formatting isn't right for some language, this should probably be reported upstream. We don't know every language out there ;-) Unfortunately it looks like the go parser [2] hasn't been touched in a long time.

[1] https://github.com/google/code-prettify
[2] https://github.com/google/code-prettify/blob/master/src/lang-go.js
