### ISSUE TITLE
Show icon for organizations in profiles

### ISSUE THREAD

**Issue by Hauwertlhaufn** [slapperwan/gh4a#287]
At the moment the app just shows the name of the organizations in a user-profile.
In my humble opinion it would be great to see the icons of the organizations too.

**Comment by maniac103** [comment]
The app already does show icons for organizations. Can you post a screenshot, maybe I'm misunderstanding what exact view you're talking about.

**Comment by Hauwertlhaufn** [comment]
I mean in the profile of a user:
![screenshot](https://cloud.githubusercontent.com/assets/9079777/12881737/70539568-ce4c-11e5-9eb3-4f6e03da44c2.png)
