### ISSUE TITLE
drone.io automated builds are failing

### ISSUE THREAD

**Issue by ARoiD** [slapperwan/gh4a#288]
No builds on drone.io https://drone.io/github.com/slapperwan/gh4a/files

**Comment by ARoiD** [comment]
@slapperwan @maniac103

**Comment by maniac103** [comment]
@slapperwan Could you add me as a member of that build project?

**Comment by ARoiD** [comment]
@maniac103 You wouldn't by any chance have a new build uploaded somewhere?

**Comment by maniac103** [comment]
@ARoiD https://www.dropbox.com/s/fgnxjxzis5053qm/gh4a-debug-20160219.apk?dl=0

**Comment by ARoiD** [comment]
@maniac103 Thanks

**Comment by slapperwan** [comment]
@maniac103 added you.  Thanks

**Comment by maniac103** [comment]
Fixed.

**Comment by ARoiD** [comment]
@maniac103 the builds are failing again?

**Comment by maniac103** [comment]
@ARoiD Fixed, license agreement failed.
