### ISSUE TITLE
android.permission.WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by ARoiD** [slapperwan/gh4a#289]
02-22 16:45:24.873 14460 14460 E AndroidRuntime: FATAL EXCEPTION: main
02-22 16:45:24.873 14460 14460 E AndroidRuntime: Process: com.gh4a, PID: 14460
02-22 16:45:24.873 14460 14460 E AndroidRuntime: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/AnyKernel2-master.zip: Neither user 10096 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.content.ContentResolver.insert(ContentResolver.java:1231)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.app.DownloadManager.enqueue(DownloadManager.java:946)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at com.gh4a.utils.UiUtils.enqueueDownload(UiUtils.java:263)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at com.gh4a.utils.UiUtils.enqueueDownload(UiUtils.java:319)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at com.gh4a.activities.RepositoryActivity.onOptionsItemSelected(RepositoryActivity.java:353)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:2914)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:68)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:172)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.support.v7.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-22 16:45:24.873 14460 14460 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ARoiD** [comment]
@maniac103 This fix is not in the drone.io builds?

**Comment by maniac103** [comment]
@ARoiD It is, or at least should be.

**Comment by maniac103** [comment]
I wonder whether we need runtime permissions here.

**Comment by ARoiD** [comment]
On the newest build it still crashes when I try to download any repo

**Comment by maniac103** [comment]
Yeah, runtime permissions probably needed there.

**Comment by iamAbode** [comment]
Make sure the following permissions is in your Manifest.xml file: 
    <uses-permission android:name="android.permission.INTERNET" />   
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

And then include this code in your download function

if(ActivityCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED || ActivityCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED){
            // this will request for permission from the user if not yet granted
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE}, 1);
            
        }else{
            // Download code here
        }

**Comment by maniac103** [comment]
> Make sure the following permissions is in your Manifest.xml file:

,,, thanks, I guess? But you're 3 years late; see the commit also linked above: https://github.com/slapperwan/gh4a/commit/a448981ea8d74f74f4de5761820b77ab6f1e74a7
