### ISSUE TITLE
Webpage link not working in user profile

### ISSUE THREAD

**Issue by AntonioND** [slapperwan/gh4a#290]
When the webpage has symbols like '_' the link only covers the address from the following character until the end.

**Comment by maniac103** [comment]
This is an Android framework bug. I've opened a bug report: https://code.google.com/p/android/issues/detail?id=202123

**Comment by AntonioND** [comment]
Oh, I guess I'll never see this fixed then... :(

**Comment by maniac103** [comment]
Yeah, but as the regex used for the linkification is hardly understandable and > 700 characters I also don't want to fix this in the app. I'm thinking of fixing this in CM though.

**Comment by Tunous** [comment]
Closing because that's Android bug.
