### ISSUE TITLE
Pulling Down to Refresh in any Repository

### ISSUE THREAD

**Issue by ARoiD** [slapperwan/gh4a#293]
03-14 16:11:20.045 14372 14372 E AndroidRuntime: FATAL EXCEPTION: main
03-14 16:11:20.045 14372 14372 E AndroidRuntime: Process: com.gh4a, PID: 14372
03-14 16:11:20.045 14372 14372 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'org.eclipse.egit.github.core.User org.eclipse.egit.github.core.Repository.getOwner()' on a null object reference
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at com.gh4a.fragment.RepositoryFragment.fillData(RepositoryFragment.java:200)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at com.gh4a.fragment.RepositoryFragment.onActivityCreated(RepositoryFragment.java:167)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1019)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2989)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:279)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at com.gh4a.BasePagerActivity.invalidateFragments(BasePagerActivity.java:49)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at com.gh4a.BasePagerActivity.invalidateTabs(BasePagerActivity.java:54)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at com.gh4a.activities.RepositoryActivity.onRefresh(RepositoryActivity.java:248)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:185)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.widget.CircleImageView.onAnimationEnd(CircleImageView.java:107)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:6104)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:16128)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1127)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
03-14 16:11:20.045 14372 14372 E AndroidRuntime: 	at com.android.internal.policy.Pho

@maniac103

**Comment by ARoiD** [comment]
@maniac103 Still crashes but pulling down to refresh in files tab only

**Comment by ARoiD** [comment]
03-15 08:21:29.855 22831 22831 E AndroidRuntime: FATAL EXCEPTION: main
03-15 08:21:29.855 22831 22831 E AndroidRuntime: Process: com.gh4a, PID: 22831
03-15 08:21:29.855 22831 22831 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'org.eclipse.egit.github.core.User org.eclipse.egit.github.core.Repository.getOwner()' on a null object reference
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at com.gh4a.fragment.RepositoryFragment.fillData(RepositoryFragment.java:200)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at com.gh4a.fragment.RepositoryFragment.onActivityCreated(RepositoryFragment.java:167)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.view.ViewPager.setOffscreenPageLimit(ViewPager.java:789)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at com.gh4a.BasePagerActivity.updateTabVisibility(BasePagerActivity.java:118)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at com.gh4a.BasePagerActivity.invalidateFragments(BasePagerActivity.java:50)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at com.gh4a.BasePagerActivity.invalidateTabs(BasePagerActivity.java:54)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at com.gh4a.activities.RepositoryActivity.onRefresh(RepositoryActivity.java:245)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:185)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.widget.CircleImageView.onAnimationEnd(CircleImageView.java:107)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:6104)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:16128)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1127)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
03-15 08:21:29.855 22831 22831 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(Thread

**Comment by maniac103** [comment]
@ARoiD That's the crash I just fixed. I can't repro it anymore with latest code.

**Comment by ARoiD** [comment]
@maniac103 Refreshing under the About or Commits tabs don't crash only under Files on the newest build

**Comment by maniac103** [comment]
Stupid me tried it on the commits tab. I'll look into it.
