### ISSUE TITLE
Plans to update the Play Store app?

### ISSUE THREAD

**Issue by mikeyxkcd** [slapperwan/gh4a#294]
I'd like to know if there's any plans to update the playstore application in the new future.

**Comment by maniac103** [comment]
From my POV definitively yes, as soon as the bugs are ironed out (the more people testing master, the better - hint hint ;) )
I'm just not sure about @slapperwan's time budget ... @slapperwan, comments on this?

**Comment by slapperwan** [comment]
Hi @maniac103, thanks for the effort and time you put in on Octodroid.  I saw you merged the navigation-reorg to master branch.  So I assume it almost ready for release?  Any major features/bugs you plan to put it?  I can further test the app from master.

**Comment by maniac103** [comment]
@slapperwan Yes, it should be mostly ready. Only immediate issue I'm aware of is #293, but I'm sure there still are a few subtle issues here and there.

**Comment by jahirfiquitiva** [comment]
I really expect to see an update soon, specially with #283 and #295 fixed/implemented :)

**Comment by mikeyxkcd** [comment]
You rock @maniac103!, I really appreciate all of the effort you've put into this app so far as well as implementing most of my feature requests.

I'll try pulling and testing master and give any further feedback if I run into any bugs.

Thanks again dude.

**Comment by mfonville** [comment]
Bump!

With #293, #283 and #295 fixed will there be a release soon?

**Comment by slapperwan** [comment]
Just uploaded to play store, should be available from now on.
