### ISSUE TITLE
2 functions improvements and fixes

### ISSUE THREAD

**Issue by jahirfiquitiva** [slapperwan/gh4a#295]
Hi

I would like to request you to enable Swipe To Refresh in all the sections, because it appears in some, but in others it doesn't, so is not so intuitive as an user. When I have some sections where I can do it, I expect all to have it. (Since everything is web related and could have an option to update the content).

Also, when opening links, it sometimes says that there's no browser installed in my device, but it has the stock browser as well as Chrome so ....

Thanks. Good luck.

**Comment by maniac103** [comment]
Item 2 is already fixed (I assume you have Marshmallow and set Octodroid as default for Github links?)
For item 1, what views are currently missing pull to refresh?

**Comment by ARoiD** [comment]
@maniac103 Can't refresh in main issues view under open or closed?

**Comment by maniac103** [comment]
@ARoiD Confirmed, will check that.
