### ISSUE TITLE
Cannot create new milestone

### ISSUE THREAD

**Issue by slapperwan** [slapperwan/gh4a#298]
As per title, the error "Cannot create milestone".

**Comment by maniac103** [comment]
03-18 20:23:03.864 W/System.err(20087): org.eclipse.egit.github.core.client.RequestException: Invalid request.
03-18 20:23:03.864 W/System.err(20087):  is not a member of ["open", "closed"]. (422)

That's a little weird, will look into it.

**Comment by maniac103** [comment]
Should probably set the milestone state to 'open' when creating the new milestone. Should be an easy fix.
