### ISSUE TITLE
Scrolling releases

### ISSUE THREAD

**Issue by ARoiD** [slapperwan/gh4a#299]
Having a hard time loading and scrolling releases

https://github.com/opengapps/arm/releases

**Comment by maniac103** [comment]
Please check if the issue is fixed with the above commit and reopen if it isn't.

**Comment by ARoiD** [comment]
Opens but entering one of the releases scrolling is stuttering

@maniac103

**Comment by maniac103** [comment]
Please define 'stuttering'. You mean you can't fling the download list?

**Comment by ARoiD** [comment]
Yes exactly when I try to fling inside one of the release listing it doesn't scroll smoothly like it does when you enter the main releases

**Comment by maniac103** [comment]
Should be fixed with the above commit.

**Comment by ARoiD** [comment]
Sure did thanks
