### ISSUE TITLE
Feature: Sort starred/watched repos

### ISSUE THREAD

**Issue by jmue** [slapperwan/gh4a#300]
Currently it is not possible to sort starred/watched repos by e.g. "most recently pushed". It would be nice if that would be possible.

Thanks for yout effort on this project!

**Comment by maniac103** [comment]
This already is possible in master ;) Select 'my repositories' and select 'starred' as well as 'most recently pushed' in the right drawer.

**Comment by maniac103** [comment]
Oops, never mind. I was wrong there.
I'll look into it, there might be an API limitation.

**Comment by maniac103** [comment]
For watched, it's an API limitation. For starred, one can sort by repo creation or by last push date. I'll add the sort option for starring.
