### ISSUE TITLE
Reactions in comments and issues

### ISSUE THREAD

**Issue by FabianWilms** [slapperwan/gh4a#304]
It would be great if the new reactions in the web version of GitHub would be also visible in the app for comments, issues and pull requests. Also it would be awesome to be able to set reactions, too.

**Comment by maniac103** [comment]
I don't see this listed in the API though.

https://developer.github.com/v3/issues/#get-a-single-issue

**Comment by maniac103** [comment]
Looks like there's going to be API support; there's a preview API available now: https://developer.github.com/v3/issues/#reactions-summary

**Comment by Bluscream** [comment]
I'd second this :)

**Comment by gregsdennis** [comment]
I'd add a "thumbs up" to this, but... you know...

**Comment by Bluscream** [comment]
Xd

**Comment by maniac103** [comment]
I've pushed some initial code that shows the existing reactions here: https://github.com/slapperwan/gh4a/tree/reactions
I'm currently wondering what a good UX for the reaction interaction is. Github's web UX feels a bit weird (e.g. add laugh reaction -> add laugh reaction again -> result: no reaction).
My thought would be clicking the reaction bar would open a dialog with
- a list of reactions and the respective users (is a timestamp needed/useful there?) and
- a bar with toggleable reaction icons for one's own reactions
Question is: how to make that bar accessible when no reactions were given so far? Move into some overflow menu? We probably don't want to waste screen space for the reaction bar just to make the button accessible in that case. Maybe it would be a good idea to completely separate the 'details' dialog from the 'react' dialog?

Thoughts, anyone (and @Tunous in particular ;-) )?

**Comment by gregsdennis** [comment]
Currently there's an edit icon to the right of a comment.  Since it makes sense that you'd only react to another's comment, couldn't you have a floating button in the same place?  A menu would then appear that toggles reactions (and it could be very clear that they toggle).

**Comment by maniac103** [comment]
Current code has an overflow menu (3 dots) instead of the edit icon with edit, share, delete options. Could add an 'add reaction' item there. Slight caveat is that we need to fetch reaction details (network activity) before allowing to react so we know whether the user already did react or not.

**Comment by gregsdennis** [comment]
@maniac103 I uploaded a screenshot (had to do it from my computer since I couldn't figure it out on the phone).  I don't see the three-dot menu.

**Comment by Tunous** [comment]
Adding "add reaction" menu item is a best best option. It could open dialog like you described which allows for toggling reactions. If fetching deatils is a problem we could display progress in that dialog before the details appear.

**Comment by maniac103** [comment]
@gregsdennis 'Current code' is the key here ;) 
![](https://drive.google.com/file/d/0B0hmLAh3l4oHdHdkQzh5Vnp5WTA/view?usp=drivesdk)

**Comment by gregsdennis** [comment]
I don't have that 😦  (I get it).

**Comment by Tunous** [comment]
Should also add this to line comments https://github.com/Tunous/TestingRepo/commit/f604c43bcc9f37a35a9b8a18203f489681fa7c65#commitcomment-21517462

**Comment by maniac103** [comment]
@Tunous That will be ... interesting though.

**Comment by Tunous** [comment]
Btw for reaction icons we could use emoji codes 0x1F601, 0x1F615, 0x1f44d, 0x1f44e, 0x1f389, 0x2764 and just use that directly in text instead of drawable. But that might not work on older API's... (<= KitKat?)

**Comment by Tunous** [comment]
> a list of reactions and the respective users (is a timestamp needed/useful there?)

I don't think it's useful. Just should sort the users based on it.

**Comment by gregsdennis** [comment]
> Slight caveat is that we need to fetch reaction deals (network activity) before allowing to react so we know whether the user already did react or not.

@maniac103, couldn't that info just be part of the page load?  You shouldn't need to make the call each time the menu is opened.

**Comment by maniac103** [comment]
> couldn't that info just be part of the page load? You shouldn't need to make the call each time the menu is opened.

I'll have to think about it ... it might be worth a thought (most comments won't have reactions and thus don't need the additional load), but I'm not sure I want to block the page load for it, and if we don't block, we're back to the same problem.

**Comment by gregsdennis** [comment]
I'm not as familiar with Android as WPF, but can you load the reactions on a separate thread then she then once loaded?

**Comment by maniac103** [comment]
Sure, that's what I'm going to do. Still I'll need to show an intermediate progress bar though ... but I guess that's not too much of an issue.

**Comment by maniac103** [comment]
Pushed some initial UX for reacting to the branch. Thoughts/comments are welcome, I'm not sure whether it's the ideal solution yet.

**Comment by Tunous** [comment]
Gif for these who don't want to compile:
![peek 2017-04-17 15-37](https://cloud.githubusercontent.com/assets/5156340/25090479/beac4114-2383-11e7-8aba-aa324ede9f93.gif)

My thoughts:

The popups with information about users which posted reactions could be done differently. Instead of it being used for the whole bar as a whole, display only the information for one reaction. Pressing on thumbs up would only show these people who added that reaction. Also, we could include to that pop-up an option to toggle your own reaction.
Other than that I think it works well. Just needs the obvious UI polish like press indicators, better paddings. And I'm not really sure about that red color for reactions...

**Comment by maniac103** [comment]
That red color is a placeholder, I just ran out of time for today.

**Comment by Tunous** [comment]
> One thing I have no good idea for yet is where to place the 'add reaction' thing in the issue header.

Toolbar overflow menu should be ok.

**Comment by gregsdennis** [comment]
I like it.  (And a 👍 for @Tunous and the gif)

**Comment by FabianWilms** [comment]
Maybe another approach: Currently there are no actions assigned to tapping on comments. Maybe a single tap can be a `response`, so that an @-Mention gets added to the text field. When the user long presses a comment they can add a reaction.

For adding and toggling reactions it would be nice if the comment expands and reveals a bar beneath it with the togglable reactions instead of opening a popup.

**Comment by Tunous** [comment]
Tapping on comments opens links and long pressing starts text selection. It would be annoying to accidently mention when trying to press on a link.

**Comment by gregsdennis** [comment]
While I agree with @Tunous, I do like @FabianWilms' suggestion about the bar.  Perhaps adding a tappable thicker horizontal line between the comments could function as an expander which would reveal the reaction bar would work.  Not sure how that fits into Material Design, but it *does* eliminate the extra pop-up.

**Comment by maniac103** [comment]
I don't really want to inline the 'add reaction' UI into the actual comment though, as it's not triggered from the comment itself, but another popup (menu). Converting it into a bottom sheet looks somewhat nicer though:
![screenshot_1492510033](https://cloud.githubusercontent.com/assets/781373/25125562/911ff5ae-242f-11e7-9986-bf289498e574.png)

**Comment by FabianWilms** [comment]
I think that the expanding comment better indicates to which comment you are reacting to. The bottom bar looks better than the popup but it misses this indication.

**Comment by maniac103** [comment]
> I think that the expanding comment better indicates to which comment you are reacting to. The bottom  bar looks better than the popup but it misses this indication.
I don't disagree, but it's additional complication that I want to avoid at this point. The new comment editor  (https://github.com/slapperwan/gh4a/pull/536) has similar implications, so maybe we can find a common solution there (e.g. highlighting the respective comment somehow).

In other questions, I'm thinking of coloring the button background matching the issue state (red/green) ... thoughts on whether this or the grey is preferable?
![screenshot_20170419-101928](https://cloud.githubusercontent.com/assets/781373/25170191/f1654418-24e9-11e7-9b76-fd2003a0dd38.png)

**Comment by Tunous** [comment]
I like that colored indicator but perhaps change the color of the icon itself too. Current color seems to be too blending. What if they were white?

**Comment by maniac103** [comment]
White would be better; I just wanted to avoid additional icon variants and the original icon (used in the light theme) has transparency, which is kept intact through the color filter. It's probably fixable by making the icons white or black and applying a color filter in the reaction bar views.

**Comment by Tunous** [comment]
Testing it now I don't really like the "saving" behavior. It's one additional unnecessary step. I would prefer to be able to click on a reaction and have the change automatically changed. It rarely happens that someone wants to add more than single reaction.

Also, I got a different idea for the reactions, perhaps it'll work better. I'll do a quick test and show it to you.

**Comment by Tunous** [comment]
![peek 2017-04-19 19-47](https://cloud.githubusercontent.com/assets/5156340/25193943/1471d634-2539-11e7-839d-b2b21727d1a7.gif)

Something like this.

**Comment by maniac103** [comment]
That's a great idea, if there's a solution for the asynchronous loading. Not sure whether one can place a progress bar in a sub menu?

**Comment by Tunous** [comment]
One possibility would be to add "Loading..." item and change visibility once data is loaded.

Anyway, the quick code is here: https://github.com/Tunous/gh4a/tree/reactions-popup. I don't have time now to do anything more but I'm sure you are able to get that working :)

**Comment by slapperwan** [comment]
Should it be only 1 level of menu item? I mean no "Add reaction" menu, just display reaction icons in different group menu and maybe in the form of 3 cols and 2 rows?

**Comment by maniac103** [comment]
@slapperwan It doesn't look like it's possible to have custom menu item views in popup menus.

**Comment by maniac103** [comment]
Updated the branch with @Tunous' popup menu idea. Let me know what you think of it.

**Comment by Tunous** [comment]
I think that's nice.

Some issues:
- Adding new reaction only updates the reactions bar once, removing the reaction or adding new doesn't change anything
- The reactions status from the add reaction popup menu in reactions bar doesn't always update
- Reaction icons in reaction bar don't have click highlight
- Users in reaction list don't have click highlihgt

**Comment by maniac103** [comment]
Those 4 issues should be fixed now. @Tunous Can you please verify?

**Comment by Tunous** [comment]
Controls in reaction bar work correctly. One issue is left though: Adding new reactions from the comment's 3 dots menu (not in reaction bar) doesn't update the reaction bar after the initial action.

**Comment by maniac103** [comment]
I've implemented commit comment reactions now. Of the 6 proposed unicode characters, 5 work on API 16, only the 'confused' one doesn't. Any alternative code point suggestions for that one?

Also, I'd appreciate if somebody using reactions more frequently than I do could throughly test drive this branch.

**Comment by Tunous** [comment]
What about 0x1F615?

**Comment by maniac103** [comment]
https://github.com/slapperwan/gh4a/commit/3041dc5070cacb90ce29fba77b0d91263444cd65#diff-8dcc72ae45f69114fe3bce0f9e59a7baR302 ;-)

That's the one you suggested earlier and the one that's not working.

**Comment by Tunous** [comment]
Oh oops, can't think of other emoji that could work...

**Comment by maniac103** [comment]
I guess I'll experiment with using SVG images instead of the unicode characters.

**Comment by maniac103** [comment]
Using SVGs seems to work fine. As CSS filters don't work pre-API 19 I have to generate inline and keep the path data in the Java sources, but that shouldn't be too much of a problem.

**Comment by Tunous** [comment]
I played with it a bit and I think it would be nice if we added a quick toggle option when clicking on individual reaction. It could be displayed above the list of people saying something like"Add/Remove reaction".

I'm suggesting this because I noticed that I keep clicking on already present reactions just to add my vote and instead I'm only seeing a list of people, so I have to use the 3 dots menu which is an additional 1-2 clicks.

Just a small improvement.

**Comment by maniac103** [comment]
I played with this, but am not sure how I feel about it ... it somewhat feels a bit confusing with the 3 dot menu right next to it. If you want to try it: https://pastebin.com/ueX4rEMu

**Comment by Tunous** [comment]
In my opinion, it works nicely and is similar how it's done in the browser. Another alternative that I can think of is to make click action toggle own reaction and long click show information about who reacted. Maybe that would be better. Toggling reaction is more common than checking who reacted.

**Comment by maniac103** [comment]
Nope, 👎 for long press from my side. Long press actions aren't discoverable at all, especially when the short press action does already some obvious action. Besides that, why would you toggle your reactions that often?

**Comment by Tunous** [comment]
Well not toggle but quickly add my own reaction to existing ones.
Anyway, I don't have a strong preference here. I'm ok with just the 3 dot menu.

**Comment by sharkykh** [comment]
Not sure if it was discussed already, but what about having the reactions (and their amounts) under the comment itself, just like Github?

**Comment by maniac103** [comment]
Err, that's like it is already?

**Comment by sharkykh** [comment]
Ha, well then, it will be when you release. Thanks!

**Comment by Tunous** [comment]
Now that the reactions branch is merged we can close this right?

**Comment by maniac103** [comment]
Yup.
