### ISSUE TITLE
other users repos are not sortable

### ISSUE THREAD

**Issue by jmue** [slapperwan/gh4a#305]
Although the sorting options are selectable from the options menu, they have no effect on other users repositories with latest master build.

**Comment by maniac103** [comment]
What exactly do you mean by 'other users repositories'?

**Comment by jmue** [comment]
By 'other users repositories' I mean the repository view of a github user/organization account other than my own. Sorry for confusion. How to get there:

- search for some repo with via the navigation drawer.
- click on the 'navigate-up' item in the top-left corner or click on the repository owner. -> account overview is shown
- click on 'repos' item

**Comment by maniac103** [comment]
Ah, I see, confirmed. I'll look into it.
