### ISSUE TITLE
search icon

### ISSUE THREAD

**Issue by Sohalt** [slapperwan/gh4a#307]
I'd like to propose to move the repo search from the menu on the left to a looking glass icon in the top bar, as this seems to be the ui guideline standard for search. Additionally search is such a common operation that having to open the menu first each time is a little cumbersome.

**Comment by maniac103** [comment]
I don't want to this for a reason: the search isn't related to the contents of the main view, e.g. the event list. Users might (rightfully) expect the search would return event list results if it was in the top bar, which isn't the case.
The search icon already is in the top bar in cases where it makes sense, e.g. in the issue list.

**Comment by Sohalt** [comment]
Understandable. Maybe adding the explore repos as a new tab and having search there search repos and search in the event stream search events might be an option?

**Comment by maniac103** [comment]
One can't search events (the API doesn't allow it), and the next version won't have any tabs in the main view ;)

**Comment by Sohalt** [comment]
OK. Then I'll best wait for the next version and see if I can come up with a better idea for search. You can close this. (I would do it myself but the app doesn't allow me to… gotta make an issue for that :D)

**Comment by maniac103** [comment]
It should allow you to close though: https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/activities/IssueActivity.java#L329

**Comment by Sohalt** [comment]
Hmmm, could it be that I need a phone with a dedicated menu button for this? I only have the back arrow at the top left and the share icon at the top right. And a text entry at the bottom for comments.

**Comment by maniac103** [comment]
There should be a button labelled 'close' left to the share button.

**Comment by Sohalt** [comment]
It's not there for me. (Using v3.8.1 from fdroid)

**Comment by maniac103** [comment]
Might it be possible you logged in with Octodroid with 'sohalt' as user name (or any other capitalization difference)?

**Comment by Sohalt** [comment]
Ehm, right. All lower caps.

**Comment by Sohalt** [comment]
OK, logging in with the right capitalization shows the close button. Should maybe be documented somewhere or fixed to work with any case.

**Comment by maniac103** [comment]
The capitalization thing is probably worth its own bug report though. If Githib doesn't care about the capitalization on login, we shouldn't care either.

**Comment by Sohalt** [comment]
I opened a separate issue.
