### ISSUE TITLE
Displaying images doesn't work

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [slapperwan/gh4a#309]
Displaying big screenshot images and badges like the Travis CI build passing image didn't load in app.

**Comment by maniac103** [comment]
Any particular example for this? And what version do you use? If 3.8.1, the loading of SVGs (which are common as badges) has been added in the meantime.

**Comment by SuriyaaKudoIsc** [comment]
I use version 3.8.1.

**Comment by maniac103** [comment]
OK, consider the badges fixed then. Got a specific example for the big screenshots?

**Comment by SuriyaaKudoIsc** [comment]
Like the badge and screenshot images in https://github.com/bunto/bunto-mention.

**Comment by maniac103** [comment]
Works fine for me on a master build, so considering fixed.
