### ISSUE TITLE
swipetorefresh in landscape mode

### ISSUE THREAD

**Issue by jmue** [slapperwan/gh4a#313]
Scrolling up on files tab while in landscape Mode is not possible, swipetorefresh is shown. Steps to reproduce:
- switch to landscape mode
- view content of some repo on files tab
- scroll down
- try scrolling up, swipetorefresh is shown immediately

**Comment by jmue** [comment]
Thank you!

**Comment by maniac103** [comment]
You're welcome, thanks for the testing :)
