### ISSUE TITLE
Open binary files in browser

### ISSUE THREAD

**Issue by maniac103** [slapperwan/gh4a#322]
From Play Store reviews: Binary files, such as pdf or docx files, are currently opened in the app, while they either should be opened in the browser (for download) or be forwarded to an external application.

**Comment by ildar** [comment]
https://github.com/siacs/Conversations/blob/HEAD/CHANGELOG.md
It isn't binary but redirected to a browser. Can you check please?

**Comment by maniac103** [comment]
Problem there for sure is the HEAD branch reference. I came across this only in local git checkouts so far. Is this equivalent to master? Or to the repo's default branch?

**Comment by Tunous** [comment]
It's equivalent to repo's default branch.

**Comment by Tunous** [comment]
I've got this.

**Comment by maniac103** [comment]
> I've got this: 9cc2371

Makes sense. May be worth dropping in a comment there, and adapting the existing ones.
