### ISSUE TITLE
Can't login with email as a username

### ISSUE THREAD

**Issue by slapperwan** [slapperwan/gh4a#325]
This taken from Google Play review, and I think the user set the username as an email address.  Currently the app does not allow to login with email.

**Comment by maniac103** [comment]
Is this _supposed_ to work?

**Comment by slapperwan** [comment]
As I remember the login with email will hit the error return from Gihub API, thats why the app prevent it.  In this scenario, I'm not sure if the username is really an email and will pass the login API.

**Comment by slapperwan** [comment]
Looks like the reviewer be able to login.
