### ISSUE TITLE
Return from file view

### ISSUE THREAD

**Issue by ksejdak** [slapperwan/gh4a#330]
Currently when back button is pressed, app returns to repository root.

It should go back to place, where is file that was just closed.

**Comment by maniac103** [comment]
The back Burton goes back in chronological order, not in hierarchical order. That being said, can you describe hire exactly you got to the file viewer?

**Comment by ksejdak** [comment]
Ok. For some reason I thought that "arrow button" should work like back button. Thus I was testing only arrow button.

So when I click hardware back button, it works as expected. But arrow button in file viewer still returns to repository root. Is it by design? If yes, then I'm ok with using only back button and I will close this.

**Comment by maniac103** [comment]
Yes, it is. Hardware back button should go back chronologically, the action bar back button should go back hierarchically. This is by design, as this behaviour is encouraged in the Android design guidelines: https://developer.android.com/design/patterns/navigation.html
