### ISSUE TITLE
Swipe to reveal navigation panel from all views

### ISSUE THREAD

**Issue by MarkBennett** [slapperwan/gh4a#333]
I often have to navigate back multiple levels to jump to a bookmark. It would be nice is the swipe gesture which reveals the navigation panel on the left hand side from the home screen also worked from other views.

**Comment by Tunous** [comment]
This would probably require to restructure core of the application which I think is unlikely to happen.

We could make long pressing on back arrow navigate to main screen and clear whole back-stack. But who would ever find this shortcut?

**Comment by MarkBennett** [comment]
Alright. Thanks for the reply. I'll close this issue.

**Comment by rubo77** [comment]
please reopen, I find it also quite unituitive to hit the back hutton several times to go back to the entry page

**Comment by landry314** [comment]
> please reopen, I find it also quite unituitive to hit the back hutton several times to go back to the entry page

EXACTLY. The major left side navigation drawer should ALWAYS be there. The fact that you have to hit back like 3 times to get to it is strange programming. It needs to be persistent.

**Comment by landry314** [comment]
> Alright. Thanks for the reply. I'll close this issue.

why did you close this? it should stay open until the dev decides on wont fix.
