### ISSUE TITLE
[Feature request] Offline repository browsing

### ISSUE THREAD

**Issue by Namnodorel** [slapperwan/gh4a#334]
As you already can download repos as zip file, I think it wouldn'tbe too hard to enable offline repo browsing using these files.

**Comment by maniac103** [comment]
The downloaded ZIP file only contains the latest code of the respective branch. It doesn't contain any information about past commits, issues etc. While it might be possible to fetch that raw git data and processing it using a local git client, that would be a totally different app. I therefore don't see us doing this anytime soon.
