### ISSUE TITLE
Adding Images

### ISSUE THREAD

**Issue by ibrokemypie** [slapperwan/gh4a#336]
adding images to issues etc is a major part of github,  one that so far seems impossible in octodroid,  an otherwise very nice app

**Comment by hwding** [comment]
the same for me

**Comment by slapperwan** [comment]
Duplicate #297

**Comment by PwnArt1st** [comment]
perhaps add a button to input the markdown for a image, requiring the user provides a url? perhaps some other markdown functions such as urls and basic font stuff would be good too

**Comment by Tunous** [comment]
> perhaps add a button to input the markdown for a image, requiring the user provides a url? perhaps some other markdown functions such as urls and basic font stuff would be good too

Added in #536.
