### ISSUE TITLE
Squash on PR merge

### ISSUE THREAD

**Issue by maniac103** [slapperwan/gh4a#344]
From Play Store comments: (optionally) allow squashing when merging PRs
Currently in preview: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

**Comment by mfonville** [comment]
That would indeed be great a feature. They also allow rebasing nowadays.
I guess this forces a UI update though, or maybe a dialog to choose the method after pressing 'merge'?

**Comment by maniac103** [comment]
My initial idea would be exposing the merge method in a Spinner in the merge (comment) dialog.

**Comment by mfonville** [comment]
yes, that would be most logical (that is what I meant with the original UI-update, I was just not clear :) )
