### ISSUE TITLE
Improve line comments UI on PR Conversation view

### ISSUE THREAD

**Issue by nisavid** [slapperwan/gh4a#345]
The official GitHub web interface provides a convenient way to view and interact with line comments in a pull request.  On the PR _Conversation_ view (a PR's home page), one can see all line comments that have been added, together with the corresponding line's diff content and its context (the preceding lines' content).  This line comment view includes a hyperlink, _View full changes_, that provides a quick way to jump to the corresponding changes in the corresponding file.

Please add similar functionality and UX to OctoDroid.

Currently (as of version 4.0.3), OctoDroid does show line comments in _Conversation_ view, but it's missing the other aspects.  There is (as far as I can tell) no way to reply to a line comment in that view.  The view doesn't show the line's diff content and surrounding context, so understanding a comment usually requires viewing the full changes.  However, there is also (as far as I can tell) no link to jump to the line comment in the context of the full changes, so doing that involves memorizing the file path and comment text, switching to the file view, choosing the file, and finding the line comment.  In a non-trivial PR, this is very unwieldy.

----

### PR _Conversation_ view on github.com
The line content is shown, together with context.  There is a button to _Add a line note_ and a link to _View full changes_.

![PR Conversation view on github.com](https://drive.google.com/uc?export=view&id=0B3BHVfI4n1hYR1RMZGlINklXaVE)

### PR _Conversation_ view in OctoDroid v4.0.3
The line content and context are not shown.  There is no way to jump to the comment's location in the full changes.  There is an _Edit_ (pencil) button, but there is no way to add a new reply.

![PR Conversation view in OctoDroid v4.0.3](https://drive.google.com/uc?export=view&id=1-JrQPRoEBpCM6MTzPVBo5bTkhN020SCUTQ)

### PR file view in OctoDroid v4.0.3
Once you find the line comment in the corresponding file, it is possible to see the comment and reply to it.  However, getting there is cumbersome.

![PR file view in OctoDroid v4.0.3](https://drive.google.com/uc?export=view&id=143P6cQWwDJu0dAvE_yVorilfdNBcUJn2nQ)

**Comment by maniac103** [comment]
I don't see a straightforward way of replicating the behaviour of Github's web UI, but adding a button to quickly jump to the respective diff shouldn't be too hard. Would that be OK?

**Comment by nisavid** [comment]
@maniac103, that would certainly be an improvement!  Thanks.

I imagine that showing the associated source content and context in the _Conversation_ view might be something that would take multiple API calls and custom code to stitch it all together—certainly a larger effort than adding a _View full changes_ link.  Likewise for controls to reply to line comments in the _Conversation_ view.

You may find it helpful to know that [Gitskarios for GitHub](https://github.com/gitskarios/Gitskarios) does show the source content and context in its _Conversation_ view, although it does not currently provide a way to reply to line comments (though the author communicated to me that this is planned for a future release).

**Comment by maniac103** [comment]
It's less of an issue with the amount of API calls involved, but more of a UI issue: unlike on desktop where Github's web UI is typically used, the amount of available screen width is very limited on phones, which makes typical code hard to fit. List content is very hard to make vertically scrollable in Android, so there's 2 ways to deal with that: live with it (which is what Gitskarios is doing with the mentioned diff view) or use a WebView (which is what we're doing - but one can't add one WebView per comment line for performance reasons). The reason why we pursued the WebView only approach is that reviewing a larger diff with mixed additions and deletions and long lines is very cumbersome, so IMHO it's not providing good UX either.

I'll see how much effort adding the quick link to the respective diff is.

**Comment by nisavid** [comment]
Such design choices are entirely up to you, of course.  I'll just point out that in landscape orientation on a Nexus 6P, Gitskarios nicely shows lines up to 92 (maybe a few more) characters long, which happens to be the about the same number that can fit in a side-by-side diff on github.com at a typical resolution and font size (e.g. the default settings on a MacBook Pro).  Yes, portrait mode is a different story, but I can live with resorting to landscape mode to view long lines neatly on my phone.

### Long lines in _Conversation_ view on Gitskarios v2.15.0

72 characters long:
![72-characters-long line in Conversation view on Gitskarios v2.15.0](https://drive.google.com/uc?export=view&id=1ZVpcqKuKmRQSyUqR9Br1mYfRxvHvqWwO7Q)

92 characters long:
![92-characters-long line in Conversation view on Gitskarios v2.15.0](https://drive.google.com/uc?export=view&id=1309Y2uSnub-mirrMt2tkwHC6NOp5cEbQeA)

It's worth noting that, as these screenshots show, Gitskarios isn't using a fixed width font.  Using a fixed width font might make more sense but may require careful tuning/compromise of the font size.

**Comment by slapperwan** [comment]
@maniac103 Can we link the filename in Conversation to the diff?  And not sure if we can straight goto the commented line in diff viewer.

**Comment by maniac103** [comment]
@slapperwan That's my plan. And yes, we can't go to a diff line at the moment, but it should be no problem to add that functionality.

**Comment by maniac103** [comment]
I pushed an initial version of this to the pr-comment-link branch. Could you please give this a try and/or point me to an example of a PR with a more complicated diff (additions + deletions, comment not at the beginning) so I can actually test the jump-to-line-in-diff-view functionality? Thanks :)

**Comment by slapperwan** [comment]
Tested this, the UI looks OK for me.  I guess the goto line not there yet?

@nisavid you can get the latest build for the apk at https://drone.io/github.com/slapperwan/gh4a/files

**Comment by maniac103** [comment]
@slapperwan I hoped it would be there yet ;) Got a PR to test it against?

**Comment by slapperwan** [comment]
I just did a quick test on the closed PR, create a comment somewhere in the middle of the diff file.

https://github.com/slapperwan/gh4a/pull/214

**Comment by maniac103** [comment]
OK, I'll check it.

**Comment by maniac103** [comment]
Fixed.

**Comment by slapperwan** [comment]
Tested and looks good.
