### ISSUE TITLE
Your Actions list missing items. 

### ISSUE THREAD

**Issue by akwala** [slapperwan/gh4a#348]
In my profile, the Your Actions list is missing at least one item. It shows an item dated Jun 24, followed by one dated Aug 4. There should be an item (opened issue) between these dated Jul 25.

**Comment by maniac103** [comment]
Are other 'opened issue' events present? In general I don't see much we can of there, the info shown comes directly out of Github's API.

**Comment by akwala** [comment]
@maniac103 Yes, other 'opened issue' events are present in the list.

**Comment by maniac103** [comment]
It looks like you'll have to take this up to GitHub. Please check their API response:

curl https://api.github.com/users/akwala/events/public

The last (oldest) event is dated 2016-06-23, the one before is dated 2016-08-04. Given the simple URL that reproduces the data Octodroid is showing, I can't see how we could change data there.
