### ISSUE TITLE
Feature Request: Issues filter for those in which I have participated. 

### ISSUE THREAD

**Issue by akwala** [slapperwan/gh4a#349]
When viewing the issues in a repo, it would help to be able to see a list of the repo's issues in which I have participated.

**Comment by maniac103** [comment]
Makes sense. I wonder whether we should replace the 'mentioned' tab with that one instead of creating a 4th tab.

(note to self: https://help.github.com/articles/searching-issues/#search-by-a-user-thats-involved-within-an-issue-or-pull-request)

**Comment by slapperwan** [comment]
@maniac103 I think @akwala is referring to repo's issue which currently has 2 tabs (Opened and Closed), not the My Issues view.

**Comment by maniac103** [comment]
@slapperwan Oh, right. That filter should be equally easy to implement, though.

**Comment by maniac103** [comment]
Implemented in #477
