### ISSUE TITLE
Any plan to support 4.44 tinted status bar？

### ISSUE THREAD

**Issue by WanderMax** [slapperwan/gh4a#351]
Now the top bar is system one, any plan to support 4.4 tinted status bar using KitKat translucent modes?
Reference here
https://github.com/jgilfelt/SystemBarTint

**Comment by maniac103** [comment]
No, I don't have any plans for that, for a couple of reasons:
- it'll make the already complicated code for supporting the 'open drawer over status bar' paradigm more complicated
- it's 'unusual' for apps in KitKat, as it isn't part of the UI guidelines for Holo
- KitKat will be phased out sooner or later anyway, so any work to target that seems like wasted effort (I just looked at our installs of the last 3 months, 86.8% were on Lollipop and newer; 8.9% were on KitKat)

A pull request would be fine with me if it isn't too intrusive (and doesn't use a third party - this should be doable just fine without it), but I won't invest time into it myself.
