### ISSUE TITLE
What API are you using to get trending?

### ISSUE THREAD

**Issue by srsudar** [slapperwan/gh4a#353]
I'm trying to piece together how you're getting the trending repos information. It looks like the magic might be happening in [TrendLoader.java](https://github.com/slapperwan/gh4a/blob/1a037ccf6df280bebd503e9c8c3bc62e7e2325f8/src/com/gh4a/loader/TrendLoader.java).

Looking at that code I don't recognize any github API endpoints. Are you using an internal API? Am I blind and missing something obvious? Are you scraping somehow? It isn't clear to me what the `POST` connection in that class is doing.

**Comment by slapperwan** [comment]
We are using service from import.io .

You can find more details at https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/fragment/TrendingFragment.java

**Comment by srsudar** [comment]
Great, thank you.
