### ISSUE TITLE
Navigation issue after search

### ISSUE THREAD

**Issue by sphingu** [slapperwan/gh4a#356]
1. Go to search page using side navigation.
2. Search with any name for example "gh4a".
3. Click on any repository.
4. Now click on back button from topbar.

It should redirect back to search result instead it redirect to user profile page of clicked repository

**Comment by touzainanboku** [comment]
I'm pretty sure that button is not a back button, but an up button.

**Comment by sphingu** [comment]
I might misunderstood it.
Thanks for the quick reply

**Comment by maniac103** [comment]
Yeah, the back button is at the bottom of your device ;) You can read about the thought process behind that here: https://developer.android.com/design/patterns/navigation.html#up-vs-back
