### ISSUE TITLE
Rotating phone while entering issue body loses text

### ISSUE THREAD

**Issue by JohnVeness** [slapperwan/gh4a#357]
While entering a new issue, if I rotate my phone from portrait to landscape or vice versa, while entering the issue body text, any text that I've entered so far is lost. This doesn't seem to happen while entering the issue title, or an issue comment. See this screencast, jerkiness when rotating is an artifact of the screen recorder, not seen in real life.
![screencast_2016-10-15-20-36-13](https://cloud.githubusercontent.com/assets/2512915/19412912/e94ffc78-9317-11e6-8d8e-86c9fe3d40dc.gif)

**Comment by maniac103** [comment]
Yup, confirmed. Will look at it, should not be a big deal.
