### ISSUE TITLE
Can't edit issues

### ISSUE THREAD

**Issue by JohnVeness** [slapperwan/gh4a#359]
If I make a typo in an issue title or body text, or for some other reason want to edit them, I cannot do so in OctoDroid. I can edit comments, just not the "original post". I can edit issue text on github.com. Can this be added to OctoDroid?

**Comment by maniac103** [comment]
So the issue is that you can't edit body and title of issues you opened yourself?

**Comment by JohnVeness** [comment]
Yes, exactly.
