### ISSUE TITLE
Show Closed button in My Issues and My Pull Requests screen should toggle to Show Open

### ISSUE THREAD

**Issue by JohnVeness** [slapperwan/gh4a#360]
In the My Issues and My Pull Requests sections, initially you are shown the open items, with a Show Closed button to switch to showing closed items. At that point, the button still says Show Closed, when in fact pressing it makes the open items show, so I think the button should be relabelled at that point.

**Comment by maniac103** [comment]
Oops, that's an embarrassing one. Should be easy to fix though :)
