### ISSUE TITLE
Handle long issue titles better

### ISSUE THREAD

**Issue by JohnVeness** [slapperwan/gh4a#361]
Currently, when viewing an issue, if its title is longer than two lines, it is just cut off. There is no indication that there is more text (e.g. an ellipsis) and no easy way to see the extra text, e.g. by clicking or scrolling, although turning to landscape works if it's not too long for that too.

See for example this issue (opened by me so my fault!)
![screenshot_20161016-101846](https://cloud.githubusercontent.com/assets/2512915/19416519/ac2cdfdc-938a-11e6-86f4-d082c4aa5ba8.png)

Probably best to not make the header any larger so one fix would be to repeat the title in normal size text in the scrollable area below, e.g. above or below the username and date/time. Maybe only do this if necessary, i.e. when showing an ellipsis in the header title above.

**Comment by maniac103** [comment]
Implemented in #473
