### ISSUE TITLE
White background behind nav buttons when viewing source

### ISSUE THREAD

**Issue by JohnVeness** [slapperwan/gh4a#362]
When viewing a source file, the background of the on screen navigation buttons turns white, making it hard to see the buttons. As soon as you start to scroll, the background turns black, as if it should have been black all along.
![screenshot_20161016-170314](https://cloud.githubusercontent.com/assets/2512915/19418818/fe177c4c-93c3-11e6-8647-bab78813c236.png)

**Comment by maniac103** [comment]
What device is that? Is this reproducible reliably, ideally on other devices as well, for you?

**Comment by JohnVeness** [comment]
That's on a Sony Xperia  Z5 Compact, but it also happens on a Nexus 7 (2013). Fully repeatable. Sometimes, as well as the white background, the actual source text is visible behind the nav buttons. It always turns black as soon as you start to scroll, or as soon as you touch the body text, in fact.

**Comment by maniac103** [comment]
And what Android version do your devices use?

**Comment by JohnVeness** [comment]
Both Android 6.0.1.

I said that sometimes the actual text appears behind the nav. Looking closely, it's actually repeated text from just above, see:
![screenshot_20161016-195730](https://cloud.githubusercontent.com/assets/2512915/19420031/120ae0d8-93db-11e6-8b91-a1d5b66ec8d9.png)

**Comment by JohnVeness** [comment]
Repeating text thing happens with dark theme too:
![screenshot_20161016-200602](https://cloud.githubusercontent.com/assets/2512915/19420096/22c40b4c-93dc-11e6-8ef0-8cf470217708.png)

**Comment by maniac103** [comment]
At this point I'm pretty much convinced this is a graphics driver or WebView problem, as from the screenshots it's pretty obvious that this is a glitch and not e.g. a wrong transparency of the nav bar.

I realize that doesn't exactly help you though :-/

**Comment by JohnVeness** [comment]
I haven't been checking often, but this issue doesn't seem to be occurring for me now. I've had minor OS and WebView updates do maybe one of them fixed it. I'll close this.
