### ISSUE TITLE
Trending repos no longer populates

### ISSUE THREAD

**Issue by jmullman** [slapperwan/gh4a#364]
Case: User selects any Trending view (Today, Week, Month)

Expected result: List of trending repos displayed based on selected filter (Today, Week, Month).

Actual result: Single, screen-centered message, "no repositories found"

**Comment by kshvmdn** [comment]
Also happening for me.

**Comment by maniac103** [comment]
I've fixed this server side (in the import.io configuration), should work again now. Let me know if it fails again.

**Comment by jmullman** [comment]
Confirmed on my end to be functional, thanks!
