### ISSUE TITLE
Incorrect date format

### ISSUE THREAD

**Issue by teod0r** [slapperwan/gh4a#380]
For billions of people MM/DD/YYYY is incorrect date format, when is should be DD/MM/YYYY

**Comment by maniac103** [comment]
Which date format are you referring to?

**Comment by teod0r** [comment]
It is DD.MM.YYYY or DD.MM.YY in Russia

**Comment by maniac103** [comment]
And where exactly do you see the supposedly wrong date format?

**Comment by teod0r** [comment]
In list of ussues

**Comment by maniac103** [comment]
What locale (language setting) are you using on your phone? In general those timestamps are formatted by a 3rd party library (https://github.com/ocpsoft/prettytime) which I don't have any control over. Only thing I can do is update it to the newest version, but I somehow doubt it's a library thing - I suspect the locale setting.

**Comment by teod0r** [comment]
ok
