### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ARoiD** [slapperwan/gh4a#381]
* What went wrong: A problem occurred configuring root project 'gh4a'. > Could not resolve all dependencies for configuration ':classpath'. > Could not find com.android.tools.build:gradle:2.2.3. Searched in the following locations: https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar https://maven.fabric.io/public/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom https://maven.fabric.io/public/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar Required by: :gh4a:unspecified

https://drone.io/github.com/slapperwan/gh4a/411

**Comment by maniac103** [comment]
It'll solve eventually, maven is probably slow again to deploy the new build tools.

**Comment by ARoiD** [comment]
@maniac103 looks like the drone builds are no more https://drone.io/

**Comment by maniac103** [comment]
(Closed due to drone.io being dead anyway)
