### ISSUE TITLE
don't reload file at screen rotate

### ISSUE THREAD

**Issue by PatrickvL** [slapperwan/gh4a#383]

**Comment by maniac103** [comment]
This is controlled by the Android framework ... usually nothing is reloaded on rotate.

**Comment by maniac103** [comment]
Or is this in a specific view only? If yes, in which one?

**Comment by PatrickvL** [comment]
Reload happens in the file view

2017-01-18 20:41 GMT+01:00 maniac103 <notifications@github.com>:
