### ISSUE TITLE
fix unreadable dark grey on black background

### ISSUE THREAD

**Issue by PatrickvL** [slapperwan/gh4a#385]
Dark color theme is very nice but text rendered in dark grey is unreadable

**Comment by maniac103** [comment]
Got an example/screenshot?

**Comment by XVicarious** [comment]
I do. Here ya go: http://i.imgur.com/wMqZ8dj.png

**Comment by Tunous** [comment]
@XVicarious See https://github.com/slapperwan/gh4a/issues/403

**Comment by Tunous** [comment]
@maniac103 He might be right that it's the same issue though. Grey could be a typo.

**Comment by XVicarious** [comment]
True, considering the last release was in June and this has been fixed in a
commit since then.

**Comment by maniac103** [comment]
Yeah, considering the lack of response from the reporter, I'm just going to assume he meant that issue. Closing.

**Comment by maniac103** [comment]
And yes, release management is our weak part :-/ A big fix release is imminent though.
