### ISSUE TITLE
Shortcut in sidebar to jump to my list of starred repos

### ISSUE THREAD

**Issue by evaryont** [slapperwan/gh4a#388]
I'd appreciate it if there were an additional quick access link in the sidebar to jump to the list of repositories I have starred.

**Comment by aisbergde** [comment]
+1

**Comment by smichel17** [comment]
@evaryont @aisbergde Do you ever use the `Bookmarks` function?

**Comment by Tunous** [comment]
#734 made it so starred repositories are positioned together with bookmarks and are accessible from the sidebar.
