### ISSUE TITLE
Issue/pull request action comment indicators

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#398]
Currently, there is no easy way to distinguish comments from issue/pull request actions such as close, merge, etc. What I propose is to add a small icon indicator near the user avatar which clearly shows that the specified comment has a special meaning. 

I did a small experiment to see what I could make and there is an example idea that I came up with:
![image](https://cloud.githubusercontent.com/assets/5156340/22980968/51904a7a-f39b-11e6-9fab-d3a3bc0a8529.png)

If it's something that you would like to be added I can properly finish my work and create a pull request.

**Comment by maniac103** [comment]
That idea sounds good to me. Feel freed to go ahead :) Don't forget the dark theme when adding new drawables though ;)

**Comment by Tunous** [comment]
Ok, great. I'll keep that in mind.
