### ISSUE TITLE
Dark green text is hardly visible in dark theme

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#403]
Example how it looks currently:

![screenshot_20170216_184147](https://cloud.githubusercontent.com/assets/5156340/23033235/9747d60a-f477-11e6-84a3-6845396f5782.png)

I have found it in the following screens but there might be more than that:

- [ ] Tag text for release info screen
- [ ] View more button for repositories in user screen

**Comment by maniac103** [comment]
Likely a wrong theme attribute is used there.
