### ISSUE TITLE
Pull requests don't show labels

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#404]
This is how they are displayed for issues:
![spectacle bc4725](https://cloud.githubusercontent.com/assets/5156340/23033474/80943042-f478-11e6-87b4-3dbadacf433c.png)
In the case of pull requests, this is not visible.

**Comment by maniac103** [comment]
Huh, it should be ... I remember having talked to the Github people about labels not being included in the PR response and adding code for fetching the labels separately... Will check this.
