### ISSUE TITLE
Pull request actions in toolbar disappear when changing tab to other than conversation

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#406]

**Comment by maniac103** [comment]
Fixed this in the printing branch; found it a little too invasive for the (bugfix only) master branch.

**Comment by Tunous** [comment]
You should rename that printing to something like develop and set is as default in repository settings so it gets automatically targetted when users create new pull requests. And then the references from commits like "Closes" should work for it too.

**Comment by maniac103** [comment]
I should probably rather just do stable branches ... will do so from the next release onwards.
