### ISSUE TITLE
All merged pull request display "Issue was closed" message

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#407]

**Comment by maniac103** [comment]
Right, that's how Github's API sends it: it sends an event with type 'closed'. Ref: https://developer.github.com/v3/issues/events/

**Comment by Tunous** [comment]
Wouldn't it be safe to ignore that event by not displaying it after pull request was merged? Unless it's somehow possible to reopen and close it after merging...

**Comment by maniac103** [comment]
The 'ignore' part isn't straightforward. One would have to filter the event list in the loader before displaying it, but only if it's a PR. And I'm really not sure what weird combinations of events are possible to happen...

**Comment by Tunous** [comment]
It's not that huge issue. I guess we can leave it as is.
