### ISSUE TITLE
Incorrect line numbers when adding line comment in diff view

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#409]
Often diffs contain folds which hide many lines but this behavior is not respected by the line display for line comments. It is always counted based on a number of visible lines.

**Comment by maniac103** [comment]
Got an example?

**Comment by maniac103** [comment]
Oh, right. Issue is here: https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/activities/DiffViewerActivity.java#L237 ... probably need to parse the line numbers out of the diff to calculate an offset :-/

**Comment by maniac103** [comment]
Actually parsing the numbers shouldn't be too hard. Every @@ line contains line numbers for old and new file, which then need to be incremented by one for old file (--- lines) or new file (for +++ lines) or both (for context lines). Depending on whether the comment is on a --- or +++ line, one can pass the appropriate number into the URL. Just need to decide which of the two numbers to use for context lines.

**Comment by Tunous** [comment]
I think it would be a nice idea to change the format of that message to display both numbers. Something like "Commented on line -274, +276" similar to the format used on the fold.
