### ISSUE TITLE
If there are no issues in issue list view header can't be scrolled to expand

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#410]

**Comment by maniac103** [comment]
I don't yet understand ... please elaborate :)

**Comment by Tunous** [comment]
Sorry, should be more specific. This is happening for me in my issues view when I'm viewing assigned tab. As I don't have any issues here the header is not expandable when scrolling up or down.

![peek 2017-02-16 19-21](https://cloud.githubusercontent.com/assets/5156340/23034779/32db24aa-f47d-11e6-96ce-345334e46c6e.gif)

**Comment by maniac103** [comment]
Uh, that one will be ... interesting to fix, as this almost for sure is an AppBarLayout issue.

**Comment by Tunous** [comment]
Easy, and the only solution I can think of is to not hide the RecyclerView here: https://github.com/slapperwan/gh4a/blame/1c127987a2df67721efac2bdd18be30bfe4c3304/src/com/gh4a/fragment/LoadingListFragmentBase.java#L83. This way AppBarLayout still sees a scrollable child and allows for expanding and collapsing. But it might have negative side effect that I'm not aware of...

**Comment by maniac103** [comment]
You mean keeping the RecyclerView visible over the empty view? That might work, but feels like a hack. I wonder whether there's a way by wrapping the empty view into some nested scrollable container.

**Comment by Tunous** [comment]
Yes that's what I meant. 

Another solution could be to make empty view extend NestedScrollingChild. Not sure if it would work tough.
