### ISSUE TITLE
Action to delete comment says cancel

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#411]
*Off-topic:*

@maniac103 Sorry for my issues spam ;)
I just think that it's best practice to first create issues before pull requests to allow for easier discussions and avoid wasting time. I'll probably work on most of them in the coming days/weeks if they're good.

**Comment by maniac103** [comment]
Makes totally sense. I added a few initial comments.

**Comment by Tunous** [comment]
For this one, I meant when long pressing on the trash icon. It should say "Delete" instead, as this seems to be what it is supposed to do.

**Comment by maniac103** [comment]
Ah, OK. Let's fix both then ;)

**Comment by Tunous** [comment]
Actually, to follow Material Design it would be better to display "Delete" and "Cancel" in the dialog. 

See https://material.io/guidelines/components/dialogs.html#dialogs-alerts
