### ISSUE TITLE
Direct link to line in commit doesn't work correctly  

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#413]
Instead of opening code view for the selected file with the specified line highlighted it is only opening commit screen and doesn't go further than that. 

Example: https://github.com/slapperwan/gh4a/commit/c021f4585244ba4a4cfdb90203aec1034818a47c#diff-1e105dc4c4e8c142976247ec34a5f610R275

**Comment by maniac103** [comment]
Now if you could tell me how to relate the diff-xxxxxx part to a diff hunk ;)

**Comment by Tunous** [comment]
As far as I understand it goes like this:

{commitSHA}#diff-{fileSHA}{lineNR}

{lineNR} starts either with L or R depending on the linked line number. L goes for the old numbers and R for new numbers. 

I'm not yet sure how exactly {fileSHA} works though. It might be something from git or only GitHub specific. Have to read about it somewhere.

**Comment by Tunous** [comment]
The [API](https://developer.github.com/v3/repos/commits/#get-a-single-commit) doesn't seem to mention that *(Perhaps it's not the endpoint used)* but I can see that there is a way to access file sha: https://github.com/eclipse/egit-github/blob/master/org.eclipse.egit.github.core/src/org/eclipse/egit/github/core/CommitFile.java#L156.

It might be possible to use it to know to which file and then line to redirect the user.

**Comment by maniac103** [comment]
That's a different SHA though. For your example: https://api.github.com/repos/slapperwan/gh4a/commits/c021f4585244ba4a4cfdb90203aec1034818a47c -> CommitFile SHAs are 15e6faf... and f17489f..., 1e105dc... is nowhere to be seen.

**Comment by Tunous** [comment]
Perhaps they generate it based on file name or something similar. I checked the history of that file and in each commit, it always had the same SHA. Sadly I didn't manage to find any mention of how they could be doing it...

**Comment by maniac103** [comment]
Maybe I should just ask them about it (together with asking if they plan to add a blame API at some point).

**Comment by Tunous** [comment]
Yeah, why not.

**Comment by maniac103** [comment]
The supposed SHA actually isn't a SHA, but an MD5 sum over the path of the file in question. Determining the right file becomes somewhat easy with that info ... @Tunous interested in implementing this? ;-)

**Comment by Tunous** [comment]
Sure, I can take a look at it this weekend.

**Comment by Tunous** [comment]
More links for testing:

https://github.com/slapperwan/gh4a/commit/c021f4585244ba4a4cfdb90203aec1034818a47c#diff-76dead059cb6d289e4835f61234e337c

https://github.com/slapperwan/gh4a/commit/c021f4585244ba4a4cfdb90203aec1034818a47c#diff-76dead059cb6d289e4835f61234e337cL19

https://github.com/slapperwan/gh4a/commit/c021f4585244ba4a4cfdb90203aec1034818a47c#diff-76dead059cb6d289e4835f61234e337cL19-L21

https://github.com/slapperwan/gh4a/commit/c021f4585244ba4a4cfdb90203aec1034818a47c#diff-76dead059cb6d289e4835f61234e337cR44-R46

**Comment by maniac103** [comment]
Fixed with #515.
