### ISSUE TITLE
Ordered lists are displayed with bullet points 

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#415]
Noticed here: https://github.com/slapperwan/gh4a/issues/358

**Comment by maniac103** [comment]
I assume you're using Android 7.x? This broke by a change of Google:

https://android.googlesource.com/platform/frameworks/base/+/8b36c0bbd1503c61c111feac939193c47f812190

They implemented <li> and <ul>, but not <ol>, so our custom tag handler now only sees the <ol> tag, but not the others, and their code inserts the bullet points for all <li> items.
