### ISSUE TITLE
Better Rendering of Markdown Codeblocks

### ISSUE THREAD

**Issue by coderfox** [slapperwan/gh4a#418]
In current version, codes are rendered just with a background only where the text lies, while codes and codeblocks looks the same. I think codeblocks should be rendered with background of the whole block.

**Comment by maniac103** [comment]
I don't understand the problem yet. Can you please illustrate it with a screenshot or something?
In particular, what do you mean by 'code' and 'codeblocks'? You don't by chance ask for the opposite of #267, do you?

**Comment by coderfox** [comment]
![img_20170217_204451](https://cloud.githubusercontent.com/assets/3616727/23065719/a6da5c68-f4dc-11e6-84e7-0606b0c87fe4.jpg)

**Comment by maniac103** [comment]
Ok, so it's `test` vs. ```test```

**Comment by coderfox** [comment]
Yes. I think the latter one should have a more "block-styled" appearance.

**Comment by maniac103** [comment]
Now I understand. Not sure if it's possible, will need to look into it. It might be possible though: http://stackoverflow.com/questions/10647141/highlight-text-row-in-textview-including-all-width

**Comment by maniac103** [comment]
Note to self: the above test translates to
```
<p>Ok, so it's</p>\n<p><code>test test2 test3</code></p>\n<p>vs.</p>\n<pre><code>test\ntest2\ntest3\n</code></pre>
```

so depending whether it's in pre or not, code should get the normal background span or the above solution.

**Comment by coderfox** [comment]
Thanks for your work. I'm looking forward to the feature. If the implement is too difficult, you may also drop it.

**Comment by maniac103** [comment]
Implemented in the printing branch:
![screenshot_20170218-155124](https://cloud.githubusercontent.com/assets/781373/23094065/3a8c8114-f5f2-11e6-94fe-328b279f20a1.png)
