### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by BitPuffin** [slapperwan/gh4a#42]
Another feature that I'd love to see is notifications.

obviously you would get spammed if you made it so that it notifies you every time someone push and stuff.

A great way to solve this would be able to 'mark' a report for notifications so that you only recieve notifications from those repos!

**Comment by TR4Android** [comment]
:+1:

**Comment by fountaingeyser** [comment]
:+1: This feature would really be awesome!

**Comment by julmot** [comment]
:+1:+

**Comment by julmot** [comment]
For those of you that want to receive notifications when switching back to a desktop browser, there is a plugin called "News Feed for GitHub" that is available for Chrome and Firefox (https://github.com/julmot/news-feed-for-github).

**Comment by Tunous** [comment]
This could be implemented with an AlarmManager and customizable interval.

**Comment by Bluscream** [comment]
Thanks for implementing notifications, may i ask why you didn't implement actual push-notifications tho?

**Comment by cdysthe** [comment]
Lack of notifications is the one reason I used FastHub for a while. OctoDroid is in other respect a better app but the lack of notifications (with a custom sound option) has made it harder for me to use OctoDroid exclusively on all my devices.

**Comment by Tunous** [comment]
I decided to first implement notifications viewing screen as that's what I primarily needed myself.

Having said that I still plan on working with this. I really want to have unread counter displayed on the app icon in the launcher and that would require same stuff as displaying actual notifications.

Sadly I'm not really capable of doing push-notifications (I guess this requires a working server to receive webhooks and send notifications?). My implementation would be pull-based checking for new entries every specified amount of time. I just have to find some time and come up with a solution that would with the new Android O background limits.

Unless there is someone who can do push-based notifications.

**Comment by maniac103** [comment]
Push indeed requires a server, which is out of scope at least from my side. A pull implementation probably is sufficient.
The O background stuff shouldn't be a problem, as the notification polling fits fine into the JobScheduler model.

**Comment by cdysthe** [comment]
Other clients I've used have pull which works just fine for this. A few timing options (like 5, 10, 30 minutes...) should be sufficient.

**Comment by Bluscream** [comment]
Currently i use gh::watch but i plah to completely switch to gh4a once thats implemented

**Comment by Bluscream** [comment]
Currently i use gh::watch but i plah to completely switch to gh4a once thats implemented

---
Sent from my Lenovo TAB 2 A10-70L running Android 6.0 via OctoDroid v4.2.0

**Comment by Tunous** [comment]
Added implementation for GitHub notifications (not like requested here https://github.com/slapperwan/gh4a/issues/42#issuecomment-1820377, which is unlikely to be added) in #736. It should be sufficient to resolve this issue.
