### ISSUE TITLE
Cannot create new issues on latest develop branch

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#422]
Title displays Edit issue #0 and fails on safe. Master branch works correctly.

**Comment by Tunous** [comment]
Broken by: https://github.com/slapperwan/gh4a/commit/4871dddeac30f7315e91461dc35e805d44ab9454

**Comment by maniac103** [comment]
*facepalm* hasExtra() probably returns true even if the passed extra is null. Should be easy to fix.
Note to self: should also kill the EXTRA_ISSUE definition while being at it.
