### ISSUE TITLE
Way to directly link to issue comment

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#423]
On GitHub website, it's possible to get a direct link to issue comment by copying it from the timestamp. Here it could be implemented similarly by copying it to clipboard when clicking on the timestamp. 
<br />
<br />Alternatively, add 3 dots menu to each comment where the edit button is currently and list all comment actions here. This would allow for adding more actions such as open in browser, copy link, share, edit, etc.

**Comment by maniac103** [comment]
Clicking on the timestamp seems a little obscure, but using an overflow menu would probably work for me ... can't think of many things to put there, though (copy link == share, and not sure whether open in browser is actually a useful comment action).

**Comment by Tunous** [comment]
That was just a quick list of ideas ;) I think that it's worth it just for the share and edit actions.

**Comment by Tunous** [comment]
Is there a way to get a link to comment? I can see that [API returns html_url](https://api.github.com/repos/slapperwan/gh4a/issues/423/comments) but it's not available via Comment class.

**Comment by maniac103** [comment]
We can just add it to the API. See https://github.com/maniac103/egit-github

**Comment by Tunous** [comment]
Great!
