### ISSUE TITLE
Scroll to opened comment

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#432]
Currently when entering issue or pull request via direct link to comment the screen always launches scrolled to top. It would be better if the screen scrolled to the linked comment once loaded so users don't have to do this manually. Optionally the comment could be also highlighted.

**Comment by maniac103** [comment]
Notes to self:
URL format: https://github.com/slapperwan/gh4a/pull/421#issuecomment-280699313
Relevant API: https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#scrollToPosition(int)

**Comment by Tunous** [comment]
Heh, I think I'm a bit too fast. I got this working for issues. Should I push pr with what I have so far?

**Comment by maniac103** [comment]
Yes, you are ;) I have it working for both issues and PRs already, will push once I fully tested it.

**Comment by Tunous** [comment]
Ok :)

**Comment by maniac103** [comment]
Should probably do the same thing for commit comments.

**Comment by Tunous** [comment]
And when clicking on a comment from feed. That's the primary use-case for me.

**Comment by maniac103** [comment]
What do you mean by 'from feed'?

**Comment by Tunous** [comment]
News Feed - main screen: https://github.com/slapperwan/gh4a/blob/printing/src/com/gh4a/fragment/EventListFragment.java#L207

**Comment by maniac103** [comment]
Got it. Should be easy to do with what I just pushed.

**Comment by maniac103** [comment]
BTW, for avoiding the 'too fast' issue in the future, could you please, when opening an issue, add a short notice in those cases where you're willing to work on resolving the issue and submit a PR? This makes sure we don't start working on stuff in parallel. Thanks :)

**Comment by Tunous** [comment]
Sure.

**Comment by maniac103** [comment]
Just for later reference: https://github.com/slapperwan/gh4a/commit/edd5d4ad4290001b5b97d29f3bf6a3dfcd43ff9a implemented the original request.

**Comment by maniac103** [comment]
@Tunous Can you please double check if everything is working as expected now?

**Comment by Tunous** [comment]
Highlight doesn't work for issue comments.

**Comment by Tunous** [comment]
And it doesn't scroll when clicking on event for pull request line comment.

**Comment by maniac103** [comment]
What API level are you on?

**Comment by Tunous** [comment]
7.0 (24) - for pull request comments it worked

**Comment by maniac103** [comment]
Better now? ;-)

**Comment by Tunous** [comment]
I think it highlights a bit too early. It does so almost together with displaying rest of the content and since it's a subtle hint the distraction of other content loading makes it easy to miss.

**Comment by Tunous** [comment]
(It does work now)

**Comment by Tunous** [comment]
Oh it's just the highlight in issues that is too fast. The one for pull requests is perfect.
