### ISSUE TITLE
Code blocks with syntax highlighting tag render no background 

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#433]
```
int a = 1;
```

vs

```java
int a = 1;
```

**Comment by maniac103** [comment]
It translates to different HTML, it looks like:

```
<pre><code>int a = 1;
</code></pre>
```

vs.

```
<div class="highlight highlight-source-java"><pre><span class="pl-k">int</span> a <span class="pl-k">=</span> <span class="pl-c1">1</span>;</pre></div>
```

Currently the background is triggered by the <code> tags. Not sure how to properly (and generically) handle the div-span combination.

**Comment by Tunous** [comment]
Not sure how the tag handles works but if it is aware of tag classes it could be possible to treat them just like <pre> with <code> and ignore spans.
