### ISSUE TITLE
Handle <a id=""> tags in markdown files 

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#434]
This is a neat GitHub feature that allows for creating direct links to specific sections of markdown files. The tag itself is not rendered but adds to the marked fragment an identifier which then can be referenced to directly link to it. 

An example can be found in the readme of my library: https://github.com/Tunous/SwipeActionView/blob/master/README.md. Here I used this feature to create table of contents in which you can click on links to scroll to specific sections. This feature doesn't work in OctoDroid - clicking on them doesn't do anything. 

Another issue is that these tags aren't hidden in OctoDroid like on GitHub.

**Comment by maniac103** [comment]
This probably either requires a showdown update, or dropping showdown completely and fetching markdown files pre-rendered. I tend to say the latter is the better idea, need to check whether it's possible to do in all cases.

**Comment by maniac103** [comment]
When dropping your readme into the showdown demo [1] the anchor tags are at least rendered correctly, even though they don't work correctly (they might do in our WebView though), so a showdown update might already help.
Fetching prerendered content doesn't seem to be an option though: when passing the `Accept: application/vnd.github.v3.html+json` header, I only get HTML, no JSON. I was hoping for the HTML to be present (base64 encoded) in the `content` field of the JSON response, just like the markdown is.

[1] http://showdownjs.github.io/demo/

**Comment by maniac103** [comment]
Problem is caused by by the way the markdown is passed to showdown. Should just switch to use txtmark instead.
