### ISSUE TITLE
Markdown file view doesn't render gif images

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#435]

**Comment by maniac103** [comment]
Got an example? As this is just a WebView, I'd expect this to just work.

**Comment by Tunous** [comment]
https://github.com/Tunous/SwipeActionView/blob/master/README.md

Preview image under table of contents

**Comment by maniac103** [comment]
It's the relative URL that's killing it. WebViewerActivity uses `file:///android_asset/` as base URL (because it fetches a number of resources from assets from there) and then can't find your gif. One would need to rewrite relative to absolute URLs there. This actually is a similar issue as #230.

**Comment by maniac103** [comment]
https://github.com/slapperwan/gh4a/commit/3bccb5266d98ee120b17be1a47d01e4f95216a08 fixed that problem in the past, but that fix was nuked by https://github.com/slapperwan/gh4a/commit/ba6119be4b6fb43fb8562cf9b8f0dfd11b938a88. When switching to a native markdown rendering library (I'll probably use textmark), I'll make sure to restore that relative URL rewriting.
