### ISSUE TITLE
Display time when comment was edited 

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#436]

**Comment by maniac103** [comment]
Test comment

**Comment by maniac103** [comment]
Just wanted to check whether it's actually in the API ... it is, as updated_at field. We probably want to display an 'edited x hours ago' hint if created_at != updated_at.

**Comment by Tunous** [comment]
3 hours ago (edited 2 hours ago) 

This would look good

**Comment by maniac103** [comment]
Yeah, that's what I thought of.
