### ISSUE TITLE
View assignees in issues/pull requests list

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#442]
Perhaps similarly to how labels are displayed.

**Comment by maniac103** [comment]
I think I had it display a small avatar icon at some point in the past, but it looked ugly/too cluttered. Open for proposals though.

**Comment by Tunous** [comment]
![screenshot_20170220_184625](https://cloud.githubusercontent.com/assets/5156340/23136430/fd459212-f79c-11e6-8bff-9af190760984.png)

It doesn't look that bad in my opinion. We could just display up to 2 assignees.

___

Alternatively list them all next to each other under the issue number.

![screenshot_20170220_185214](https://cloud.githubusercontent.com/assets/5156340/23136578/b5b56476-f79d-11e6-97d2-015fdc2efda1.png)

I start to like this version better :smile:

**Comment by maniac103** [comment]
I don't really like either, TBH. Feels like information overflow, as the assignee isn't really important IMHO. For the (rare?) cases where it is important, one could simply use the 'filter by assignee' option.

**Comment by Tunous** [comment]
Ohh so that option should be available but isn't...

Agreed!

**Comment by maniac103** [comment]
> Ohh so that option should be available but isn't...

But it *is* available.

**Comment by Tunous** [comment]
https://github.com/slapperwan/gh4a/issues/443
