### ISSUE TITLE
Option to filter by assignee is not available for non-collaborators

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#443]
It works only in the repositories I own or am collaborator.

**Comment by maniac103** [comment]
Damn, right. Issue is that the list of potential assignees to select from is populated from the repo collaborator list, which is only accessible for collaborators. Suggestions? :-/

**Comment by Tunous** [comment]
Search API? https://developer.github.com/v3/search/

**Comment by Tunous** [comment]
:man_facepalming: Oh wait that doesn't list collaborators...

**Comment by Tunous** [comment]
Perhaps this: 

https://developer.github.com/v3/issues/assignees/#list-assignees
https://api.github.com/repos/slapperwan/gh4a/assignees

**Comment by maniac103** [comment]
That sounds like the right thing to use. I wonder whether this API wasn't available at the time this code was written.

**Comment by Tunous** [comment]
Something is off. When I select you from issues list of this repo it selects slapperwan. And when I select him it opens his profile.

**Comment by maniac103** [comment]
I'll check it, I only tested any assignee and unassigned :-/

**Comment by Tunous** [comment]
Also, shouldn't pull requests list have toolbar menu icons for search and menu too? It's gone but I'm not sure when that happened.

**Comment by maniac103** [comment]
PR list never had that, I never implemented that there ... even though it would be straightforward.
