### ISSUE TITLE
Add search and filtering to pull request list

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#445]

**Comment by maniac103** [comment]
It probably is possible to unify IssueListActivity and PullRequestListActivity. Only difference is (or at least should be) the title and type of instantiated fragment.

**Comment by Tunous** [comment]
I'll look into this.

**Comment by Tunous** [comment]
Looks like this requires more work. Issues list uses [/search/issues](https://developer.github.com/v3/search/#search-issues) API endpoint to handle the filter data while pull requests list uses the [/repos/:owner/:repo/pulls](https://developer.github.com/v3/pulls/#list-pull-requests) endpoint. 

We might want to switch to the search endpoint unless there are some required fields missing in it.

#472 would be fixed if we switched to search.

**Comment by maniac103** [comment]
Question is whether the pull_request field in the returned issue list is (fully) populated or not.

**Comment by Tunous** [comment]
It's missing a lot of information :(

**Comment by maniac103** [comment]
Welcome to the world of Github's API :-/ It's full of such inconsistencies between issues and PRs, even though a PR is only an issue with extra information attached.

**Comment by Tunous** [comment]
Yeah, so this issue should get the `needs-api-support` label and stay forgotten :cry:

**Comment by maniac103** [comment]
At least the label is right. But yeah, I don't have high hopes on getting API support there, I asked them previously about getting the labels field filled in PR list responses and got nowhere.

**Comment by Tunous** [comment]
Actually pull requests list doesn't need that much information looking at the 'My Pull Requests' screen. I think we only would lose the merged indicator I added recently and gain comments count instead.

**Comment by Tunous** [comment]
Search api has is:merged filter which could be added instead of indicator. It seems worth switching to the search API in my opinion. Filters are a really useful feature so it would be nice to have that for pull requests too.

**Comment by maniac103** [comment]
Yeah, fine with me. This would likely allow dropping a shitton of (PR specific) code as well.
What fields does the pull_request field in the returned issues have filled?

**Comment by Tunous** [comment]
Just the links https://api.github.com/search/issues?q=repo:slapperwan/gh4a%20type:pr

**Comment by maniac103** [comment]
Then that field indeed is more or less useless.
We could probably also split the PR lists in 3 tabs (open, closed, merged); we wouldn't need the indicator in that case.

**Comment by Tunous** [comment]
Indeed. That's a nice idea.
