### ISSUE TITLE
Mention suggestions

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#447]
When typing @ in comments or issue body display suggestions for users to mention. 

It might be possible to do with [AutoCompleteTextView](https://developer.android.com/reference/android/widget/AutoCompleteTextView.html) and adapter that overrides filtering behavior to only work when @ character is typed. 

As for the list of users to suggest then I'm not sure how GitHub does this but I think it's OK to just list repository collaborators and current issue/pr participants.

**Comment by Tunous** [comment]
Working on this.

**Comment by Tunous** [comment]
@maniac103 In which package or file should I put special generic classes:

```
WhitespaceTokenizer implements MultiAutoCompleteTextView.Tokenizer

PrefixFilterArrayAdapter<T> extends ArrayAdapter<T>
```

**Comment by maniac103** [comment]
How large are those and how widespread are they used? If small, UiUtils is my dumping ground for such things, if large, maybe separate classes in widget/ are the best solution ... adapter/ is only used for list adapters.

**Comment by Tunous** [comment]
Then UiUtils and widget/ should work.
