### ISSUE TITLE
Rework commenting on file lines 

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#455]
This issue is about the dialog that appears when adding a new line comment or replying to existing one. 

Currently it's annoying to work with it due to these issues: 
- Only single line of context is shown
- When replying to other comment it's not shown for reference 
- When something goes wrong and commenting fails everything is lost (similar to https://github.com/slapperwan/gh4a/issues/358) 

My idea is to replace it with a screen similar to commit comments but with an additional header showing 7 lines of context: 3 above, 3 below and highlighted line on which the user is commenting.

Although for that to work the best there should be also a way to expand the size of the comment box used in that screen as we will lose the size of it in current dialog. (https://github.com/slapperwan/gh4a/issues/365)

**Comment by maniac103** [comment]
Another useful case for using a bottom sheet ;)

**Comment by Tunous** [comment]
Improved in #536
