### ISSUE TITLE
Adding new issue doesn't show it in the list immediately 

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#458]
Requires a reload for it to show up.

**Comment by maniac103** [comment]
Is this still an issue with https://github.com/slapperwan/gh4a/commit/6a9d10331b9c8aa0720d251bea2caf89b08622cf ?

**Comment by Tunous** [comment]
Yes

**Comment by Tunous** [comment]
It seems like reload happens quickly after new issue screen disappears but it doesn't make the new issue to show up.

**Comment by Tunous** [comment]
https://github.com/slapperwan/gh4a/blob/printing/src/com/gh4a/activities/IssueListActivity.java#L327
`mOpenFragment` is always null for me here.

**Comment by maniac103** [comment]
Hmm, I suspect the activity gets recreated then. Best idea probably is to stop remembering fragments in the activities and expose the adapter's getExistingFragment instead. Will need to see how much more effort/uglier code that is.

**Comment by maniac103** [comment]
Alternatively make the adapter call back into the activity in instantiateItem and remember fragments from there.

**Comment by maniac103** [comment]
@Tunous Can you please check whether it's better with the above commit? If not, I guess I'll also need to make a test repo - alternatively you could give me access to yours :)

**Comment by Tunous** [comment]
Invited you to it

**Comment by Tunous** [comment]
Still broken

**Comment by maniac103** [comment]
I can't repro here anymore, and mOpenFragment is != null for me now as well.

**Comment by Tunous** [comment]
OK there is how it looks like:

```
Opening issues list:
- onCreate
- onFragmentInstantiated, mOpenFragment = IssueListFragment{f110f30 id=0x7f0d016c}

Entering new issue screen and creating it:
- onCreate
- onActivityResult, mOpenFragment = null
- onFragmentInstantiated, mOpenFragment = IssueListFragment{db19738 #0 id=0x7f0d016c}
```

Apparently, the issues list activity is recreated and the activity result is received before instantiating the fragment. It probably is filled with the saved data so the new issue is not present.

**Comment by Tunous** [comment]
Easy to reproduce if you enable the "Don't keep activities" setting in developer options, but it was happening for me also with it turned off.

**Comment by maniac103** [comment]
From my testing there (also?) seems to be something on the server side. I added debug output and saw the new list indeed being loaded after returning to the issue list activity, but the server response simply didn't include the new issue. Adding a Thread.sleep(1000) in PageIteratorLoader.loadInBackground makes it work. I wonder whether they're caching responses or something.

**Comment by maniac103** [comment]
This might work: https://gist.github.com/maniac103/ea8f5f5df2d547b43918ae21d4385ebd ... it's ugly, but I guess we won't be able to change their server side behaviour.

**Comment by Tunous** [comment]
Works correctly with that change :+1:

**Comment by maniac103** [comment]
Seemingly still happens for me?

**Comment by Tunous** [comment]
Yep happened to me too. Maybe needs a bit longer delay.

Alternatively we could implement #496 and reload the list when leaving that activity instead.
