### ISSUE TITLE
Typing html tags in comments can crash the app

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#460]
https://github.com/slapperwan/gh4a/issues/433#issuecomment-281824177

After adding this comment the app crashed and was continuing to do so every time I came back to see this comment. 

It looks like on GitHub these were interpreted differently too and made code block appear...

I typed `<pre> with <code>`.

**Comment by maniac103** [comment]
Code inside of pre is what makes a code block, see #418. Looks like a newline is missing after the code block though ... guess I should enforce adding a newline if not yet present there.
