### ISSUE TITLE
Use Oauth web flow for login?

### ISSUE THREAD

**Issue by maniac103** [slapperwan/gh4a#464]
We're currently using the simple oauth flow where we let the user enter user name and password to generate an oauth token. From looking at Play Store comments, people seem to be unhappy with that because they believe entering the password into Github's login form is more secure. We should ponder whether we want to switch to the web flow for authentication because of that.

**Comment by maniac103** [comment]
Personally I don't agree with the assertion of the entering the password into a WebView (controlled by us) being any more secure than entering into an EditText (controlled by us), but whatever. Implementing the web flow should be more or less straightforward, but has a few caveats:
- How would we want the UX to look like?
- Are we ok with home-builders of OctoDroid having to register an app with Github for using their home built version? For using the web flow one needs secret tokens that we can't put in the source.
- Need to check whether there's any implications on the generated tokens regarding the authorization level.

@slapperwan @Tunous thoughts on this?

**Comment by maniac103** [comment]
BTW, if we receive 1 star reviews in Play Store, 90% of the time it's because of this. There are a lot of paranoid people out there, it seems. :(

**Comment by Tunous** [comment]
I think it should be done through users default web browser (or custom tabs) instead of WebView. That way it's more secure and possibly they might not have to login again if they are already logged in here.

UX would be like this:
At launch show introduction screen with a button to log-in that redirects users to their browser. There they login, approve the application and then the result is communicated back to the application where it starts up to the default screen.

**Comment by maniac103** [comment]
I need to check whether it's at all possible to do this via the user's default browser (at this moment I think it isn't).
Currently we allow the user to do a few actions pre-login (search, browse trending repos etc.), where I can't think of how to integrate into such an introduction screen yet. Should we just drop that and enforce login before being able to do anything?

**Comment by maniac103** [comment]
Thinking about it, I think the main issue is that one needs to use a custom callback URL, which leads to  the activity picker popping up at the end of the login process asking you whether you want to open the URL in the browser or the app. IIRC Gitskarios behaved like that, and it felt very awkward. The Github app (which is now PocketHub) uses a WebView, probably for that very reason.

**Comment by Tunous** [comment]
> which leads to the activity picker popping up at the end of the login process asking you whether you want to open the URL in the browser or the app

That's not necessairly true. If it's possible the callback URL could be set to something like: `com.gh4a://OAuthLogin` and then handled in `AndroidManifest`:

```
<activity
    android:name=".HandlingActivity"
    android:launchMode="singleInstance">

    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>

        <data
            android:host="OAuthLogin"
            android:scheme="com.gh4a"/>
    </intent-filter>
</activity>
```

That way only this application knows how to handle this specific URL and the browser won't pop-up. I use an approach like this in my app and it works nicely.

**Comment by Tunous** [comment]
> Currently we allow the user to do a few actions pre-login (search, browse trending repos etc.)

I didn't know about that. The login button could be also put somewhere in the drawer and on screens that can't be used without it.

**Comment by maniac103** [comment]
I just checked this. The chooser actually pops up when going to Github's oauth endpoint, because Octodroid registers for all github.com URLs. This seems to be a problem solvable with custom tabs, though, and probably is manageable if Chrome isn't installed as well. Will explore this further.

**Comment by maniac103** [comment]
Got it working end-to-end with custom tabs. The flow actually isn't too bad, it's a shame that custom tabs didn't exist last time I tried it. Will look into the fallback working properly, clean up and ship this, I guess. For the not-yet-logged-in case we can basically keep everything as-is it looks like; we'd just replace the username + password fields by some text blurb saying 'press login to login via github or select an option in the navigation drawer to the left'.

Ugliest thing is that everyone of us will need to setup an application with github to get his personal client id + secret, but I guess this can be remedied with a proper readme.'
