### ISSUE TITLE
Reopening own issue closed by collaborator

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#467]
This isn't possible from GitHub web. In the application, the button to reopen that issue is present but fails when clicking on it.

Additionally, the error message says "Closing issue failed" instead of "Reopening issue failed".

**Comment by maniac103** [comment]
Uh, this is ugly. This means for determining whether a user can reopen an issue, I need to fetch the collaborator status of the user who closed the issue?

**Comment by maniac103** [comment]
Actually, thinking about it, it should be sufficient to check whether the closing user equals the creating user.
