### ISSUE TITLE
Add the ability to search in a repository

### ISSUE THREAD

**Issue by The-Fireplace** [slapperwan/gh4a#479]
I want to be able to search a repository for code, much like you can do on the GitHub website. Idea for where the button could go:
http://imgur.com/XUIFYWf

**Comment by maniac103** [comment]
There's no space there (only 2 icons + overflow are possible), but adding it to the menu shouldn't be a big problem.
I guess the easiest way would be doing it as a 'shortcut' into the search activity with the repo name pre-filled.
