### ISSUE TITLE
Going back from edit milestone screen should show list of milestones instead of issues

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#485]

**Comment by maniac103** [comment]
Agreed. I even wonder whether the edit activities (also applies to e.g. the issue edit activity) shouldn't just finish() instead.

**Comment by Tunous** [comment]
I think it's safer to navigate up. If it was opened from different screens users could be redirected to different places when using up button and that wouldn't be consistent with the up button behavior in the other parts of the app.

**Comment by maniac103** [comment]
Hmm, you got a point there. The issue editor should probably still go back to the issue page instead of the issue list though.

**Comment by Tunous** [comment]
Yeah, in that case, the issue screen is a good parent activity.

**Comment by maniac103** [comment]
Issue is fixed by your PRs, but I'm intentionally keeping this one open to be reminded to fix the close confirmation dialog button tomorrow ;)
