### ISSUE TITLE
Do not allow refreshing issue when it is still loading

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#502]
Whenever I open issue knowing that I'll want to scroll down I start doing so as soon as the screen launches. **If all worked correctly then my scrolling shouldn't do anything.** Instead what happens is that as soon as I release my finger the issue gets refreshed. 

I tried waiting for the issue to load before releasing my finger to see how pull to refresh indicator behaves and what I noticed is that the refresh indicator is not shown. Moving finger up or down doesn't change that too. But somehow even though it never appears releasing the finger always reloads the issue. 

I don't know if this bug is only exclusive to issue screen or other screens too but I couldn't reproduce that in issues list screen.

**Comment by Tunous** [comment]
Easy way to reproduce is to:

1. Open the issue
2. As soon as empty screen appears press down on it and keep the finger down 
3. Wait for content to load
4. Once it appears release the finger 

Now what happens is that pull to refresh indicator appears and the issue reloads. **This happens even when finger didn't move.**

**Comment by maniac103** [comment]
Interesting bug. I'll look into it.

**Comment by Tunous** [comment]
Noticed that it still happens but not as often as before. Now to reproduce I have to open the issue and wait short time before pressing down finger (but not too long so the content doesn't load yet)

**Comment by Tunous** [comment]
The issue might be here: https://github.com/slapperwan/gh4a/blob/printing/src/com/gh4a/activities/IssueActivity.java#L160 Content is set here to be shown which enables the refresh but the problem is that at this point the IssueFragment was just created and comments didn't load yet.

I'm confirming this observation by checking if the header is visible when I press down my finger. If it's not then the refresh won't happen but if it is and comments aren't loaded yet then the refresh will happen.

**Comment by Tunous** [comment]
@maniac103 Reopen? It's really annoying when this happens.

**Comment by maniac103** [comment]
Sure. I guess the way to go is making the fragments pretend they're scrollable while mContentShown == false.

**Comment by maniac103** [comment]
Can you give this a try?

```diff
diff --git a/src/com/gh4a/fragment/LoadingFragmentBase.java b/src/com/gh4a/fragment/LoadingFragmentBase.java
index 7951389..afe4ef0 100644
--- a/src/com/gh4a/fragment/LoadingFragmentBase.java
+++ b/src/com/gh4a/fragment/LoadingFragmentBase.java
@@ -66,7 +66,7 @@ public abstract class LoadingFragmentBase extends Fragment implements
 
     @Override
     public boolean canChildScrollUp() {
-        return UiUtils.canViewScrollUp(mContentView);
+        return !mContentShown || UiUtils.canViewScrollUp(mContentView);
     }
 
     protected void setHighlightColors(int colorAttrId, int statusBarColorAttrId) {
```

**Comment by Tunous** [comment]
This doesn't work.

**Comment by Tunous** [comment]
Reopen. That's old not fully working fix.

**Comment by maniac103** [comment]
Yup, that closing was accidential due to me merging printing back to master (which is now the new development branch).

**Comment by Tunous** [comment]
Closing, it's fixed now. (You can refresh while the issue is loading but it doesn't bug out like before)
