### ISSUE TITLE
Some images aren't rendered

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#504]
![](https://camo.githubusercontent.com/6aada0559be7ccf856ef76f3d4b4b8df391e05e4/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f7365742d7269676874) 

Probably something to do with content type as viewing that image separately in browser returns "Non-Image content-type returned" but it gets displayed correctly on GitHub.

**Comment by maniac103** [comment]
- OKHTTP throws a FileNotFoundException for this file
- Accessing it in Firefox yields HTTP error 400 ('bad request')
- Github's web UI doesn't render it for me

... I don't think not displaying this image can be called a bug in Octodroid ;-)

**Comment by Tunous** [comment]
That's weird. It does load for me in GitHub's web and mobile UI and also does in Firefox and Chrome... Viewing that link directly also works in both browsers.

**Comment by Tunous** [comment]
And now it started working in OctoDroid so it's definitely GitHub bug.
