### ISSUE TITLE
"Closed Issues" button should say "Open Issues" when viewing closed issues.

### ISSUE THREAD

**Issue by The-Fireplace** [slapperwan/gh4a#510]
So, when you are on the open issues button and press "Closed Issues", it goes tonthe closed issues screen. However, the button still says "Closed Issues", when it should say "Open Issues".
Screenshot:
http://i.imgur.com/0AQi7mK.jpg

**Comment by The-Fireplace** [comment]
Edit: I meant to say the "Show Closed" button should say "Show Opened" on that screen. Can't seem to edit this issue to say that, so commenting it.

**Comment by maniac103** [comment]
Both the button and the inability for issue creators to edit the issue are already fixed, we just need to do a release with those fixes.

**Comment by maniac103** [comment]
For reference: #359, #360.
