### ISSUE TITLE
Crash when trying to open link from pull request

### ISSUE THREAD

**Issue by Tommy-Geenexus** [slapperwan/gh4a#513]
Upon clicking a link in the conversation of a (merged in that case) pull request,
which leads to a commit in a specific repo, OctoDroid first tries to load then
crashes (on receiving loader result it seems) with below error: 

FATAL EXCEPTION: main
Process: com.gh4a, PID: 16115
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Stringorg.eclipse.egit.github.core.User.getLogin()' on a null object reference at com.gh4a.widget.DropDownUserAdapter.replace(DropDownUserAdapter.java:50) at com.gh4a.fragment.CommentBoxFragment.setMentionUsers(CommentBoxFragment.java:73) at com.gh4a.fragment.CommitNoteFragment.onAddData(CommitNoteFragment.java:153) at
com.gh4a.fragment.ListDataBaseFragment$1.onResultReady(ListDataBaseFragment.java:25) at com.gh4a.fragment.ListDataBaseFragment$1.onResultReady(ListDataBaseFragment.java:16)
....

**Comment by maniac103** [comment]
Already fixed ;)
https://github.com/slapperwan/gh4a/commit/3495b13c3064ff4c074d188501da43954878b0d6

**Comment by Tommy-Geenexus** [comment]
Derp, forgot to check for updates here before opening. Good job!
