### ISSUE TITLE
Some screens have incorrect parent activities

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#517]
Should check every single screen and create a list with these broken so we can fix them all in a single pull request.

There is what I have found so far:

- Release
- Pull request file diff
- Milestones list when entered from pull requests list (redirects to issues instead of pull requests)
- Labels list (same as above)
- Pull request commit

**Comment by maniac103** [comment]
I've fixed release, PR diff and PR commit, but I'm unsure about whether milestones and labels actually need changes: Both don't have an obvious parent (as they belong to both PRs and issues), so I think the current behaviour is fine if one ignores the way how one reached the milestone/label list (which one should as the back arrow is about hierarchical, not temporal navigation).

**Comment by Tunous** [comment]
I agree with you but this case is a bit different. The milestone and labels list do have a single obvious parent. It's the IssueListActivity. The only thing that's different is the argument which specifies if it displays pull requests or issues. I think remembering its state isn't against hierarchical navigation and is the best option to do here.
