### ISSUE TITLE
Add refresh action to toolbar menu

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#531]
When there is a long content and I want to refresh it, then I have to do a lot of scrolling to reach the top. Adding refresh action to toolbar menu would solve this issue. 

Screens where it could be useful are these when the content can often change while the users are still viewing it. Mostly:

- Issue/Pull request comments
- News feed
- Notifications

**Comment by maniac103** [comment]
I see the problem, but I think adding a refresh button is not the right solution. IMHO adding a 'scroll to top' button/menu entry/whatever or adding fast scrolling (-> #233) is the much better solution, as it wouldn't introduce UI redundancy.

**Comment by Tunous** [comment]
Hmm, from these options fast scrolling seems to be the best as it solves more than one problem. 

I'll just close this issue in favor of #233.
