### ISSUE TITLE
Issue search bugs

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#533]
1. Initial search often returns invalid results or no results at all. Changing the input and pressing enter again solves this (might require few attempts sometimes)
2. Resubmitting search refreshes only one fragment (either closed or open). If you keep tapping enter key you can see that reload animation happens only every 2 clicks. I tried switching pages and noticed that one time it refreshes only open issues and the other time closed and so on.

**Comment by Tunous** [comment]
Something tells me that the second issue is within this method: https://github.com/slapperwan/gh4a/blob/master/src/com/gh4a/activities/IssueListActivity.java#L319 but I didn't test it.

**Comment by maniac103** [comment]
That method only determines whether a given fragment needs to be kept or thrown away when invalidateFragments() is called. It isn't related to refreshing fragment content.

**Comment by maniac103** [comment]
Uh, why do we keep track of only one search fragment? That doesn't feel right...

**Comment by maniac103** [comment]
*sigh* no, 'might fix' doesn't mean 'fixes' -> reopening

**Comment by Tunous** [comment]
Doesn't fix.

**Comment by maniac103** [comment]
Then I need a reproduction scenario, please. I can neither repro 1) nor 2) at the moment.

**Comment by Tunous** [comment]
Here is issue 1:

![peek 2017-03-19 17-06](https://cloud.githubusercontent.com/assets/5156340/24082467/6741e416-0cc6-11e7-8980-7205b4db8b41.gif)

Type initially gist -> No results, change to Gist -> got results, same for Gist -> gist.

I think that 2) got fixed but I didn't notice, can't reproduce it anymore

**Comment by maniac103** [comment]
I can repro with that info, thanks. Will look into it.
