### ISSUE TITLE
checkbox aren't supported

### ISSUE THREAD

**Issue by antoine-pous** [slapperwan/gh4a#534]
`- [ ]` is not supported when we read MD files

**Comment by maniac103** [comment]
Works for me on latest code with this file: https://github.com/Tunous/TestingRepo/blob/master/markdown-test.md ... can you re-test with 4.0.4? If your file doesn't work there, got a link to it?

**Comment by antoine-pous** [comment]
Oh, my mistake, this is'nt on MD files but on PR/Issues.
