### ISSUE TITLE
garbage characters when I open file has Chinese character

### ISSUE THREAD

**Issue by AoEiuV020** [slapperwan/gh4a#546]
sorry for my poor English,
It's ok when I open a Chinese repository,
I can see Chinese character normally,
but if I switch to 'files',click the file 'README.md',
I must have got garbage characters,
other files are the same,

version 4.5,download from google play,

**Comment by AoEiuV020** [comment]
only markdown file will be so,

**Comment by maniac103** [comment]
I guess this is already fixed, but for double checking, do you have a link to an example file?

**Comment by AoEiuV020** [comment]
https://github.com/AoEiuV020/UserDictionaryBackup/blob/master/README.md

2017年3月24日 00:05，"maniac103" <notifications@github.com>写道：

I guess this is already fixed, but for double checking, do you have a link
to an example file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/slapperwan/gh4a/issues/546#issuecomment-288769359>, or mute
the thread

**Comment by maniac103** [comment]
Yep, that looks fine with current code. It was fixed in commit https://github.com/slapperwan/gh4a/commit/3a6660fe547faca686888fc23b5535be6829c0db

**Comment by AoEiuV020** [comment]
@maniac103 
but you have not merged this commit on tag v4.0.5,
why?

**Comment by maniac103** [comment]
Because I forgot :(
There will be a 4.1 release soon though.
