### ISSUE TITLE
Mention people by tapping their avatar.

### ISSUE THREAD

**Issue by Bluscream** [slapperwan/gh4a#566]
When tapping someones username it brings you to their profile. I'd like to see a similar functionality that pastes @username> when tapping someones avatar

**Comment by maniac103** [comment]
We already have a mention mechanism: just type '@'.

**Comment by Tunous** [comment]
Could also add mention action to the comment menu for quick access. But I think that just typing @ is easy enough to use.

**Comment by Bluscream** [comment]
hm?

![](https://puu.sh/v71Ss/e44a9c5c81.png)

**Comment by Tunous** [comment]
It's in development version not released yet.

**Comment by Bluscream** [comment]
wow xD

**Comment by Bluscream** [comment]
When will it get rekl

**Comment by Tunous** [comment]
About release ask @maniac103 but you can get the "pre-release" by [manually compiling](https://github.com/slapperwan/gh4a#how-to-build-octodroid) the app.

**Comment by slapperwan** [comment]
@Bluscream v4.1.1 released in play store and has this feature.

**Comment by Bluscream** [comment]
Thanks
