### ISSUE TITLE
App crashed because of specific MD tag 

### ISSUE THREAD

**Issue by sharkykh** [slapperwan/gh4a#567]
Hey,

Viewed a pull request in which there was a comment I posted, that had this markdown tag in it: `2. >Quote`.
Every time I went into that pull request and scrolled to that comment, the app freezed just before the comment, then crashed.

I had a hunch that it was that tag that caused it, because it looked kinda "funky" on Github.
I was able to work around it by editing my comment to:
```
2.
>Quote
```

I hope this information describes the issue in the best possible way.
Thank you for the great app!

**Comment by maniac103** [comment]
You can't link to that PR by chance, can you? I assume it crashed when you didn't have the list item + quote in a code block, right?

**Comment by sharkykh** [comment]
Don't want to actually link this so I'll put it on a code block: `https://github.com/SickRage/SickRage/pull/3368#issuecomment-290843078`.

Indeed, it crashed when it was normally used, a numbered list item, followed by a quote on the same line, no code block.
I refrained from doing it here to not crash it again.
