### ISSUE TITLE
Milestone filtration doesn't work for non-English milestones

### ISSUE THREAD

**Issue by rugabarbo** [slapperwan/gh4a#568]
I don't see any issues under my milestone filters...

**Comment by maniac103** [comment]
Dupe of #428 ... this issue should be fixed in 4.0.5 though, are you using an oder version?

**Comment by rugabarbo** [comment]
I'm using 4.0.5
Not sure this is dupe of #428.

**Comment by maniac103** [comment]
Hmm, so what exactly are you doing? Some repo -> issue list -> filter by milestone -> select a milestone -> resulting list is empty?

**Comment by rugabarbo** [comment]
> Some repo -> issue list -> filter by milestone -> select a milestone -> resulting list is empty?

Yes exactly.

> Not sure this is dupe of #428.

I mean #428 is about comment button... While this issue is about milestone filtration.
So I'm a bit confused.

**Comment by maniac103** [comment]
Oops, typo: I meant #528.

**Comment by rugabarbo** [comment]
Yes, that's right. #528 is dupe of this issue.

I see that #528 has been fixed in 4.0.5 version. But I have this version installed and there is still a bug. How can I help localize the problem?

**Comment by rugabarbo** [comment]
Perhaps it will be useful: I'm watching the filtering bug in the **private** repository.

**Comment by Tunous** [comment]
Works for me both in private and public repositories.

**Comment by rugabarbo** [comment]
I think I found the source of the problem. For the milestone «English» filtering works fine, but for the milestone «Русский» doesn't (this is Russian language).

**Comment by rugabarbo** [comment]
Thank you a lot. Now it works fine (4.0.6)
