### ISSUE TITLE
Adding change requests to the news feed

### ISSUE THREAD

**Issue by geekyd** [slapperwan/gh4a#569]
I have been using the application since 2 months. Its a great application. One feature that we should have is getting information about change requests in the news feed as well as the PR fragment. I recently missed a change request due to not receiving a notification.

**Comment by maniac103** [comment]
Unless I am misunderstanding what a change request is, this is a dupe of #391, right?

**Comment by geekyd** [comment]
@maniac103 Yes its is duplicate close this. Thanks
