### ISSUE TITLE
Trending repository without description displays "null"

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#576]
![example](http://i.imgur.com/pN8V5OW.png)

**Comment by maniac103** [comment]
Interesting. In the JSON data it's correct (null, not 'null'), so something must be off in the processing.

**Comment by maniac103** [comment]
Ah: https://android.googlesource.com/platform/dalvik/+/f2f7880a40aed1c8d9c27db49226e47396556aac/libcore/json/src/main/java/org/json/JSONObject.java#97

-> should check with isNull()
