### ISSUE TITLE
reply to a comment doesn't nest like it does in the web interface

### ISSUE THREAD

**Issue by PatrickvL** [slapperwan/gh4a#582]

**Comment by Tunous** [comment]
Got an example?

**Comment by PatrickvL** [comment]
Each and every time I've used the Reply button from within OctoDroid here, but instead it became separate comments​ : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/367

**Comment by maniac103** [comment]
https://developer.github.com/v3/repos/comments/#create-a-commit-comment

I don't see any way to specify a reference to another commit there?

**Comment by maniac103** [comment]
Hmm, looks like it's possible with PR comments: https://developer.github.com/v3/pulls/comments/#create-a-comment (see 'alternative input' section)

**Comment by maniac103** [comment]
This should be reasonably easy to do. I'll look into it.

**Comment by PatrickvL** [comment]
Now that was quick! Thanks! Any idea how soon this lands in Google play so people can update OctoDroid the usual way?

**Comment by maniac103** [comment]
Ultimately it depends on @slapperwan, but I guess a soon-ish release totally makes sense for the web flow based oauth alone. I wanted to land the comment bottom sheet PR first, but it's probably better not to delay all the other new features for it.

@Tunous @slapperwan Thoughts on this?

**Comment by Tunous** [comment]
Yes, I think that earlier release is a good idea. Comment bottom sheet still needs some more bug fixes and I feel like a few more will pop up. This feature deserves its own release anyway ;) It could also come with some sort of drafts system that I'm thinking about implementing. _I'll talk about this more in a new issue once I finish my base idea._ 

Just should merge #580 before releasing, and I also think that the mark all as read button from notifications screen should disappear once everything is marked read.

**Comment by slapperwan** [comment]
I'm currently testing from Master.  Any PR that need to be merged?
