### ISSUE TITLE
Emoji in repo description not being rendered

### ISSUE THREAD

**Issue by kshvmdn** [slapperwan/gh4a#584]
If a repo has an emoji in it's description, the emoji isn't rendered. Would be cool if we saw the actual emoji instead of just the text value, not sure if it's possible to do anything about this though.

Examples:
- [nodejs/node](https://github.com/nodejs/node)
- [avajs/ava](https://github.com/avajs/ava)

**Comment by kshvmdn** [comment]
Actually, looks like this is only happening for certain emojis. For example, the :popcorn: from [daneden/animate.css](https://github.com/daneden/animate.css) is rendering fine.

**Comment by maniac103** [comment]
Pretty sure 'blame Github' is the correct answer here. They provide pre-rendered HTML for the descriptions, if emojis aren't correctly replaced by them there, there's not much we can do. I'll verify that's the case though.

**Comment by Tunous** [comment]
I can confirm this. The popcorn example is returned directly as an emoji in response while the rest are strings. 

Maybe there is some library that parses these GitHub emoji strings and renders them? That would be one way to solve this.

**Comment by kshvmdn** [comment]
Looks like this might be of some use here - https://github.com/vdurmont/emoji-java.

**Comment by Tunous** [comment]
It could also be used in commit messages as they aren't rendered here too.
