### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by thermatk** [slapperwan/gh4a#588]
Recent versions of the source can't be built by F-Droid anymore. There are three steps to be done to make it possible again:

- [x] eliminate bad repositories (https://github.com/slapperwan/gh4a/pull/587)
- [x] make a flavor which builds successfully without fabric. I've tried, shouldn't be hard, can do that
- [x] the egit github api jar: maybe merge the library into the main project? If you're not planning to send your patches upstream, this will be easier for you too.
- [x] api keys: providing some separate keys in the specific flavor should work fine

**Comment by maniac103** [comment]
I've thought about inlining the API a couple of times already. The only reason I haven't done it yet is that I saw no way to preserve history, and I was too lazy to do the Maven -> Gradle conversion. Both aren't strong reasons though, so I'd gladly accept a PR importing the current API library source here.

**Comment by maniac103** [comment]
Just did the import - was less of an issue than I thought :)

**Comment by thermatk** [comment]
#589

**Comment by thermatk** [comment]
Sorry for being silent so long, I have exams. Please make a release or provide some ETA for it, so I can edit the metadata and enable tag auto-updates 
👍

**Comment by mimi89999** [comment]
@maniac103 Can you please tag release v4.1.2? https://gitlab.com/fdroid/fdroiddata/merge_requests/2269#note_32980125

**Comment by maniac103** [comment]
@mimi89999 Done: https://github.com/slapperwan/gh4a/tree/v4.1.2

**Comment by Tunous** [comment]
Shouldn't it be a release which contains commits with changes for F-Droid?

**Comment by thermatk** [comment]
@Tunous exactly, that's why I tagged it with WIP on F-Droid and was just waiting for next release.
@maniac103 @mimi89999 this 4.1.2 release is too old and makes no sense

**Comment by maniac103** [comment]
Well, adding the tag for it makes sense in any case. Only @slapperwan can do new releases though.

**Comment by mimi89999** [comment]
When can we expect 4.1.3?

**Comment by Tunous** [comment]
That's question to @slapperwan.

Myself I think there is enough new stuff already to update unless we are waiting to figure out fixes for #629 and #649.

**Comment by slapperwan** [comment]
Ok will release 4.1.3 on 27 Aug.

**Comment by thermatk** [comment]
Thank you all, we finally did it 👍

**Comment by licaon-kter** [comment]
@slapperwan Thoughts? https://f-droid.org/wiki/page/com.gh4a/lastbuild_61

**Comment by maniac103** [comment]
The build target is now named 'assembleRelease', no longer 'assembleFossRelease'.

**Comment by licaon-kter** [comment]
Thanks
https://gitlab.com/fdroid/fdroiddata/commit/c720ed7f075954d699e9280f3297c2fe182a251a
