### ISSUE TITLE
Incorrect "Reopen" button on PR

### ISSUE THREAD

**Issue by sharkykh** [slapperwan/gh4a#590]
I searched for a bit but couldn't find an issue about this.

I opened a pull request on a repo to which I have write access,
the pull request is from a branch on the repo (not a fork) to the develop branch (not the default branch).

The image on the top shows that I have a button to reopen the PR, even though it is still open and unmerged, as you can see from the green color.
The image on the bottom shows the options I have when I click the three dots -
I have the "Close" option.
It seems like it shouldn't be this way.
Instead, it should **only show** "Reopen" when the PR was **closed unmerged**.

Link to PR: `https://github.com/SickRage/SickRage/pull/3588`

P.S.
**The organization has not yet allowed the OctoDroid OAuth2 application [(full) access to the information](https://cloud.githubusercontent.com/assets/10238474/25366770/8749e9d6-297a-11e7-84d9-5289e0432a80.png)**,
so maybe that has something to do with this behavior?

<img src="https://cloud.githubusercontent.com/assets/10238474/25366447/5ddf121c-2978-11e7-9eaf-4fb417378ce0.jpg" width="35%" title="Click for full size" />

**Comment by maniac103** [comment]
It looks like it's a general problem. I'll look into it, should be a trivial fix.

**Comment by maniac103** [comment]
Note to self: https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/activities/PullRequestActivity.java ... add a `|| !isClosed` there.
