### ISSUE TITLE
Laggy scroll

### ISSUE THREAD

**Issue by Archimedyz** [slapperwan/gh4a#591]
First off, great app!

I was looking at a user profile, and it seems to be somewhat laggy/jerky when scrolling. I think it might have to do with hiding the top fragment when scrolling down. 

Example, flicking to scroll won't work, it will just hide the top frightened and then sit there. Subsequent scrolling is fine.

**Comment by Tunous** [comment]
I'm also experiencing this issue in about repository screen.

**Comment by maniac103** [comment]
What 'top fragment' are you referring to? The user profile page is a single fragment.
FWIW, I've also seen this, but I'm pretty sure it's touch event handling related. Try the fling at the very left or right edge of the view, it'll work fine there.

**Comment by Archimedyz** [comment]
I can no longer reproduce the issue. I can't recall at this point exactly hich screen it was, but if I do, I'll post a screenshot and re-open this ticket.

**Comment by Tunous** [comment]
I can still experience this sometimes when scrolling in repository info screen.

**Comment by Tunous** [comment]
This is a bug in NestedScrollView: https://issuetracker.google.com/issues/37138918.
I tried the workaround from https://issuetracker.google.com/issues/37138918#comment8 and it works but as mentioned that's only for API 21+.

Should reopen.

**Comment by Tunous** [comment]
I've tested it with the latest SDK and the issue has been fixed here. (See #658)
