### ISSUE TITLE
Show saved replies when responding to issues/PRs

### ISSUE THREAD

**Issue by mmoayyed** [slapperwan/gh4a#592]
Quite simply, it would be superb if the user's saved replies were pulled in by the app and made available when responding to issues or pull requests.

**Comment by maniac103** [comment]
What saved replies are you referring to exactly?

**Comment by mmoayyed** [comment]
![image](https://cloud.githubusercontent.com/assets/1205228/25485706/a79a16b2-2b13-11e7-994c-d914564b466a.png)

**Comment by maniac103** [comment]
Just asked Github support - there's no API for this, at least currently :(

**Comment by mmoayyed** [comment]
That is unfortunate. Thank you for keeping track of this.
