### ISSUE TITLE
Repository attribute text doesn't fit

### ISSUE THREAD

**Issue by kshvmdn** [slapperwan/gh4a#596]
The repo attributes for a private fork are too long, so the size attribute text overflows.

In this case (both private and fork), I think it'd be appropriate to remove the "Private" and "Fork" text to make everything fit.

Screenshot:

![](https://i.imgur.com/8ZxWpGo_d.jpg?maxwidth=640&shape=thumb&fidelity=high)

**Comment by kshvmdn** [comment]
It could also be fixed by reducing the padding between each attribute and/or stacking attributes if they don't fit.

**Comment by Tunous** [comment]
Scrolling is the easiest solution. Stacking would be nice but I'm not sure how easy is that to do in Android.

Reducing padding wouldn't fix that in all situations and hiding labels would make these icons hard to identify.

**Comment by maniac103** [comment]
Stacking should be fairly easy by using a FlowLayout. I think we're using this elsewhere in the code already.

**Comment by Tunous** [comment]
I didn't find `FlowLayout` anywhere in the code so I went for the scrollable solution.

**Comment by maniac103** [comment]
It's this one: https://github.com/ApmeM/android-flowlayout ... I used to use it for the label dots in the issue list, but forgot I replaced it with a custom view.
