### ISSUE TITLE
Bookmarks reordering

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#601]

**Comment by ildar** [comment]
This is still the issue, please reopen 😁
Seriously, the new bookmark gets to the tail of the list. To compare, the neighbor Starred list works in opposite way.
Would you make the new entry to the top? Thanks.

**Comment by maniac103** [comment]
This is closed because the feature this report is about (reordering of bookmarks) is already implemented...
I'll see why stars works differently, probably should pass a sort order argument to Github API.

**Comment by ildar** [comment]
Oh! I thought Bookmarks is a totally local feature. Want to look out for it
on the site...

**Comment by smichel17** [comment]
Bookmarks are local AFAIK. I interpreted the comment above to be talking about stars.

**Comment by maniac103** [comment]
> I interpreted the comment above to be talking about stars.

Exactly that. Bookmarks are local, stars are remote.

**Comment by ildar** [comment]
Then maybe new bookmark -> to the top?

**Comment by smichel17** [comment]
@ildar — @maniac103 wasn't shooting down your suggestion, they were pointing out this issue is closed because it's about a completely different functionality (the ability to change the order of existing bookmarks). Feel free to open a new issue :)
