### ISSUE TITLE
Viewing profile of "Bot" shows error page

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#603]
Link: https://github.com/fman-users/fman/issues/4

API link: https://api.github.com/repos/fman-users/fman/issues/4/events

Trying to view profile of the fman-issues-bot from comments in the linked issue displays an error page. In browser I am redirected to https://github.com/integration/fman-issues-bot for that bot. 
(should handle integration/ links differently)

Not sure what we can do here. Perhaps this needs a new activity for displaying integration profiles?

**Comment by maniac103** [comment]
Probably not, I guess. To me, this looks like an URL encoding problem. The 'url' field of the user is set to https://api.github.com/users/fman-issues-bot%5Bbot%5D - which works - but the bindings do not seem to do that encoding ... the thrown exception's message is

`05-20 18:38:20.315 E/Gh4a    (27885): Illegal character in path at index 44: https://api.github.com/users/fman-issues-bot[bot]`

**Comment by maniac103** [comment]
We'll probably need to check all user related binding methods for this issue.
