### ISSUE TITLE
Spellchecker color too dark

### ISSUE THREAD

**Issue by sharkykh** [slapperwan/gh4a#604]
When clicking on a mispelled word (a word with a red underline),
the spellchecker's suggestions are barely visible because the color is too dark (at least on the dark theme)

![20170522_131103](https://cloud.githubusercontent.com/assets/10238474/26303478/7b4de3d6-3ef0-11e7-8e43-73ea2afe26c0.png)

**Comment by maniac103** [comment]
I can't reproduce this:

![screenshot_20170522-131851](https://cloud.githubusercontent.com/assets/781373/26305850/49ef37f8-3ef1-11e7-9fee-9c3cf31f485e.png)

@Tunous Can you repro?

**Comment by Tunous** [comment]
Nope, it looks good here.

**Comment by sharkykh** [comment]
That's weird.
I also tried force-quitting the app (from phone settings),
and to toggle the theme to light (which works fine) then back to dark, but it still looks the same.

Is there anything I can provide you with that may point to why this is happening only for me?

By the way, it's Android 7.0 on a Samsung Galaxy S7

**Comment by maniac103** [comment]
No, if anything, that's a manufacturer (software) screwup. I'll try to repro with my wife's Galaxy S2 Tab, which is also running Android 7.0.

**Comment by sharkykh** [comment]
@maniac103 
What are the two options in you have below the suggestions in your image?
**Add to dictionary** and **delete**?
Could the fact that I have different options be connected?

**Comment by maniac103** [comment]
Yes, it's 'add to dictionary' and 'delete'. I'm not entirely sure what process displays that popup, but did you try whether the issue persists with a different keyboard (say e.g. Gboard)?

**Comment by sharkykh** [comment]
@maniac103 
I couldn't even get the suggestions popup with Gboard, nor with SwiftKey. Just the keyboard predictions row...

**Comment by sharkykh** [comment]
Closing as I don't think there's anything you can do about it.
