### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#605]
I don't know what are the plans but it's worth considering switching to this new API.
From [this blog post](https://github.com/blog/2359-introducing-github-marketplace-and-more-tools-to-customize-your-workflow): "The GitHub GraphQL API is fresh out of its Early Access program."

[Documentation](https://developer.github.com/v4)

**Comment by maniac103** [comment]
I don't have any plans for it yet. It's certainly pretty cool, but also needs a complete rethinking of the bindings and therefore the app.

If we're going to start to use it, I'd suggest for implementing stuff that isn't possible in the v3 API to get an initial feeling. At some point we're probably going to add a Java abstraction for the various objects, and with progress of that implementation, we probably could convert more and more parts of the app.

I fear the full conversion will need much more time than at least I have, though :-/
