### ISSUE TITLE
New organization not shown

### ISSUE THREAD

**Issue by Crease29** [slapperwan/gh4a#612]
I have an issue with a new organization I've created. It's not shown in the app. I have also deleted the Cache of the app and all data so I had to sign in again.

**Comment by kshvmdn** [comment]
You have to enable third-party application access on a per-organization basis now, do that here - https://github.com/organizations/{ORG_NAME}/settings/oauth_application_policy.

If I recall correctly, I had to login again after enabling that.

**Comment by Crease29** [comment]
Thank you very much! That worked :)
