### ISSUE TITLE
IssueActivity doesn't remember state of its fragments

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#616]
From https://github.com/slapperwan/gh4a/pull/536#issuecomment-303726440.

`IssueActivity` always creates new fragments instead of restoring them which results in a loss of their instance state.

**Comment by maniac103** [comment]
What's triggering the recreation, IOW what's triggering IssueActivity.showUiifDone() to be called? Data being redelivered for the loaders? If that's the problem we'll likely have to re-think how to pass data into the fragments, as it won't affect only the IssueActivity, but also all pager activities (they'll either create new fragments or won't be updated correctly when new data arrives, as the loaded data is passed into the fragments). In case you're wondering why I'm passing loaded data into fragments, the point of that was to avoid redundant data loads - e.g. for PRs, the loaded pull request is needed for all 3 page fragments + the activity itself.

What's the actual high level issue here - what kind of state is getting lost?

**Comment by Tunous** [comment]
Mostly I mean the recreation which happens when rotating screen. 

The high level issue is losing scroll position and also the comment text in editor.

**Comment by Tunous** [comment]
Btw, the issue is not happening for pull requests, here the scroll position and text is correctly restored. It's just the `IssueActivity` that's incorrect.

**Comment by maniac103** [comment]
I figured it doesn't happen for PRs, as I'm pretty sure fragments aren't recreated there. From first look though it looks like they aren't recreated on refresh either, though, which means the PR data isn't updated. I'll verify this.

**Comment by Tunous** [comment]
Yeah it doesn't reload PR data.
