### ISSUE TITLE
Crash on PR review comment link to a grayed out file

### ISSUE THREAD

**Issue by sharkykh** [slapperwan/gh4a#619]
The app crashes when clicking a link to a review comment in the conversation tab of a pull request,
this happens when the file is grayed out on the files tab (when the diff is too big?)

By clicking one of these links in the conversation tab, while the file is grayed out in the files tab...
The app tries to load, and crashes after a few seconds.

<img src="https://cloud.githubusercontent.com/assets/10238474/26791064/9fdb2a0e-4a1e-11e7-8ab2-a63bec12a5f2.png" width="49%" /> <img src="https://cloud.githubusercontent.com/assets/10238474/26791065/9fddb12a-4a1e-11e7-8376-7a8c94fbc487.png" width="49%" />

**Comment by maniac103** [comment]
Is this PR publically accessible?

**Comment by sharkykh** [comment]
@maniac103 
I keep forgetting you need this to debug...
 `https://github.com/pymedusa/Medusa/pull/2816`

**Comment by maniac103** [comment]
https://github.com/pymedusa/Medusa/pull/2816

**Comment by maniac103** [comment]
Ah, now I finally know how to reproduce this Play Store reported crash :) Will fix this.

**Comment by sharkykh** [comment]
Happy to help. Thank you!
