### ISSUE TITLE
Deprecated Module

### ISSUE THREAD

**Issue by rhonyabdullah** [slapperwan/gh4a#625]
I found that this project implement "github-api" which is cloned module, after take a minute exploring i found the api module are coming from [this](https://github.com/kohsuke/github-api) but it seems that the whole module is changed, is this "local" github-api module still useable?
And please consider almost all of the pojo class implement seriazable rather than with parcelable or [parceler](parceler.org)
@slapperwan @maniac103

**Comment by maniac103** [comment]
It doesn't have to do anything with the project, but instead is a copy/import of https://github.com/maniac103/egit-github ... that's why it implements Serializable, not Parcelable: it started as a generic Java binding for Github.

And yes, it's still usable (and used) - why shouldn't it be?

**Comment by rhonyabdullah** [comment]
Whoa, i'm sorry, misunderstanding about the api because read this "compile project(':github-api')" line on build.gradle make me assume that this project use [this github-api](http://gradleplease.appspot.com/#github-api) module after exploring throught gradle please.
