### ISSUE TITLE
Scroll to highlighted comment in file scrolls to line

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#631]
When entering diff viewer with a highlighted file the scroll is moved to the line corresponding to the comment instead of the comment itself. This is problematic when there are many comments on a single line. In that case, the highlighted comment is not even visible and manual scrolling is required to see it.

**Comment by maniac103** [comment]
Got an example for this?

**Comment by Tunous** [comment]
Ohh nvm... I accidentally added an initial line when creating intent and assumed that it was a bug outside of the reviews branch. It works correctly.
