### ISSUE TITLE
Github releases sort options?

### ISSUE THREAD

**Issue by mmoayyed** [slapperwan/gh4a#637]
It seems like the releases page is sorted using created date. Could you please add additional options so releases can sorted alphabetically? This is useful in cases where releases are tracked as version numbers and you'd want to see the most recent version on top. 

Thank you for this most excellent app.

**Comment by maniac103** [comment]
Doesn't the current sort order (creation date descending) provide just that - display the most recent version on top?

In general, changing the sort order is not a big deal, but alphabetical sorting doesn't provide the properties you're interested in either. Think version numbers like 3.1, 3.2, ..., 3.9, 3.10, 3.11. With alphabetical sorting you'll get 3.1, 3.10, 3.11, 3.2, ..., 3.9. There are solutions to that (e.g. http://www.davekoelle.com/alphanum.html), but it's not entirely trivial.

What does Github's web UI do here?

**Comment by mmoayyed** [comment]
I dont really see or cannot find the option for sort order. The releases page simply lists things without any additional knobs. This is with v4.1.1, seen under About tab where at the bottom there is "releases" link under "Other Information". Going into that screen, there are no additional options. 

Github sorts things by creation/update date:
https://github.com/apereo/cas/releases

I do agree that literal alphabetical sort does not help. Maybe options could be: creation-date (if it does not exist) and a sort-by-version where you could see the following order: `3.1...3.2...3.9..3.10..3.11`.

**Comment by Fs00** [comment]
I've just stumbled upon this old issue and I think there is no more reason to keep it open.
Now the app sorts releases in the same way as the GitHub web UI does (see #1191), consistently displaying the most recent versions at the top.

**Comment by maniac103** [comment]
Agreed.
