### ISSUE TITLE
Menu option to copy repository link

### ISSUE THREAD

**Issue by mmoayyed** [slapperwan/gh4a#638]
The menu option for the individual repository project does not have an option to allow one to copy the project's link to clipboard. This would be a very good nice-to-have.

**Comment by kshvmdn** [comment]
The "share" option opens a dialogue that allows you to copy the link.

**Comment by maniac103** [comment]
What @kshvmdn said ;)

**Comment by mmoayyed** [comment]
Thank you for the hint.
