### ISSUE TITLE
Editing only issue labels/milestones displays edited text in header

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#641]
![spectacle zu3326](https://user-images.githubusercontent.com/5156340/27339148-4bd01fd6-55d7-11e7-9cde-bbb2ce9c0491.png)

The underlined text is what appears on issues even though I didn't modify issue's body or title. It doesn't appear when adding labels from the web interface.

**Comment by maniac103** [comment]
This likely can be fixed by not calling the setters for items that weren't actually changed here: https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/activities/IssueEditActivity.java#L608

**Comment by smichel17** [comment]
I think there's two parts to this issue. Part 1 is closed by #700. Part 2 is about ui changes (I also like how fasthub does this part). Maybe copy that section of your comment into a new issue?

**Comment by Tunous** [comment]
@smichel17 Yeah, added as #706

**Comment by smichel17** [comment]
This is still happening in v4.2.1. [Example](https://github.com/LibreShift/red-moon/issues/203)
