### ISSUE TITLE
Update F-Droid link

### ISSUE THREAD

**Issue by Kvaibhav01** [slapperwan/gh4a#646]
Please update the dead F-Droid app link. Here's the link: https://f-droid.org/packages/com.gh4a/

**Comment by Tunous** [comment]
Not sure why you decided to close your pull request but I've merged it manually as fa602bf41785b942dd7185a7bb35ee62beef4a9f.

**Comment by Kvaibhav01** [comment]
Oh, 😆. Sorry about that and thanks for the merge! 😃
