### ISSUE TITLE
Unable to merge pull request

### ISSUE THREAD

**Issue by mmoayyed** [slapperwan/gh4a#649]
![screenshot_20170714-072001](https://user-images.githubusercontent.com/1205228/28217240-54f390ee-6869-11e7-8c6c-80a715372230.png)

**Comment by mmoayyed** [comment]
As you can see, every checkmark is green, and this happens with the latest version of the software. In fact I think I cant merge ANY pull requests on ANY repository and it's unclear why.

**Comment by maniac103** [comment]
I guess this is due to an error returned by the server ... can you collect & post logcat after such an attempt?

**Comment by mmoayyed** [comment]
I would love to, but that would be way beyond my android-dev skills. Does the app itself not have a log viewer? If not, what set of steps need I follow to produce log output?

**Comment by maniac103** [comment]
It doesn't have something like that (yet - see #629). On a rooted device you can use an app like MatLog or CatLog to review and save the log. On a non-rooted device, you'd have to install ADB on your PC (tutorials for a minimal installation can be found via Google, I believe; if you use Linux installing the android-tools package should be sufficient) and the log can be pulled by running 'adb logcat' afterwards.

**Comment by maniac103** [comment]
From my recent experience it seems likely that this is due to Octodroid not being authorized to have access to the respective organization's repos. @mmoayyed Can you please check whether that's the case?
