### ISSUE TITLE
Show DMCA page

### ISSUE THREAD

**Issue by Kriskras99** [slapperwan/gh4a#651]
If a repository is taken down by a DMCA notice, OctoDroid reports connectivity issues instead of the DMCA notice which can be really confusing. Example:
https://github.com/sickrage/sickrage

**Comment by sharkykh** [comment]
I second that.

BTW, this info is provided by the API endpoint: https://api.github.com/repos/SickRage/SickRage
```json
{
  "message": "Repository access blocked",
  "block": {
    "reason": "dmca",
    "created_at": "2017-07-19T22:34:13Z",
    "html_url": "https://github.com/github/dmca/blob/master/2017/2017-07-17-SiCKRAGE.md"
  }
}
```

**Comment by Bluscream** [comment]
Ths
