### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by deephole** [slapperwan/gh4a#659]
./gradlew clean build failed with  following message:
./gradlew clean build
Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/dhole/.gradle/wrapper/dists/gradle-3.3-all/2n0i7hqatcbtk57vvql575dbap/gradle-3.3-all.zip to /Users/dhole/.gradle/wrapper/dists/gradle-3.3-all/2n0i7hqatcbtk57vvql575dbap
Set executable permissions for: /Users/dhole/.gradle/wrapper/dists/gradle-3.3-all/2n0i7hqatcbtk57vvql575dbap/gradle-3.3/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://maven.fabric.io/public/io/fabric/tools/gradle/1.24.0/gradle-1.24.0.pom
Download https://maven.fabric.io/public/io/fabric/tools/gradle/1.24.0/gradle-1.24.0.jar
Checking the license for package Android SDK Platform 24 in /Users/dhole/Library/Android/sdk/licenses
License for package Android SDK Platform 24 accepted.
Preparing "Install Android SDK Platform 24 (revision: 2)".
"Install Android SDK Platform 24 (revision: 2)" ready.
Finishing "Install Android SDK Platform 24 (revision: 2)"
Installing Android SDK Platform 24 in /Users/dhole/Library/Android/sdk/platforms/android-24
"Install Android SDK Platform 24 (revision: 2)" complete.
"Install Android SDK Platform 24 (revision: 2)" finished.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/dhole/Desktop/gh4a-master/app/build.gradle' line: 48

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method buildConfigField() for arguments [String, CLIENT_ID, BuildType_Decorated{name=ClientId, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}] on BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=/Users/dhole/.android/debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=/Users/dhole/.android/debug.keystore, v1SigningEnabled=true, v2SigningEnabled=true}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by Tunous** [comment]
Make sure to follow the steps described in [How to Build OctoDroid](https://github.com/slapperwan/gh4a#how-to-build-octodroid).

As far as I can tell the error means that ClientId is missing.

**Comment by Tunous** [comment]
Or it might be the same problem as here https://stackoverflow.com/q/45236098. @deephole can you confirm that ClientId is not missing?
