### ISSUE TITLE
Some links in notifications open in web browser

### ISSUE THREAD

**Issue by sharkykh** [slapperwan/gh4a#660]
I'm currently using the [`reviews`](https://github.com/slapperwan/gh4a/tree/reviews) branch, not sure if it's related.

For some reason, when I click a notification of a pull request, or a notification of a commit in the Notifications tab, it opens the link in the web browser instead of in-app.
It works perfectly fine with notifications of issues (opens in-app)
[**Screenshot**](https://user-images.githubusercontent.com/10238474/29196698-c3b567c4-7e3e-11e7-9331-10e588f294d1.jpg)

FTR, My app defaults *are* set to OctoDroid (to open `gist.github.com` & `github.com` links using the app)

**Comment by Tunous** [comment]
I've fixed this for pull requests. Not sure about commits (last item in your screenshot) as I don't have any notifications of this type currently.
