### ISSUE TITLE
BrowseFilter doesn't exit after handling some links

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#667]
https://github.com/slapperwan/gh4a/commits/master causes this every time.

**Comment by Tunous** [comment]
Most likely caused by https://github.com/slapperwan/gh4a/commit/7a36f865c6cfcd392d49f67880abcc4ddc74aa39
There must be an error in this logic that I've missed.

**Comment by sharkykh** [comment]
The exact same thing happens when clicking a bookmark (linking to a repo's non-default branch).
I was about to post about it, but I guess it's the same issue.
