### ISSUE TITLE
Toolbar doesn't hide during scroll in IssueActivity

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#671]
It only hides/expands after finger is released.

**Comment by Tunous** [comment]
This is slowly getting really annoying. Sadly I can't find a solution. I would really appreciate if someone else can look at this. (I can record a gif if you don't know what I mean by this issue)

All I know right now is that the issue is caused by internal changes in support library after changing to version 26. (Version 25 worked correctly) 

EDIT: It also happens when you fling in bottom sheet when previously scrolling here locked toolbar at collapsed state.

**Comment by maniac103** [comment]
I can repro the problem - but if it is caused by support library changes, wouldn't downgrading them to 25 and writing a support library bug report be the best idea for now?
I'll also look at it and see if I can pinpoint a root cause.

**Comment by Tunous** [comment]
Perhaps, but then we'll have to lower target API and we'll reintroduce #591. Also would need to revert the `findViewById` changes.

**Comment by maniac103** [comment]
OK, #591 alone convinced me to not do it ;-) I'll check it.
