### ISSUE TITLE
Custom accent color

### ISSUE THREAD

**Issue by dimqua** [slapperwan/gh4a#683]
Please add a possibility to set custom accent color.

**Comment by maniac103** [comment]
No, sorry, this won't happen. Octodroid's color is green to match the icon.

**Comment by cdysthe** [comment]
I guess we will just have to accept the decision whether we like green or not. I do not use the default icon, so a match in that regard doesn't matter.

**Comment by smichel17** [comment]
You could also download the source and change the hard coded colors; that's is as simple as modifying the values in the [colors file](https://github.com/slapperwan/gh4a/blob/master/app/src/main/res/values/colors.xml), then building the app. Even if you have no development experience at all, building is pretty easy if you do everything through Android Studio.

I know that's some extra maintenance for you (you have to pull updates, re-apply your color changes, and build again each time you want an update), but maybe worth it if the changed color is that important to you.
