### ISSUE TITLE
Can't load the corresponding content for filter/order setting

### ISSUE THREAD

**Issue by WanderMax** [slapperwan/gh4a#684]
I choose the start page : My repositories, and set filter "Starred" and sort order "Most recently pushed".
However, when I open the app, the loaded content is always "My repositories" with one strange order.
In previous version, app can load the "Starred" content with "Most recently pushed" order.
Thanks.

**Comment by Tunous** [comment]
Same issue as #746 ?

**Comment by maniac103** [comment]
It's extremely likely, yes.
