### ISSUE TITLE
Show user tags in PR/issue comments

### ISSUE THREAD

**Issue by kshvmdn** [slapperwan/gh4a#690]
Not sure if this data is available, but I think it'd be cool if we saw user tags in PR and issue comments.

By tags I'm referring to the text that appears at the top-right of comments in the web UI (only on the desktop UI, not mobile as far as I know) with `"owner"`, `"member"`, `"collaborator"`, `"contributor"`, etc.

**Comment by kshvmdn** [comment]
For example:

![](http://i.imgur.com/QvFP50d.png)

**Comment by sharkykh** [comment]
It seems like each comment has an attribute named `author_association` that holds this the user's title, so my guess is that it is possible.

**Comment by maniac103** [comment]
Yeah, but I like how this field and its possible values are documented: https://developer.github.com/v3/issues/comments/ ... NOT.

**Comment by Tunous** [comment]
Looks like `author_association` is not always correct. For this [pull request](https://github.com/slapperwan/gh4a/pull/655) it says "NONE" while GitHub shows "First-time contributor". For my pull requests, it correctly shows "COLLABORATOR".

@maniac103 Maybe ask GitHub about this?
