### ISSUE TITLE
Relocate Starred and Watched repos

### ISSUE THREAD

**Issue by smichel17** [slapperwan/gh4a#696]
On the `My repositories` screen, the `Starred` and `Watched` filter categories feel a bit out of place, since they alone are not subsets of `All`. 

I think it would make sense to move `Watched` under Notifications, as its own tab (or possibly its own screen via a menu item). I seldom want to go look through the list of what I'm watching, unless I want to change that list -- in the context of notifications, and this mirrors the github interface, so we don't need to make people re-learn where it is.

Then, `Starred` can go under `Bookmarks`, which serves basically the same purpose, anyway. There could either be two tabs, or they could be in the same list, with bookmarks appearing on top.

**Comment by Tunous** [comment]
See #578 and #624

**Comment by maniac103** [comment]
Let's continue in #578 ... I'll copy your comment there.

**Comment by landry314** [comment]
But you never dealt with Watched...
