### ISSUE TITLE
Add project logo next to repo heading in notifications view

### ISSUE THREAD

**Issue by jancborchardt** [slapperwan/gh4a#702]
As an additional visual indicator, it would be great if left next to the repo name heading the correaponding logo of the organization would be shown.

That allows you to quickly scan the list without reading the title itself.

**Comment by Tunous** [comment]
![screenshot_1504970614](https://user-images.githubusercontent.com/5156340/30241455-d2618bca-9583-11e7-9af3-2c5f4e53a847.png)

*Alpha is updated just like for the header based on read/unread state*

**Comment by jancborchardt** [comment]
@Tunous perfect! :)
