### ISSUE TITLE
Invoke sidebar by swiping from any view

### ISSUE THREAD

**Issue by jancborchardt** [slapperwan/gh4a#705]
If you are deep in a project and just want to switch back to a different section, you have to go back-back-back all the way.

A nicer way would be if a swipe from the left edge opens the left sidebar, no matter which view one is in.

**Comment by Tunous** [comment]
Duplicate of #333 (@maniac103 Might want to reopen if we want to reconsider this)

**Comment by landry314** [comment]
This is huge problem for the app. The main navigation drawer should be persistent. 100%.
