### ISSUE TITLE
Reame file content fetch

### ISSUE THREAD

**Issue by MattiaPrimavera** [slapperwan/gh4a#709]
I'm sorry for the question, but I'm not sure I got the reason why the html readme file is not simply loaded into a **WebView**, why exactly is the **TextView** preferred here?

**Comment by Tunous** [comment]
Are you talking about the readme in About repository section? This one I believe is a TextView because there would be scrolling issues when using WebView. Nesting scrollable views is generally a bad idea.

**Comment by MattiaPrimavera** [comment]
About the **RepositoryFragment**, showing summary info on the repository plus the **Readme content**

**Comment by Tunous** [comment]
That's the one.

**Comment by maniac103** [comment]
@Tunous explanation is spot on. Additionally we can't scroll horizontally.
