### ISSUE TITLE
Use retrolambda

### ISSUE THREAD

**Issue by MattiaPrimavera** [slapperwan/gh4a#712]
Lessen more boilerplate code ;)

**Comment by Tunous** [comment]
I would be against this. Starting with Android Studio 3 some of Java 8 features become available for use with older API versions. Lambdas are included with these. 

See [this page](https://developer.android.com/studio/write/java8-support.html) for details. 

We can use that once Android Studio 3 is released to the stable channel.

**Comment by MattiaPrimavera** [comment]
Or ... Include it now since it clearifies a lot **rxJava** calls + reduces boilerplate code and just remove it as soon as **android studio** release comes up :) above all whether the syntax btwn **retrolambda** and new studio stay the same

**Comment by maniac103** [comment]
AS3 is in beta, it won't be long until it's released. I think we can wait for its release.
