### ISSUE TITLE
New issue "+" button

### ISSUE THREAD

**Issue by ildar** [slapperwan/gh4a#732]
When a user opens Issues view, he can see the "+" button in the right bottom corner. But when he scrolls issues the button disappears and don't come back.

**Comment by maniac103** [comment]
Dupe of #711 (and already fixed, see #673)

**Comment by Tunous** [comment]
@slapperwan it would be a good idea to release a bug fix update.

**Comment by maniac103** [comment]
> @slapperwan it would be a good idea to release a bug fix update.

+1, but please wait until Monday; I got another fix to make.

**Comment by slapperwan** [comment]
Ok sure, let me know once done.

**Comment by maniac103** [comment]
@slapperwan Done :)

**Comment by slapperwan** [comment]
Thank you, I will release it coming 1-2 days.
