### ISSUE TITLE
Trending repo list generation will break on 10/10/17

### ISSUE THREAD

**Issue by maniac103** [slapperwan/gh4a#751]
I got an email from scrapycloud in which they say periodical scrape jobs will be limited to paying accounts from 10/10/17 onwards, which means trending repo generation will break for us at that date.

@Tunous @slapperwan Any ideas on how to proceed? Last I checked there weren't any alternative free cloud scrapers, so what shall we do now? Do the scraping on-device (slow and significantly more data usage)?

**Comment by smichel17** [comment]
I personally do not use this feature and would not care if it disappeared

**Comment by Tunous** [comment]
> Any ideas on how to proceed? Last I checked there weren't any alternative free cloud scrapers, so what shall we do now? Do the scraping on-device (slow and significantly more data usage)?

I don't have any other ideas than that...

**Comment by Unpublished** [comment]
What do you think about https://github.com/Unpublished/GithubTrending?
if you set this up as a daily travis cron it'll update itself everyday and can be used in the app like this https://github.com/Unpublished/gh4a/commit/6162c077052a4c30f60e5140b2cab26dc4149bc5

**Comment by maniac103** [comment]
I used scrapy previously: https://gist.github.com/bf43a31bafa7d96a0ea1026dc473fcb4

I just need a server to set it up on...

**Comment by Unpublished** [comment]
So you want to run the scraper every 10-15 minutes?
Because for me it would be sufficient if it scrapes only once a day and that's what happens in the above repo without need for a server.
Scrapy looks a bit more comfortable, I'm probably going to use it too :D

**Comment by maniac103** [comment]
> So you want to run the scraper every 10-15 minutes?

Maybe not every 10 minutes, but at least once an hour. Fetching the daily trends on a daily schedule seems a little pointless ;-)

**Comment by Unpublished** [comment]
At the moment I setup Travis to do a daily cron (that's the shortest interval available) in the Travis repo settings. But I think it's possible to get a shorter Interval, I'll try now.

**Comment by Unpublished** [comment]
Travis now waits 30m (build times out after 50m), deploys and recursively triggers itself on trends branch.

TODOs I'm seeing:
- [ ] Prevent stop if trending data doesn't change and therefore no commit is pushed (maybe write current datetime in a file?)
- [ ] Try again if scraper fails (I think Travis has a command for this)

**Comment by Alonski** [comment]
Just chiming in that I actually liked this feature when it worked :)

**Comment by Unpublished** [comment]
> What do you think about https://github.com/Unpublished/GithubTrending?
> if you set this up as a daily travis cron it'll update itself everyday and can be used in the app like this Unpublished/gh4a@6162c07

Scraping is pretty stable now, anyone can try it by applying the quoted commit and I would be happy to see it in Octodroid officially :)

**Comment by maniac103** [comment]
Oh, I missed the comment about the 30m updates...if that's the case, I'll switch to it, at least for now.
