### ISSUE TITLE
GitHub emoji are not rendered in comment preview

### ISSUE THREAD

**Issue by dgw** [slapperwan/gh4a#764]
Emoji codes (e.g. `:shipit:`) in published issue/PR comments are rendered, but not in the preview when writing a comment.

I'll update this issue if I come across other Markdown elements that are missing from previews.

Is this likely to be something a relative noob to Android development (like me) could tackle? It's Hacktoberfest, after all. :)

**Comment by smichel17** [comment]
They're rendered when I'm writing comments. ☺

**Comment by Tunous** [comment]
> Is this likely to be something a relative noob to Android development (like me) could tackle?

Yes, wrapping the string with `EmojiParser.parseToUnicode` before it's set probably should be enough. `MarkdownPreviewWebView.setContent` is where the text is set.

**Comment by dgw** [comment]
> They're rendered when I'm writing comments. ☺

Oh, I think I was insufficiently specific. I meant GitHub's `:emoji:` codes, like `:shipit:` => :shipit: ☺

Thanks for the pointers, @Tunous. I'll have to see about getting a machine set up with the Android SDK and emulator, maybe over the weekend.

**Comment by dgw** [comment]
Not gotten the SDK running yet, but looked at the code this morning. It looks like `MarkdownPreviewWebView.setContent` _has_ to be the place. Though I thought it would make more sense to parse the emoji in `MarkdownPreviewWebView.generateMarkdownHtml`, somehow I don't think `EmojiParser` will parse the base64-encoded text passed to that function.

In this case I guess it's not a big deal, because `setContent` is the only place that calls (that version of) `generateMarkdownHtml` (`WebViewerActivity` has its own version used for rendering published content). But it feels a little unclean to have to parse emoji separately before rendering the Markdown…
