### ISSUE TITLE
Mention someone by tapping their username

### ISSUE THREAD

**Issue by smichel17** [slapperwan/gh4a#769]
It would be great if, in issues/prs, you could tap on someone's username and it would append `@<username>` to the comment box.

I got the idea from the [Riot.im](https://f-droid.org/app/im.vector.alpha) (matrix client) app, if you want to try it out for feel.

**Comment by maniac103** [comment]
Would you want this in addition to the already existing auto completion after entering '@' (IOW, did you already discover that functionality)?

**Comment by smichel17** [comment]
Yes. It's one of those things that doesn't seem like a big deal (what's an extra second or two to type `@`, and find the person you want to tag?), but makes a huge difference to the feel.

**Comment by smichel17** [comment]
Empirically, it actually saves quite a lot, as well. To mention someone right now, starting from "I just finished reading their comment", you have to:

- Look down and tap the comment area
- Switch your keyboard to show symbols, type `@`, and switch your keyboard back to letters
- Look back up at the comment to see who you were replying to (which is now harder because they keyboard is expanded)
- Look back down and pick them from the list (might require typing the first few chars of their name)
- Look back up at the comment to remember what you wanted to reply to
- Look back down at the comment box to write your reply

Obviously those don't all happen every time -- sometimes you remember who you were replying to and don't look back up. But it happens often enough that it's much nicer to be able to just tap their username without even thinking about it and start the reply while it's fresh in your mind.

**Comment by Tunous** [comment]
![mention-tap](https://user-images.githubusercontent.com/5156340/31586119-f074da12-b1cc-11e7-9397-27264718a4f1.gif)
