### ISSUE TITLE
Sorting of Notifications

### ISSUE THREAD

**Issue by jancborchardt** [slapperwan/gh4a#770]
Currently the notifications are sorted alphabetically, by organizations and the repositories within.

This is unexpected cause Github does it on their website by sorting repos with the most recent notifications first.

That's also a much more relevant metric since currently old notifications are at the top simply cause their organization starts with an a. ;)

**Comment by jancborchardt** [comment]
Thanks a lot for the prompt fix @maniac103! :) :tada:

**Comment by jancborchardt** [comment]
@maniac103 @slapperwan will there be a new release at some point? Last one was 3 months ago it seems?

**Comment by maniac103** [comment]
Indeed, we should do a 4.2.2 release. @slapperwan Can you please create one?

**Comment by slapperwan** [comment]
Ok I will release it. Thanks
