### ISSUE TITLE
News Feed started to only show star events

### ISSUE THREAD

**Issue by phw198** [slapperwan/gh4a#773]
The News Feed screen has stated to only show Starred events for my repositories not, for example, issue updates by other users.

Not sure if this is a recent GitHub change affecting the app?

Also, feature request - I've just found it would be nice to be able to upload files to an issue from gh4a 🙂

**Comment by phw198** [comment]
Running v4.2.1
![screenshot_20171013-080610](https://user-images.githubusercontent.com/11843015/31534140-7e1dc888-afed-11e7-8c3c-65994c3f53c2.png)

**Comment by Tunous** [comment]
I think it's a GitHub change. I observe the same with news feed on website. No idea why they would change that, it was much more useful before.

**Comment by Tunous** [comment]
> Also, feature request - I've just found it would be nice to be able to upload files to an issue from gh4a 🙂

That's related to #297 I think.

**Comment by maniac103** [comment]
FWIW, I'll ask them about it. I only have push events in my news feed anymore.

**Comment by maniac103** [comment]
Got a response:
```
The changes to the API were not intentional, and it's possible they happened due to the changes made to the web UI's news feed. The team is looking into why this happened and into fixing this, but it doesn't seem to be a trivial problem. We have an issue open internally for this and a link to your message so we'll be able to followup with you as soon as there's any news here. We're sorry for the trouble, and wanted to thank you again for reporting this.
```

**Comment by kshvmdn** [comment]
My newsfeed seems to be back to normal!

**Comment by phw198** [comment]
> My newsfeed seems to be back to normal!

Yes, so is mine! :+1:
