### ISSUE TITLE
Possible copyright violation

### ISSUE THREAD

**Issue by dimqua** [slapperwan/gh4a#774]
What you think about this?

https://git.io/vdPfM

**Comment by Tunous** [comment]
Based on initial commits and current code they didn't fork. There are some similarities in interface based on screenshots but they most likely just liked our interface and took that as inspiration. I don't see any copyright violation in that.

**Comment by yakov116** [comment]
https://github.com/ThirtyDegreesRay/OpenHub/issues/12

Its a pure copy of fasthub LOL

I did not even have to try hard to compare forks

**Comment by dimqua** [comment]
FastHub with UI inspired by OctoDroid. 😆

**Comment by smichel17** [comment]
Octodroid *does* have the best UI of the 3 Github apps on F-Droid...

**Comment by yakov116** [comment]
@smichel17 Yeah its a shame he stole fasthub's code and tried to make it look like Octo 😛

**Comment by yakov116** [comment]
@Tunous looks like he changed his mind lol

I spent an hour today having fun... He literally copied the code from FastHub and design from octo.

**Comment by Tunous** [comment]
I see. I don't know FastHub code so couldn't tell that it was copied from here.
