### ISSUE TITLE
Line comments being typed lost on portrait/landscape rotation

### ISSUE THREAD

**Issue by cben** [slapperwan/gh4a#777]
If I rotate phone while typing comment on a PR, I get a blank comment editor, what I was typing is lost :-(

**Comment by Tunous** [comment]
Are you running the latest (v4.2.1) version?

**Comment by cben** [comment]
Yes.  It seems it only happens when commenting on a line, or replying to comment on a line.
No problem writing top-level PR comment, not what issue comment.

**Comment by Tunous** [comment]
> It seems it only happens when commenting on a line, or replying to comment on a line.

Got it. Happens to me too. Will fix.

**Comment by Tunous** [comment]
@maniac103 I tried to fix this with 48350631d63f3681d170ae45d61762f2f24b4e6b but there is something else wrong. These input fields rely on automatic state saving by `TextView` but apparently, it doesn't work correctly in `EditCommentActivity` like it does in `CommitNoteFragment`. I can't see what's missing though...
