### ISSUE TITLE
Newsfeed issue/PR label events aren't handled

### ISSUE THREAD

**Issue by kshvmdn** [slapperwan/gh4a#779]
Think this is caused by Newsfeed API changes (#773).

Here's the event on the GitHub homepage:

<img width="696" alt="screen shot 2017-10-21 at 12 32 25 pm" src="https://user-images.githubusercontent.com/8116382/31853766-4dee735e-b65c-11e7-9691-90de1132a37b.png">

and in app:

![22690660_1725730520802400_1325331341_o](https://user-images.githubusercontent.com/8116382/31853767-57c02d8c-b65c-11e7-8412-02efa5dbf745.jpg)

**Comment by maniac103** [comment]
So the issue seems to be that EventAdapter doesn't generate a title for label events. Doesn't seem to be related to the news feed changes, but it's a bug nevertheless :-)

**Comment by devdrops** [comment]
Hi! I've noticed today the same behaviour for comments on issues.

**Comment by maniac103** [comment]
Actually, this seems to be a (temporary?) server side bug. According to [the docs](https://developer.github.com/v3/activity/events/types/#labelevent), label events should *not* appear in timelines, and this seems to be the case for me as of now. @kshvmdn Can you still see such events in your timeline?

**Comment by kshvmdn** [comment]
@maniac103, seems to still be the case for me, saw this one yesterday (unless this was patched within the last 20 hours?):

![](https://i.imgur.com/0kbWPyw.jpg)

**Comment by kshvmdn** [comment]
Now that I'm thinking about it, I'm watching a ton of repos where issues are being labelled (including this one), but this problem only occurs for that single repo ([golang/dep](https://github.com/golang/dep)).

**Comment by devdrops** [comment]
> Now that I'm thinking about it, I'm watching a ton of repos where issues are being labelled (including this one), but this problem only occurs for that single repo (golang/dep).

@kshvmdn I noticed this behavior on other repositories too (https://github.com/LappleApple/feedmereadmes):

![screenshot_20171028-170110](https://user-images.githubusercontent.com/1259313/32273664-8379c6a4-beea-11e7-94cd-fddde9700c0a.png)

**Comment by kshvmdn** [comment]
@devdrops, ah, interesting. I noticed that each of those issues has the "good first issue" label, which might be the problem here. 

@maniac103, you think you can quickly test this with that issue specifically?

**Comment by maniac103** [comment]
> you think you can test this with that issue specifically?

Problem is that I don't have access to your timelines :-( Those events don't appear in the respective repository timelines (repo activity tab); I just tried with that feedmereadmes repo.

Just to make it clear: the app currently doesn't handle those events because they're *not supposed to be present at all*.

I also asked Github support about it; they said it's likely not intentional and they'll investigate.

**Comment by kshvmdn** [comment]
> Just to make it clear: the app currently doesn't handle those events because they're not supposed to be present at all.

Haha, yeah, that's what I meant when I said this was caused by changes to the newsfeed API.

I guess the best solution for the time being is to just wait for GitHub to solve the API problems.

**Comment by maniac103** [comment]
@kshvmdn Is this fixed (by Github's latest changes to the news feed API) now?

**Comment by kshvmdn** [comment]
@maniac103, I think so, haven't seen this happen again since the API was fixed. Will reopen if I see anything.
