### ISSUE TITLE
Issue with adding reactions

### ISSUE THREAD

**Issue by notramo** [slapperwan/gh4a#780]
Adding reaction on an issue or PR doesn’t always work.
For example, I can't add reaction to an issue in the manjaro/pamac repo.
It works in some repos.
Adding reaction via the web interface of github always work.

**Comment by maniac103** [comment]
What does 'doesn't work' mean exactly?

**Comment by notramo** [comment]
The reaction doesn't got added.

**Comment by maniac103** [comment]
Indeed. This seems to be a server side issue, though. From the logs:

10-25 16:35:04.895 D/OkHttp  (3116): --> POST https://api.github.com/repos/manjaro/pamac/issues/299/reactions http/1.1 (16-byte body)
10-25 16:35:05.178 D/OkHttp  (3116): <-- 404 Not Found https://api.github.com/repos/manjaro/pamac/issues/299/reactions (282ms, unknown-length body)

The 404 really doesn't make sense here. I'll investigate and ask Github support about it.

**Comment by maniac103** [comment]
Support response:

> You're making a request with an OAuth token, so this feature kicks in:
>
> https://help.github.com/articles/about-third-party-application-restrictions/
> 
> With that feature enabled, you're always allowed to read public information, but modifying public information might be blocked if it would reveal organization membership. In this case, I don't think it reveals that since any user is allowed to create reactions on public issues, regardless of whether they're a member of the organization. So, I think the endpoint is incorrectly blocking you from adding reactions. I'll open an issue for that and ask the team to take a look. I can't promise an ETA, but we'll followup as soon as there's any news.

**Comment by maniac103** [comment]
Got a response from support; this was fixed server side. I tried and can confirm that's the case.
