### ISSUE TITLE
Right side drawers becomes expandable after using fastscroller

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#782]

**Comment by Tunous** [comment]
It becomes possible to swipe it after using fast scroller.

**Comment by Tunous** [comment]
Apparently it also happens in other screens too like IssueActivity.

**Comment by whisperity** [comment]
Happens on the pull request conversation  page too, resulting in an empty drawer.

**Comment by maniac103** [comment]
Fixed with https://github.com/slapperwan/gh4a/commit/ba1bb21fc46e79519bab8c999fd7f118f02e2b73
