### ISSUE TITLE
Support authentication with a token

### ISSUE THREAD

**Issue by laughedelic** [slapperwan/gh4a#783]
I'd like to be able to manually generate an access token and provide it to the app. The reason is that this way I would give the application access to my work org in which I don't have admin rights. Currently I just don't have any notifications or events from that org which makes the app mostly unusable for me (which I like in many other aspects).

**Comment by maniac103** [comment]
I've now added back authentication via user/password, which, unless I am missing something, should cover your use case as the user/pw auth creates personal access tokens. Please let me know if there's a need for supplying a raw token that I'm missing.

**Comment by laughedelic** [comment]
@maniac103 I don't think it resolves the issue. I'm using v4.2.1, logged out and in again and I still don't see my work organization private repos. 

As far as I understand, I'm logging in through the app to grant it certain permissions to act on my behalf. It won't let me grant any access on organizations where I am not an administrator (in the web-interface it sometimes shows a button to ask administrators for this permission). 

The difference with using a token is that it gives any permissions the token was created with and works with any organizations as if I was doing stuff by myself.

**Comment by maniac103** [comment]
4.2.1 doesn't have my today's changes ... the yet-to-be-released 4.3 will have it.
