### ISSUE TITLE
update gradle to fit Android Studio 3.0

### ISSUE THREAD

**Issue by WanderMax** [slapperwan/gh4a#786]
Android Studio 3.0 limits the Gradle version to 4.0+.
It's needed to update the Gradle version.

**Comment by maniac103** [comment]
Is AS 3.0 out of beta? We'll move to it once that happens.

**Comment by WanderMax** [comment]
yes, officially released today

**Comment by maniac103** [comment]
OK, will update the gradle plugin then in a few days. Will help me in the rx branch as well, as I can get rid of retrolambda there with the new AS.
