### ISSUE TITLE
[FR] multi backend ready?

### ISSUE THREAD

**Issue by ildar** [slapperwan/gh4a#798]
Hi! I wonder how ready the app is to work with other git servers, especially gitlab-based. This surely requires backend abstraction, maybe heavy refactoring and such. But maybe some of that already done?
Gitlab is missing a good developing client while gitlab instances are numerous.
What do you think?

**Comment by Tunous** [comment]
OctoDroid is highly coupled with the GitHub API and features. I don't see it supporting other git servers. At the current point it would be much easier to create new app than modify OctoDroid for this.

**Comment by ildar** [comment]
That's sad.
Thanks anyway.

**Comment by smichel17** [comment]
@ildar LabCoat is under slow but active development

**Comment by ildar** [comment]
This is the LabCoat's fault why I raised this OctoDroid request.
LabCoat is quite good and I like it. But with lack of searching in issues
LabCoat is nearly useless.
https://gitlab.com/Commit451/LabCoat/issues/128

**Comment by ildar** [comment]
... and actually the idea about a multi-backend git* client app is long
rolling in my mind, so I wanted to share and see what happens.
