### ISSUE TITLE
Next release timing?

### ISSUE THREAD

**Issue by smichel17** [slapperwan/gh4a#800]
There's been a bunch of new features since the last release, 7 weeks ago. Time for a release?

**Comment by maniac103** [comment]
With the app being completely broken on pre-L now (#819), this becomes a much more pressing issue. @slapperwan Can you please do a 4.3 release?

**Comment by smichel17** [comment]
Looks like f-droid updates using tags, so you could do a release there any time. Although I do understand there are downsides to doing that, too.

**Comment by ShalokShalom** [comment]
Is slapperwan the only one who can do a release?
After one week with no response, I would welcome any apk, also in F-Droid. 
:)

**Comment by ShalokShalom** [comment]
I see this issue open for half a year

Will you wait one half of a year more for a release?

Slapperwan was no active on his Github account for at least a full year, do you really like to depend your releases on him?

What are you doing, if there is a security hole? Wait half a year?

**Comment by ShalokShalom** [comment]
This release is out, so this can be closed :)

**Comment by maniac103** [comment]
Yeah, even though my name is not Mike ;-)

**Comment by ShalokShalom** [comment]
I think I read this somewhere :P

**Comment by Bluscream** [comment]
What are the new login options? Oauth,user/pw and token?

**Comment by ShalokShalom** [comment]
https://github.com/slapperwan/gh4a/issues/818#issuecomment-368530217

**Comment by ShalokShalom** [comment]
https://github.com/slapperwan/gh4a/issues/818#issuecomment-368530217
