### ISSUE TITLE
Issues page inaccessible

### ISSUE THREAD

**Issue by arm32x** [slapperwan/gh4a#810]
When I view a repository in OctoDroid, there is **no visible option to view issues**. However, when I open a link to a GitHub issues page, it will show it in OctoDroid as normal. I can also access issues from the My Issues page.

Could someone please tell me how to access the issues page, or add the option in if it doesn't exist?

My device is a Google Pixel running Android 8.1, and I am using OctoDroid 2.4.1.

**Comment by smichel17** [comment]
The part where it says "104 Issues" is actually a link to the issues page, even though it doesn't look it. See #681 for more info.
