### ISSUE TITLE
Save comment draft

### ISSUE THREAD

**Issue by StefanBrand** [slapperwan/gh4a#815]
(or at least display a confirm dialogue if I accidentally try to discard an unsaved issue comment...)

I just typed an issue comment three times because I once clicked the back button and once pressed the pencil button instead of the send button.

Octodroid should save issue comments or at least warn me if I want to discard an unsaved comment.

**Comment by maniac103** [comment]
Dupe of #358.

**Comment by StefanBrand** [comment]
Sorry for the duplicate, the "About" link in the app settings directly leads to a window for a new issue. I couldn't search for existing issues... 😊
-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 10. Februar 2018 19:07:03 MEZ schrieb maniac103 <notifications@github.com>:
>Closed #815.

**Comment by maniac103** [comment]
No problem at all, just need to keep the issue list clean :-)
