### ISSUE TITLE
Support TLSv1.2 on KitKat and older

### ISSUE THREAD

**Issue by Matrixcoffee** [slapperwan/gh4a#819]
With GitHub having removed support for TLSv1.0 and 1.1, OctoDroid no longer works on Android devices prior to 5.0. The strange thing is that some of these devices do have support for TLSv1.2, but it has to be forced on. Please consider doing so.

Since OctoDroid seems to use OkHttp, square/okhttp#2372 will probably be most instructive here.

**Comment by maniac103** [comment]
It doesn't use OkHttp yet, but will do in the future.

**Comment by github-userx** [comment]
thanks a lot for this thread. I am on an older android device and I was already wondering why nothing in the OctoDroid app works anymore! Hoping for a solution soon, since this app helped me a lot already.

**Comment by Matrixcoffee** [comment]
In that case see:
* https://stackoverflow.com/questions/37705367/how-do-i-get-tls-1-2-to-work-in-android-4-4-without-the-help-of-google-play-serv
* https://stackoverflow.com/questions/28943660/how-to-enable-tls-1-2-support-in-an-android-application-running-on-android-4-1

**Comment by ildar** [comment]
Ahhh, it's tickling for a release already!
