### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by milo** [slapperwan/gh4a#823]
Hi. I updated to version 4.3.0 and cannot run on Android 4.4.4. It crashes right after run.

**Comment by milo** [comment]
Remove app data or uninstall/install did not help.

**Comment by maniac103** [comment]
I've seen the issue in Crashlytics reports already; will take care of it today.

**Comment by maniac103** [comment]
Interesting, I don't see the crash on either an API 16 or an API 19 emulator (?)

**Comment by milo** [comment]
Can I help somehow?

**Comment by maniac103** [comment]
[gh4a-test.zip](https://github.com/slapperwan/gh4a/files/1780269/gh4a-test.zip)

Can you please test whether this apk works for you (just rename .zip to .apk - Github doesn't allow uploading apk files)? I've given it a different package name so it installs alongside the Play Store release version since I don't have the official signing keys.

**Comment by milo** [comment]
I cannot install the app. Installation from unknown sources is allowed, I agree with permissions access, but then I get message Application cannot be installed (actually I get message in Czech language, I hope the translation is accurate).

**Comment by maniac103** [comment]
Oops, sorry. I didn't know that the suffix '.test' in the package name is special :-/
New test version attached.

[gh4a-test.zip](https://github.com/slapperwan/gh4a/files/1780696/gh4a-test.zip)

**Comment by milo** [comment]
Great! 👍 This version works perfectly for me.

**Comment by maniac103** [comment]
@milo Thanks for testing!
@slapperwan Can you do a 4.3.1 release ASAP, please?

**Comment by slapperwan** [comment]
@maniac103 done.  Thank you.

**Comment by milo** [comment]
Thank you both. Upgraded and works perfectly.

**Comment by ShalokShalom** [comment]
Uploading .apk files is possible on the release page: https://github.com/slapperwan/gh4a/releases/tag/v4.2.1

**Comment by maniac103** [comment]
Yes, but one can only create (tagged) releases there, which is not what I wanted to do here.

**Comment by ShalokShalom** [comment]
Yeah I see. I mean the current releases are not that available also:
4.3.1 and 4.3.0 got uploaded without an apk release.

I could have done a separate issue, probably :)
I thought you did forget about this option at all. :)
