### ISSUE TITLE
Shorter sync intervals of the notifications

### ISSUE THREAD

**Issue by ShalokShalom** [slapperwan/gh4a#825]
I am used to live updates of my notifications is there any reason why 15 minutes is the shortest possible?

**Comment by Tunous** [comment]
Yes, it's a limitation of library we are using (and the APIs it's using). Here is a detailed explanation: https://github.com/evernote/android-job/wiki/FAQ#why-cant-an-interval-be-smaller-than-15-minutes-for-periodic-jobs
