### ISSUE TITLE
Notifications not being marked read

### ISSUE THREAD

**Issue by matthewdias** [slapperwan/gh4a#826]
Marking read via the system notification action or on the notifs screen in the app has no effect.

**Comment by maniac103** [comment]
Can you provide more details, like app version or logcat output? I just tried to mark as read by clicking an item in the notification list, which worked fine. This is on 4.3.1.

**Comment by matthewdias** [comment]
Oops, looks like I wasn't up to date. Seems to be fixed on 4.3.1

**Comment by maniac103** [comment]
'Mark read buttons' as in the double checkmarks or as in the 3-dot menu?

**Comment by matthewdias** [comment]
Double checks. 3-dot menu seems fine.

**Comment by maniac103** [comment]
Hmm, works fine for me. Can you check logcat after an unsuccessful attempt to mark as read?

**Comment by mbStavola** [comment]
Encountered the same issue on 4.3.1.

Attached `pidcat` and tried again, but unfortunately no useful logs seemed to be produced.

**Comment by matthewdias** [comment]
https://github.com/Meisolsson/GitHubSdk/pull/22

If and when this gets merged and released I'll create a pull here to update.

**Comment by matthewdias** [comment]
Dunno what changed but it seems like this is fixed now
