### ISSUE TITLE
An error 404 page shows up when going back

### ISSUE THREAD

**Issue by beckysophie** [slapperwan/gh4a#830]
***Expected Behavior***

After browsing some repositories, users have to view some issues and pulls.
Users tend to go back to the previous page they came from or to go back and view other related searched repositories properly, without any issue 

***Actual Behavior***

After selecting and viewing a repository, on going back to the initial page displays an 'error 404'

***Test Tools***

* Operating system : Android 6.0
* Phone : Infinix hot s
* Octodroid App v4.3.1

***How to produce the bug***

Open the app, log in to github, now browse a repository (I used utopian-io as a case study shown in the video below) and select it for viewing. 
After selecting, click on issues, select any open issues, now keep pressing the back button at the top left corner, so as to take you to the main repository, It would load up the repository home for like a second, then keep bringing an 'error 404' page. Even when I press the 'try again' button,  it will still be bringing the error message..... 

*Each step on how to produce the bug is shown in the video below.....*

*video file...*

https://youtu.be/Xwq1CShdCCE

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/an-error-404-page-shows-up-when-going-back">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by maniac103** [comment]
Looks like there's something special with the utopian-io user. I'll check it.
