### ISSUE TITLE
The app crashes if a specific link is opened 

### ISSUE THREAD

**Issue by beckysophie** [slapperwan/gh4a#833]
***Expected Behavior***

It should be able to open the link to show more details,info and updates of a specified repository 

***Actual Behavior***

When the link is visible in a particular repository and it's clicked, the app crashes 

The highlighted link in the image below shows the link in the App on a specific repository 

![image](https://s14.postimg.org/4ixo70iht/IMG_20180326_213251_513.jpg)

***How to produce the bug***

Open the App, search for a repository which have the link available in it(as shown in the video below), click on the link, and the App would crash.... 

***

***PS***

I had to use the repository of octodroid as a case study, because the link is available on the repository.

On the search for repository, you can search for the repository of octodroid on the app as a case study to reproduce the bug. Type *gh4a* in the search box as shown in the video..... 

***TEST TOOLS***

* Operating system : Android 6.0
* Phone : Infinix hot s
* Octodroid v4.3.1

***Recording of the bug is showned below......***

Watch the video below to see how it behaves.... 

https://youtu.be/4YQ76xYJ-Vs

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/the-app-crashes-if-a-specific-link-is-opened">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Tunous** [comment]
Fixed in 115a9f6ce501f5cf9e74913e2e88179589f04e22
