### ISSUE TITLE
Crash when opening t/t7406-submodule-update.sh in git/git

### ISSUE THREAD

**Issue by maniac103** [slapperwan/gh4a#837]
Root cause is TransactionTooLargeException when saving state of RepositoryActivity. We probably should move the content list cache into a retained fragment.

**Comment by maniac103** [comment]
Or we drop the cache altogether and hope that HTTP caching layer does the right thing?

**Comment by Tunous** [comment]
I think that retained fragment is a better option. I wouldn't trust HTTP caching layer enough to rely only on it.

**Comment by maniac103** [comment]
Tried the HTTP-cache-only solution as well, but it brings a performance penalty: at least for small to medium sized content lists, checking the ETag status (and getting a 304 response, leading to cache response being used) needs the same time (~200ms for me) as loading the actual data does.
