### ISSUE TITLE
OctoDroid crashes when going to the Kiss Launcher GitHub project 

### ISSUE THREAD

**Issue by cdysthe** [slapperwan/gh4a#848]
I'm trying to go to the KISS launcher project: 

https://github.com/Neamar/KISS 

OctoDroid crashes every time. Works fine in other GitHub clients. 

OctoDroid 4.3.1 on Android 7

**Comment by Tunous** [comment]
Fixed in 74c9b80d6a4d5fa3300f1d7c73966c62f9c7c26f
