### ISSUE TITLE
Force close on open

### ISSUE THREAD

**Issue by craigfowler** [slapperwan/gh4a#850]
Very recently (within the last day or two) Octodroid has begun force-closing immediately on opening, before I can interact with any UI. I've tried clearing the app cache and also restarting the device but neither has helped.

I was able to use it successfully a couple of days ago and I haven't had an updated app since then (I see last update was March 2018). Perhaps triggered by a GH API change?

I'm using Android 8.0.0 and (according to Google Play) Octodroid 4.3.1.

Thanks

**Comment by maniac103** [comment]
I don't see a matching log in the Crashlytics reports :-( Do you have ADB available on your PC by any chance, or is - alternatively - your device rooted?

**Comment by craigfowler** [comment]
Problem has gone away in Octodroid 4.3.2, cannot reproduce anymore. So thanks - whatever was done 🤣
