### ISSUE TITLE
Add adaptive launcher icon

### ISSUE THREAD

**Issue by matthewdias** [slapperwan/gh4a#853]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by c-e-p-x-u-o** [comment]
you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by maniac103** [comment]
An adaptive icon is not required for targetting API 26.

I also don't yet have an idea how an adaptive version if the current icon could look like...

**Comment by matthewdias** [comment]
could just stick it in a white container i think

**Comment by c-e-p-x-u-o** [comment]
> you should fix it to upload new version to google play

looks like it's not true

**Comment by c-e-p-x-u-o** [comment]
> could just stick it in a white container i think

agree

**Comment by maniac103** [comment]
This is what I could come up with so far:
![grafik](https://user-images.githubusercontent.com/781373/49873359-f1da7c80-fe1b-11e8-928f-d7f5307d4923.png)

Not sure yet whether I like this or not. @Tunous @slapperwan Thoughts on this?

**Comment by c-e-p-x-u-o** [comment]
Nice!

**Comment by Tunous** [comment]
@maniac103 Looks pretty good. Could you also show how it would look with other shapes if possible?

**Comment by maniac103** [comment]
Sure:
![grafik](https://user-images.githubusercontent.com/781373/49874959-1df7fc80-fe20-11e8-966c-6ddf3586f415.png)
![grafik](https://user-images.githubusercontent.com/781373/49874978-2bad8200-fe20-11e8-9704-2177def18e94.png)
![grafik](https://user-images.githubusercontent.com/781373/49875001-3b2ccb00-fe20-11e8-9feb-439b00e032db.png)
![grafik](https://user-images.githubusercontent.com/781373/49875020-467ff680-fe20-11e8-82cd-93e80e8871ac.png)

**Comment by 532910** [comment]
Awesome! Thank you!
