### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by iraamaro** [slapperwan/gh4a#859]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by Tunous** [comment]
We don't have anything prepared for translations. You can just start editing [strings.xml](https://github.com/slapperwan/gh4a/blob/master/app/src/main/res/values/strings.xml) file or use something like [Stringlate](https://github.com/LonamiWebs/Stringlate). I don't know if there is anything similar for pc.

It would be nice to integrate with https://crowdin.com/ or similar but only @slapperwan can do that as far as I know.

**Comment by slapperwan** [comment]
Hi, which option do you plan to use?

**Comment by smichel17** [comment]
https://weblate.org/ is an alternative to crowdin that, while less polished, is FLO itself and is gratis for FLO projects.

**Comment by yurtpage** [comment]
Duplicate of #947
