### ISSUE TITLE
editing

### ISSUE THREAD

**Issue by mr-phlames** [slapperwan/gh4a#863]
Can't edit files in my repository...maybe you can handle this in a new release of Octo droid

**Comment by Tunous** [comment]
See #855

**Comment by mr-phlames** [comment]
Hello, i was talking about the fact that i can't make a whole lot of
operations on the app

**Comment by mr-phlames** [comment]
Hey,

I just signed the petition "Netflix: Remove blasphemous film The First
Temptation of Christ from Netflix NOW!" and wanted to see if you could help
by adding your name.

Our goal is to reach 200,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/kYGB54xWym

Thanks!
Mychi
