### ISSUE TITLE
App crashes when accessing pinned issues

### ISSUE THREAD

**Issue by techexo** [slapperwan/gh4a#869]
Hi,

My app crashes when accessing pinned issues:
https://github.com/wallabag/wallabag/issues/3439
https://github.com/wallabag/wallabag/issues/1284

I'm running on LineageOS (android 8.1.0).

What can I do to give you more information about this?

**Comment by maniac103** [comment]
I know about it already; I'll prepare a PR for the Github bindings which will fix this.

**Comment by techexo** [comment]
Great! I'm waiting for it then :smile:

**Comment by bpcurse** [comment]
Is this crash related? celery/celery#5180

**Comment by maniac103** [comment]
https://github.com/Meisolsson/GitHubSdk/pull/25

**Comment by techexo** [comment]
Thanks @maniac103. Do you have any idea approximately how much time will be needed for changes to cascade into OctoDroid? (No pressure intended, I just have no idea of the activity of Octodroid and the rhythm of releases :smile:)

**Comment by maniac103** [comment]
I've just pushed the SDK update, so it's only a matter of @slapperwan doing the release.

@slapperwan Can you please do a 4.4 release? #733 probably justifies the version bump.

**Comment by slapperwan** [comment]
Noted

**Comment by techexo** [comment]
Hi @maniac103 @slapperwan, any news for the 4.4 release? It's been a long time now and this issue is quite critical for accessing some repositories' bugs. Thanks in advance!

**Comment by slapperwan** [comment]
Hi, I just publish the app into playstore.  Thank you.

**Comment by maniac103** [comment]
@slapperwan Thanks! Could you please also update the repo screen screenshot there?
