### ISSUE TITLE
I'm not able to download releases from within octodroid

### ISSUE THREAD

**Issue by GintokiHub** [slapperwan/gh4a#871]
So I'm not sure if I am meant to open every release view within 'open browser' (instead op DL in app) to be able to download.
However it is not working for me.

I am guessing this would be a bug correct?

**Comment by maniac103** [comment]
This sounds like #857 ... what Android version are you on?

And yes, you should be able to download release artifacts from within the app itself by clicking on them.

**Comment by GintokiHub** [comment]
https://mega.nz/#!M5AlDYYD!RE8vKjQEq_Gdod2q8kLVQcMZwAd93ZmrX1gmjpyGGTI

**Comment by GintokiHub** [comment]
android 9 I attached the image because Im running the oneplus6 beta as well

**Comment by maniac103** [comment]
Huh, I can reproduce, but would've sworn I tried this recently...I'll look into it.

**Comment by maniac103** [comment]
Yeah, that's what I found as well; the above commit just adds the missing notification. Closing the issue then.
