### ISSUE TITLE
Stars and Bookmarks tab order

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#875]
This is a very minor issue but it somehow started to make me feel a bit uncomfortable recently. Basically the title of entry in navigation bar and title of activity say "Stars and Bookmarks" but when you enter that activity you see that Bookmarks is the first tab followed by Stars.

I'm just not sure what to change. Reorder the tabs or change the name to "Bookmarks and Stars"? What are your opinions on this?

**Comment by maniac103** [comment]
I'd probably rename instead of reorder, but I don't have a strong opinion either way.
