### ISSUE TITLE
Commit Hash When Printing 

### ISSUE THREAD

**Issue by ferittuncer** [slapperwan/gh4a#877]
It would be nice to include commit hash to print output. Useful for code reviews.

**Comment by maniac103** [comment]
You mean to include the hash/ref when printing files?

**Comment by ferittuncer** [comment]
Git commit hash of which commit the file belongs to. So you know which version of the file you are reviewing.

It can be on top of the page or on the bottom. Small characters and the first six characters of the commit would do the job, no need for full hash.
