### ISSUE TITLE
Crash on attempt to open long discussion issue page

### ISSUE THREAD

**Issue by Wohlstand** [slapperwan/gh4a#879]
I have an isse at my repo:
https://github.com/Wohlstand/OPN2BankEditor/issues/46

Once I trying to open it by OctoDroid, then, it crashing.

Android 4.3, SGS-III GT-i9300

**Comment by maniac103** [comment]
I'd guess this is the same issue as #869?

**Comment by Wohlstand** [comment]
Just now I have tried to open another issue on another repo, and the crash was happen. You right!
I have sent the report with title `Issue 879 and issue 869` from my phone. Yeah, feel free to mark this a duplicated, I'll subscribe to #869.
