### ISSUE TITLE
AMOLED Dark Theme

### ISSUE THREAD

**Issue by doamatto** [slapperwan/gh4a#882]
It would be nice if there was an AMOLED Dark theme for that battery efficiency.

**Comment by maniac103** [comment]
There actually isn't any relevant battery savings from using a pure black theme:
https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/amp/

Thus, we'll stick to the default dark theme, which allows us to switch to a day/night theme (and thus automatic dark mode support in Android 10) soon.

**Comment by blackCauldron7** [comment]
You can still support auto dark mode just add a black theme option.
