### ISSUE TITLE
Star and Watch are gone for repositories

### ISSUE THREAD

**Issue by ildar** [slapperwan/gh4a#884]
With latest updates. Please explain. Thanks

**Comment by dimqua** [comment]
This is not true.

**Comment by ildar** [comment]
![Screenshot_20190329-095430](https://user-images.githubusercontent.com/517752/55208744-8b7e3c00-5209-11e9-9357-1c38a55f944a.png)
![Screenshot_20190329-095444](https://user-images.githubusercontent.com/517752/55208746-8c16d280-5209-11e9-9e2f-d0637c8eab95.png)
![Screenshot_20190329-095450](https://user-images.githubusercontent.com/517752/55208747-8c16d280-5209-11e9-86cf-3ee926a163af.png)

**Comment by dimqua** [comment]
@ildar to star/unstar a repository you need to click on the star icon (button). The same with watch/unwatch and the eye icon, although you can't choose "release only option".

**Comment by ildar** [comment]
You're right, thank you. I tried it before but missed as the icons are
quite small. So I thought it doesn't work.
Now I tried again accurately and it's ok. Thanks again.

**Comment by maniac103** [comment]
Alternatively you can click on the full row to go to the respective list and use the menu action there.

**Comment by smichel17** [comment]
Those menu actions seem to be missing, in the fdroid build at least

**Comment by maniac103** [comment]
Damn, guess I forgot adding those :-( I'll add them.
