### ISSUE TITLE
Unsubscribe button only "mark as read"

### ISSUE THREAD

**Issue by beerisgood** [slapperwan/gh4a#885]
Version 4.4.0 from F-DROID with LineageOS 16 (Android 9)

The button doesn't unsubscribe, it just mark the entry as read

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
*push*
C'mon

**Comment by maniac103** [comment]
Looks like it's a mixture of our and an SDK issue:
- Relevant SDK endpoint is https://github.com/maniac103/GitHubSdk/blob/master/library/src/main/java/com/meisolsson/githubsdk/service/activity/NotificationService.java#L83
- The SDK offers two settable flags https://github.com/maniac103/GitHubSdk/blob/master/library/src/main/java/com/meisolsson/githubsdk/model/request/activity/SubscriptionRequest.java#L50
- But the API only supports one of them https://developer.github.com/v3/activity/notifications/#set-a-thread-subscription
- We use the non-existing one https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/fragment/NotificationListFragment.java#L212

Should be reasonably easy to fix.

BTW, the bumping of the thread is both useless and impolite.

**Comment by beerisgood** [comment]
Sadly it's still not fixed with latest version (4.4.0) on F-DROID

**Comment by maniac103** [comment]
The 4.4.0 release was before this fix.

**Comment by beerisgood** [comment]
Yes, but no later version is available in F-DROID
