### ISSUE TITLE
OAuth stuck with wrong Github account

### ISSUE THREAD

**Issue by tilboerner** [slapperwan/gh4a#892]
I was going to add another Github account to Octodroid via OAuth, but decided against it while on the Github auth confirmation screen. Now this screen shows up whenever I try to use OAuth again, and I can't switch back to my old account because of it.

Closing or force-closing the app does not help; deleting the app's cache or data does not work, either. Reinstalling also does nothing. When I open the app and press `Login via OAuth`, I get returned to the Github confirmation screen for the unwanted account. Hitting the close button (`x`) or back (`<`) shows a splash screen *Authenticating...* with a spinner that never goes anywhere. As far as I can see, there's no other way to abort the authentication from the confirmation screen.

I'd expect to be able to choose another Github account or abort/restart the OAuth process somehow. Any ideas for a workaround? I'd very much like to avoid using a password login.

**Comment by maniac103** [comment]
Clearing the cookies and/or cache and/or data in Chrome would be my first idea/suggestion.

**Comment by tilboerner** [comment]
Right, it's using the browser session! Didn't think of that. Logging out of Github in the browser helped. Thanks! :)

Maybe you could add a little help text in the app, telling people to log out manually in case of trouble? Otherwise, feel free to close this issue.
