### ISSUE TITLE
Repositories with two types of issues

### ISSUE THREAD

**Issue by smnthermes** [slapperwan/gh4a#923]
OctoDroid doesn't support issue templates on repositories with two types of issues. 
Example: https://github.com/bromite/bromite/issues/new/choose

**Comment by hXtreme** [comment]
Is this feature planned to be implemented in the near future? Asking as we have a tiny discussion going on in another repo on what should be done for the issue reporting system there.

Thanks in advance!

**Comment by 3xploiton3** [comment]
@hXtreme what name alternative github client can fix this issue?

**Comment by maniac103** [comment]
I think I'll have something ready in the next few days:
![Screenshot_1572883505](https://user-images.githubusercontent.com/781373/68136275-4cddfc00-ff25-11e9-8d65-2f26700914e4.png)

Just need to finish wiring assignees and labels.

**Comment by hXtreme** [comment]
Any eta on when this will be released? There haven't been any new releases since September.

Thanks!
