### ISSUE TITLE
Trending repos have no username, no connection if clicked

### ISSUE THREAD

**Issue by matthiasroos** [slapperwan/gh4a#925]
### Description

In Trending there is no username shown for all repos, for example it reads "/DeepFaceLab" instead of "iperov/DeepFaceLab". As a consequence the repos can not be loaded if clicked (Not Found 404 Error) and the Trending section can not be used.

### Version

OS: Android 9 patchlevel August
Phone: Nokia 8.1
Octodroid: v4.4.0 (via FDroid)

### Screenshot
![Screenshot_20190905-085132](https://user-images.githubusercontent.com/40145019/64318750-1afaf880-cfbb-11e9-96af-82627fd12e79.png)

**Comment by Unpublished** [comment]
Thanks for your bug report.

Fixed via https://github.com/Unpublished/GithubTrending/commit/be26ebccb3420aca97e184e26759dd8950ab265a
