### ISSUE TITLE
Opening links from other apps

### ISSUE THREAD

**Issue by smnthermes** [slapperwan/gh4a#933]
Links to GitHub from other apps aren't opened in a separate window for OctoDroid, but instead in the same window of the previous app. It compromises the multitasking. 

![Screenshot_20191025-120933_Trebuchet](https://user-images.githubusercontent.com/51975869/67582677-91e18180-f720-11e9-8ff5-b40b31e47ed5.png)

**Comment by beerisgood** [comment]
That's normal how Android handle it

**Comment by beerisgood** [comment]
That's normal how Android handle it

**Comment by maniac103** [comment]
There's the 'open in new window' command exactly for that purpose (detaching OctoDroid from the calling activity's task) in the context menu of almost all activities you can open via link.

**Comment by smnthermes** [comment]
@beerisgood it doesn't happen with NewPipe or Slide

@maniac103 it's improbable to always remember to use that command

**Comment by maniac103** [comment]
The current behavior follows most other apps, including high volume ones like Google docs or sheets. I always try to orient towards Google's apps, as Google are the ones who developed Android in the first place.
Because of that, the current behavior is the intended one.
