### ISSUE TITLE
incomplete news feed orgs list

### ISSUE THREAD

**Issue by casperdcl** [slapperwan/gh4a#934]
News feed orgs list doesn't include all the orgs listed on https://github.com/ (top left drop down list when logged in) or user profile even when membership to said orgs is public.

**Comment by casperdcl** [comment]
Logging in with password (creating a personal access token) instead of OAuth resolves this. Really should fix OAuth permissions...

**Comment by casperdcl** [comment]
Also should allow manual entry of personal access token

**Comment by maniac103** [comment]
> Really should fix OAuth permissions...

By requesting 'user' permission, Octodroid already does that. There's one catch though: Depending on the org settings, one needs to grant Octodroid access to the org via Profile -> Settings -> Applications -> Authorized OAuth apps -> Octodroid -> Organization access. As the requested permissions on that page look fully correct, I don't think there's anything we can do about that?

But yeah, login via access token should totally be doable.

**Comment by casperdcl** [comment]
The `Authorized OAuth apps -> Octodroid -> Organization access` route seems heavy-handed - need to request/grant "full repo access" for each org I belong to? Much nicer using a personal access token which grants access to my account in a way that I can control and which doesn't alarm any orgs.

**Comment by maniac103** [comment]
As said, I can surely add login via access token. That's not a solution for everybody though. I believe the text in that dialog is a bit off, comparing it to the text on the page itself which says the requested access is according to the permissions on the page, which in turn clearly say org access is read only.

**Comment by maniac103** [comment]
Above commit adds token based login.

**Comment by maniac103** [comment]
FWIW, support response:

> If a user creates a personal access token with the read:org scope, then they can fetch a list of organizations they belong to.
> If a user authorizes an OAuth application with the read:org scope, when the OAuth application fetches a list of organizations they belong to, the only organizations that will be returned in the response are organizations that have explicitly approved the application to access its resources.
> Put another way, these OAuth Application Access restrictions not only apply to an organization's private resources, but also their public resources.

So that heavy handed route above is intentional as per their design and can only be avoided using a PAT.
