### ISSUE TITLE
Expand readme by default

### ISSUE THREAD

**Issue by Madis0** [slapperwan/gh4a#935]
The readme file is one of the most important features of a repository. It is cool that we can collapse it, but it should be still expanded by default.

**Comment by maniac103** [comment]
A lot of people are only interested in repo content (commits, files) and not so much the readme, especially if they are familiar with the repo. That's why we skip loading the readme (and thus avoid network traffic) by default.

**Comment by smichel17** [comment]
@Madis0 I felt the same way as you when the feature was first introduced, but after using it for a while I very much agree that collapsed by default is better. Most of the repos I visit in octodroid are ones I've already seen, know the readme content, and don't need to see it again.
