### ISSUE TITLE
Header color

### ISSUE THREAD

**Issue by Madis0** [slapperwan/gh4a#936]
I like the fact that open issues use a green header and closed issues use a red one, but for the majority of the app the colors are not needed IMO.

I would like to request a color picker for the header (or primary?) color, or simply give options green, white and black.

**Comment by maniac103** [comment]
The green used throughout the app actually is the app color (matches the icon color) ... coloring like that matches the (first version of the) Material Design spec.
I really don't want to add a color picker (as with that the colors don't match the icon anymore, and do you know any widely used app that does that?) ... but with the new Material Design, colors are going to be toned down anyway - but not as random one-off measure, but as part of a larger redesign. It's just matter of a) waiting for the new MD to be settled a bit and b) finding the time (and motivation) to actually implement the change.

**Comment by aha999** [comment]
From #1037 : 

Add the option to select the theme, based on the colors you select, currently green, i would like to change to blue, and the gray menu part to dark blue for example...
Theme - Custom - Accent color...
I would like to set my theme to look like FastHub libre's premium theme.

**Comment by Secret-chest** [comment]
I want a brighter header in dark mode
