### ISSUE TITLE
App disappears from Overview when clicking links from other apps

### ISSUE THREAD

**Issue by Madis0** [slapperwan/gh4a#946]
OctoDroid disappears from Overview (Recents) when clicking a link from an other app and then going home. The user can't even get the last view back when opening OctoDroid again. 

How to reproduce: 
1) Tap on a Github link in any app
2) OctoDroid opens the link
3) Go home 
4) Open Overview 
5) OctoDroid view is gone forever, only the app where the link was clicked is seen

Using Android 10.
Related: #933

**Comment by maniac103** [comment]
Notes to self:
- this does not happen for all invocations from other apps, but only if the invoking app sets FLAG_ACTIVITY_NEW_TASK
- thus, a new task is opened for the browse filter, but the filter activity (and thus the whole task) is excluded from recents
- should probably open the new activity in a new separate task if that's the case.
