### ISSUE TITLE
add reaction is no longer working

### ISSUE THREAD

**Issue by arcturus140** [slapperwan/gh4a#951]
in an issue, on a comment you can add reaction to give it a heart or thumbs up. When doing so the comment does not have a thumbs up. 

it does work on some repositories but not other. For example on gh4a it is working fine. 

The two repositories where it doesn't it was working initially, I am a contributor on both and very active on both. When I visit the github website I am able to add reactions in the web browser.

**Comment by arcturus140** [comment]
I emptied cache, data and reinstalled the app to no avail.

**Comment by maniac103** [comment]
Can you give a concrete example of repos/issues/comments where it doesn't work?

**Comment by arcturus140** [comment]
for example

BoostIO/Boostnote/#3443

**Comment by smichel17** [comment]
I think it is working for personal repos and not for organizations.

**Comment by arcturus140** [comment]
@smichel17 thanks, I'll close the duplicate
