### ISSUE TITLE
[Feature request] Save default sorting in settings

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#952]
Hello,

I always want my issues list to be sorted by "most recently updated", but it is always sorted by "newest" by default.

Then, I would like to be able to change that default selection from settings.

Thanks

**Comment by smichel17** [comment]
To implement something like this without adding a setting, you could also make the sort method persistent.

**Comment by KaKi87** [comment]
You're actually right xD

**Comment by KaKi87** [comment]
Thanks @maniac103  ! Is it possible to know when this will be available in the production package ?

**Comment by farfromrefug** [comment]
@maniac103 could you add the same for bookmark starred? I keep on changing the order which also seems to trigger a new request everytime.

**Comment by maniac103** [comment]
@farfromrefug You mean make it so that thr last used page is opened by default?

**Comment by farfromrefug** [comment]
@maniac103 i mean storing the sort order in bookmarks and starred.
But if you mean remember the tab selected in "Bookmarks and Stars" that would be awesome too.
Never use Bookmarks, only starred

**Comment by maniac103** [comment]
@farfromrefug I've implemented the sort order saving. Saving the last used tab is not as straightforward; I'd like to keep that out for now.

@KaKi87 Whenever @slapperwan has time for a release, I guess.
@slapperwan Mind doing a 4.6.0 release (with dark mode support as new important feature)?
