### ISSUE TITLE
Crashes on deleted comments

### ISSUE THREAD

**Issue by casperdcl** [slapperwan/gh4a#955]
- Trying to open https://github.com/casperdcl/git-fame/issues/28 crashes the app, likely due to not handling a deleted comment.
- ~~Also related: the app would crash on startup (trying to display notifications) which I fixed temporarily by marking GitHub Actions notifications as read in a browser.~~ moved to #956

**Comment by maniac103** [comment]
I can repro the former, will check it. Can you get me the crash log for the latter crash? (I can walk you through that if that's needed)

**Comment by casperdcl** [comment]
No because I deleted those notifications so it would stop crashing :)

Could probably force reproduce it - what log do you need?

**Comment by maniac103** [comment]
I'd need the crash part of logcat after the crash (collected using either running `adb logcat -b crash`) on a PC or using an app like MatLog (in case the phone is rooted).

**Comment by casperdcl** [comment]
I'll open a new issue and post the logcat if it affects me again.

**Comment by casperdcl** [comment]
moved Actions notifications crash to #956
