### ISSUE TITLE
Pure Black theme for amoled display

### ISSUE THREAD

**Issue by anishmittal2020** [slapperwan/gh4a#957]
Pure Black theme for amoled display can be useful.

**Comment by smichel17** [comment]
Pure black themes can look nice, and I often use them myself, but they're not that useful -- compared to dark gray, the power savings are [not that different](https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/).

**Comment by maniac103** [comment]
Indeed, what @smichel17 said is also my opinion. Thus this is a dupe of #882 and #437.
