### ISSUE TITLE
Crash on specific pull request

### ISSUE THREAD

**Issue by jthistle** [slapperwan/gh4a#959]
Hi, opening this link in the app always causes a crash:

https://github.com/neontribe/gbptm/pull/480

Using the latest version from the play store. 

And, thanks for such a great app :)

**Comment by maniac103** [comment]
This already seems fixed in master ... likely by https://github.com/slapperwan/gh4a/commit/7e0c05f5bc289afbb3ac62efef9270f82b3cb747

Thanks for the report :-)

**Comment by jthistle** [comment]
That's great, thanks. Any idea when a new release might come?
