### ISSUE TITLE
[Bug] Notification not dismissed once read

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#963]
## Steps to reproduce

1. Wait for a notification
2. Click on the notification from Android status bar
3. Wait for in-app notifications list to load
4. Click on the notification from the list

The issue/pull request then loads, the notification is marked as read, and is finally removed from the in-app notifications list.

## Expected behavior

The notification is removed from Android status bar

## Actual behavior

The notification is not removed from Android status bar

<br>
Thanks !

**Comment by KaKi87** [comment]
up

**Comment by elimuhub** [comment]
Thanks @KaKi87

**Comment by maniac103** [comment]
I just tried to reproduce, but can't: the status bar notification is (as intended) removed after step 2 for me. To be precise, it's removed when opening the in-app notifications page.

Am I misunderstanding something here?

**Comment by KaKi87** [comment]
Well, I can't anymore. But I swear I could, in the previous version of the app. Thanks

**Comment by smichel17** [comment]
I can reproduce. I don't have exact steps because I wasn't trying for a repro, but it likely has to do with bundling of multiple notifications. Possible it's also related to receiving a new notification while the app is open or manually refreshing on the notifications screen. I'll try to narrow it down as more notifications come in.

**Comment by KaKi87** [comment]
Well, yes, it's happening again, in the exact same way you described

**Comment by maniac103** [comment]
> in the exact same way you described

What is this exact same way? ;-)

**Comment by KaKi87** [comment]
smichel17's

**Comment by maniac103** [comment]
> smichel17's

> I don't have exact steps

So please share exact steps if you have found them.

**Comment by KaKi87** [comment]
What I meant is that I'm 100% sure that I reproduced these scenarios today :
- expanding a group of notifications and opening a single issue/PR from them

and
- going back to the notifications tab without quitting the app and opening other issues/PRs from there

Then, the issue happened again.
So, the issue has to be caused by one or both.

**Comment by smichel17** [comment]
Last week I (temporarily) turned off notifications, so I haven't been testing for a while. However, before that I was trying to reproduce again, and I noticed that, when there are multiple notifications:

1. Sometimes they appear as a single notification, that cannot be expanded.
2. Sometimes they appear as a group of individual notifications, that can be expanded to allow tapping on an individual notification.

As far as I can remember, I have never been able to reproduce the bug with the first type of notification, and when I am able to reproduce, it follows the following pattern:

- Get Android notifications, grouped in type 2
- Expand the group and tap an individual Android notification
- ???
   - Includes reading all the GitHub notifications from within the app
   - Maybe involves swipe to refresh or receiving a new GitHub notification while in-app?
- Receive an Android notification type 1, with all the GitHub notifications I've already read

**Comment by maniac103** [comment]
What just occurred to me is that maybe we have a misunderstanding. Do you mean that the status bar notification isn't removed at all, or do you mean that it reappears for a GH notification that already is read once the GH notifications are next polled (according to the configured interval)?
I thought we were talking about the former, which is almost impossible from the code, but maybe we're actually talking about the latter?

**Comment by smichel17** [comment]
Unsure. This is a particularly hard bug to get exact repro on because I am usually distracted (by notification content) when it happens; tapping a notification in the drawer closes the drawer so I can't see exactly what happens in that case; it requires grouping type 2, which I cannot consistently reproduce; and it's hard to test alone, since I can't send myself notifications. That said, I think it is the latter, or maybe both.

I think the ideal way to nail down reproduction steps is:

- Figure out the circumstances under which grouping type 2 happens (either looking through the source or @maniac103 can share if you know it off the top of your head).
- @KaKi87 and I spend some time spamming each other with notifications until we get reliable repro.

This will have to wait until I have more free time.

**Comment by maniac103** [comment]
Notifications are grouped by repo, so 'type 2' happens whenever you have notifications for more than one repo. You then can expand it to get one notification for each repo.

**Comment by maniac103** [comment]
> and it's hard to test alone, since I can't send myself notifications

That's precisely the issue I have here as well ;-)

**Comment by maniac103** [comment]
Just had a notification for two repos. Expanded it, tapped on one of them -> notification list opens, highlighting the rapped repo, and notification is removed from status bar ... so everything seems fine here ¯\_(ツ)_/¯

**Comment by smichel17** [comment]
Notifications back on this week, and I just managed to reproduce this with a *single* notification, although I was not paying attention enough to capture repro steps. I think the key factor is having the app open as a new notification is received.

**Comment by maniac103** [comment]
So might it be get notification - visit notification page - go elsewhere in the app - get new notification - move back in app to notification page - status bar notification doesn't hide? If so, I guess I know what's wrong, but I'd like to see confirmation whether those steps (might) match your scenario.

**Comment by smichel17** [comment]
Getting closer to repro. I was paying attention to specific steps I took when the issue happened, although I don't yet know if they will reliably reproduce it:

1. Open Octodroid, go to the notification screen, and read all notifications, so the screen is blank
2. Press the home button to put the app in the background; do not swipe it away from recent apps.
3. Get a notification (an individual notification that would be grouped under type 2).
4. Press the notification (open Octodroid)
    - Notice: Notification screen is still blank (has not updated, just brought into the foreground). (screenshot 1)
    - Notice: Notification has been replaced by type 1. (screenshot 2)
5. At this point I swiped to refresh the notification view and make the notification appear (screenshot 3).
6. Then I tried tapping on the new (type 1) notification and it is not dismissed.

<img height="475" alt="Blank notification screen" src="https://user-images.githubusercontent.com/6563664/85565567-c9415e80-b61e-11ea-9db5-1f17d0db9e56.png"/> <img height="475" alt="New type 1 notification" src="https://user-images.githubusercontent.com/6563664/85565573-cba3b880-b61e-11ea-8504-82cf92b5470d.png"/> <img height="475" alt="Refreshed notification screen" src="https://user-images.githubusercontent.com/6563664/85565581-ce061280-b61e-11ea-866e-9bddca8c8351.png"/>

**Comment by smichel17** [comment]
I've prepped the first two steps again so I can see if these steps are reliable, the next time I get a notification :)

**Comment by smichel17** [comment]
Okay, confirming that the steps above will reliably reproduce the issue. For completeness' sake, here's screenshots of the notification before and after tapping it, so we're clear what the two types are:

<img height="500" alt="Before" src="https://user-images.githubusercontent.com/6563664/85573104-1de7d800-b625-11ea-95c6-9cfec96560ea.png"/> <img height="500" alt="After" src="https://user-images.githubusercontent.com/6563664/85573224-3952e300-b625-11ea-90ec-a7654b6355c6.png" />
