### ISSUE TITLE
[Question] Why is this repo named "gh4a" instead of "OctoDroid" ?

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#964]

**Comment by smichel17** [comment]
I believe the app was originally named "GitHub For All", or gh4a for short. Seems like it would make sense to move the repo, though.

**Comment by maniac103** [comment]
> Seems like it would make sense to move the repo, though.

I'm not sure it's really worth the hassle after all this time. I believe @slapperwan is really time constrained, so I'd like to use his time for stuff that really drives us forward (like doing releases *cough* ;-) ) and not for minor annoyances like this.

**Comment by KaKi87** [comment]
Well, this annoyance affects referencing. For instance, I need twice the time to find this repo than to find any other repo.

**Comment by maniac103** [comment]
But why? It's literally the second match when searching for 'Octodroid' in GH repo search, and it's linked from within the app...

**Comment by KaKi87** [comment]
Because I use my browser's URL bar, and the repo's name is in the URL. I can't remember "gh4a" 😅

**Comment by smichel17** [comment]
Workaround: you can bookmark the repo and put Octodroid in the name or keywords. Then your browser should autocomplete correctly.

**Comment by KaKi87** [comment]
Indeed. But I only bookmark websites that I visit really frequently.
