### ISSUE TITLE
[Bug] Crashing while trying to open specific issues

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#965]
- [duke7553/files-uwp#37](https://github.com/duke7553/files-uwp/issues/37) : https://del.dog/ysoteephur

- [ForkIssues/Tracker#562](https://github.com/ForkIssues/Tracker/issues/562) : https://del.dog/bulelecymu

**Comment by maniac103** [comment]
Thanks, I will take care of adding those enum values to the bindings.
If only GH had proper enum value documentation...

**Comment by KaKi87** [comment]
I confirm the issue has been fixed in yesterday's release. Thanks !

**Comment by KaKi87** [comment]
Hello, it's happening again with https://github.com/carloscuesta/gitmoji/issues/435 : https://del.dog/icoppuxela
