### ISSUE TITLE
[Bug] "Open in browser" incompatible with Kiwi Browser (Chrome)

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#967]
Hello,

I use Kiwi Browser as my default web browser on Android, it's a fork of Google Chrome supporting extensions.

However, OctoDroid's "open in browser" feature only allows me to open in Firefox.

Thanks

**Comment by maniac103** [comment]
Do other apps allow choosing that browser when opening http or https links? In general, we rely on querying handlers for https URLs from the system... See https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/utils/IntentUtils.java#L71 and the methods called from there.

**Comment by KaKi87** [comment]
| OctoDroid | Any other app |
| ------ | ----------- |
| ![Screenshot_20200416-145740_Systme_Android](https://user-images.githubusercontent.com/21284089/79469435-746edf80-8000-11ea-9666-32eb78ecefd8.png) | ![Screenshot_20200416-163433_Systme_Android](https://user-images.githubusercontent.com/21284089/79469437-75077600-8000-11ea-8c56-a4ee58a3e782.png)

**Comment by maniac103** [comment]
Works for me?! https://www.dropbox.com/s/chhkjf60j38qlf1/Screenshot_20200416-172628_Android-System.png?dl=0

Did you do anything special to Kiwi, like setting it the default browser or something?

**Comment by KaKi87** [comment]
Kiwi is my default browser, yes.

**Comment by maniac103** [comment]
Hmm, looks like there's a limit in items that are shown. When installing Firefox, that one is missing in the menu for me.
I'll look into that.

**Comment by maniac103** [comment]
It's indeed a limit in the number of apps shown, put in place by the system UI: https://github.com/LineageOS/android_frameworks_base/blob/lineage-17.1/core/java/com/android/internal/app/ChooserActivity.java#L263 (link is for LineageOS, but this is AOSP code) ... I'll see whether there's a way around that.

**Comment by KaKi87** [comment]
Okay but there's another "open with" method that doesn't have this limitation, therefore, I guess the best solution is to use the other one. Is it okay ?

**Comment by maniac103** [comment]
No, it isn't. Quoting the code comment in the piece of code I linked above:
```
   // We want to forward the URI to a browser, but our own intent filter matches
    // the browser's intent filters. We therefore resolve the intent by ourselves,
    // strip our own entry from the list and pass the result to the system's
    // activity chooser.
    // When doing that, pass a dummy URI to the resolver and swap in our real URI
    // later, as otherwise the system might return our package only if it's set
    // to handle the Github URIs by default
```

That means that when relying on the default intent resolver would
- also get Octodroid listed in the 'browser' list (which is unexpected and feels wrong) and (worse)
- if Octodroid is set as default app for Github links, you wouldn't get any chooser at all

**Comment by KaKi87** [comment]
So it's a wontfix ???

**Comment by KaKi87** [comment]
Thanks ! So, is it possible to get an APK featuring all the recent fixes, some time ? ^^

**Comment by maniac103** [comment]
Yes. I got all needed things to make releases myself now, so I will do a new release after checking for easy-to-fix open issues.

**Comment by KaKi87** [comment]
Very nice ! Thanks 🎉

**Comment by KaKi87** [comment]
I confirm the issue has been fixed in yesterday's release. Thanks !
