### ISSUE TITLE
Switching tasks loses work

### ISSUE THREAD

**Issue by MatthewScholefield** [slapperwan/gh4a#968]
If you open octodroid from an email and then switch applications you'll expect your draft is safe in the running app but when you switch back you'll realize there's no running task for it since it was attached to the email application or something and your work is lost. Similar to #358 but even worse because the app's state wasn't even explicitly changed.

[Here's a video of the problem](https://photos.app.goo.gl/gzG58E1ssA4mD4vXA)

**Comment by maniac103** [comment]
The actual issue is the same as #946 - the activity instance you entered your reply into gets lost. Closing this one in favor of #946
