### ISSUE TITLE
[Feature request] Search in issues and pull requests

### ISSUE THREAD

**Issue by KaKi87** [slapperwan/gh4a#969]
As it is possible to search in repositories, I'd like to be able to search in issues and pull requests.

Thanks

**Comment by maniac103** [comment]
So you want to search across different repos? Asking because issue search in one repo is already implemented.

**Comment by KaKi87** [comment]
Yes, I use the per-repo search too. But, sometimes, I need to only search in issues and PRs I'm involved in. Thanks

**Comment by KaKi87** [comment]
Closing in favor of #953 which I just renamed.
