### ISSUE TITLE
Release package

### ISSUE THREAD

**Issue by fusionneur** [slapperwan/gh4a#970]
There is no release since october '19, but some code was commited until now. Can we have a fresh release?

Do not let this project die.

**Comment by maniac103** [comment]
Pinging @slapperwan about this (again)

**Comment by slapperwan** [comment]
@maniac103  Helloo... sorry! So the master is ready to release, will do it tonight here.

**Comment by fusionneur** [comment]
When is the new release expected to be added?

**Comment by maniac103** [comment]
@slapperwan gave me the necessary info, I hope to get it released in the next 2 weeks ... want to resolve a few issues first.

**Comment by Zaseth** [comment]
Is this ever going to happen? App is unusable right now for me...

**Comment by maniac103** [comment]
Unusable because of what reason exactly?
But yes, it definitely is going to happen.

**Comment by Zaseth** [comment]
@maniac103 because of js files not opening right on Android 10, and I'm a js developer. Please just publish it.

**Comment by maniac103** [comment]
Release done (and uploaded to Google Play): https://github.com/slapperwan/gh4a/tree/v4.6.0

**Comment by fusionneur** [comment]
Can we get a release build please in the github releases page as well as on f-droid? Thank you

**Comment by maniac103** [comment]
> Can we get a release build please in the github releases page

Done: https://github.com/slapperwan/gh4a/releases/tag/4.6.0

> as well as on f-droid? Thank you

As far as I know (looking at #824), the F-Droid builds are updated automatically.
