### ISSUE TITLE
.js files get opened in the browser

### ISSUE THREAD

**Issue by Zaseth** [slapperwan/gh4a#973]
Opening .js files in the app makes Octodroid open them in the browser as raw.githubusercontent.com is not set default on Android 10 (Oxygen OS).

**Comment by maniac103** [comment]
You mean when opening GH links in other apps I guess? Got an example link handy?

**Comment by Zaseth** [comment]
When I open a .js file in a repo on Octodroid, it opens Brave browser for me. Just *any* .js file causes this.

**Comment by maniac103** [comment]
Ah, that's because JS files are resolved to `application/javascript` MIME type in Android 10 instead of `text/javascript`. I'll fix this.

**Comment by Zaseth** [comment]
I'm glad that you found a fix. I have one more question; Is it possible to search newest code?

**Comment by maniac103** [comment]
> Is it possible to search newest code?

What exactly do you mean by that?

> Hoping that you push this onto Google store.

Sure, I have a release planned in the next few days.

**Comment by Zaseth** [comment]
When you want the latest repositories in your search on the app, you add `sort:updated` in your query. Is there something like this for searching the latest code?

**Comment by maniac103** [comment]
Nope: https://developer.github.com/v3/search/#search-code

**Comment by Zaseth** [comment]
When is this landing in the play store?
