### ISSUE TITLE
Markdown links going to Markdown get opened in the browser

### ISSUE THREAD

**Issue by Zaseth** [slapperwan/gh4a#979]
As title says. Open Pino repo on Octodroid and then click on any link in the Readme and it gets opened on the browser. I'm on Android 10.

**Comment by maniac103** [comment]
You mean on the repo overview page? I don't think scrolling to links in that view is actually doable, even if one would distinguish them from external links.

**Comment by Zaseth** [comment]
Exactly, on the Readme itself
