### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by Zaseth** [slapperwan/gh4a#985]
When downloading private repositories, you get the result that it's unsuccessful. Downloading public repositories works just fine though. I'm on Android 10.

**Comment by maniac103** [comment]
Is this with 4.6.0 or 4.6.1? If the former, please try the latter ;-) Same issue as #976 I guess.

**Comment by Zaseth** [comment]
I'm currently using 4.6.1, I updated today

**Comment by maniac103** [comment]
And are you downloading releases or code zips?

**Comment by Zaseth** [comment]
I'm downloading the repository as zip
