### ISSUE TITLE
Crash when trying to open issue  (probably when loading templates)

### ISSUE THREAD

**Issue by billie80** [slapperwan/gh4a#994]
When trying to open an issue for Signal-Android [1] Octodroid crashes when loading the template. Maybe this has something to do with the template contents. For other projects using templates it works as expected.

[1] https://github.com/signalapp/Signal-Android

**Comment by billie80** [comment]
When taking a closer look this is probably issue #992 which is already fixed with commit https://github.com/slapperwan/gh4a/commit/a527c5ee3973907142197ee414a8a519031adebc. Just did not recognize it from the title. If this is the case please close it as duplicate.
Is there an ETA when this fix will be released?

**Comment by maniac103** [comment]
I'll double check if it's the same issue and close of that's the case.
I plan to do a new release sometime next week.

**Comment by maniac103** [comment]
Indeed it's the same issue as #992.

**Comment by billie80** [comment]
I wanted to test the new release. It seems however that they do not make it to F-Droid. Latest there is 4.6.0.92!

**Comment by billie80** [comment]
Works for me with 4.6.2!
