### ISSUE TITLE
App crashes when viewing stargazers after starring a repo

### ISSUE THREAD

**Issue by kylejcharlton** [slapperwan/gh4a#996]
Like the title says, the app crashes when attempting to view the stargazers of a repo after starring said repo. This makes it so I am unable to un-star a repository if I change my mind through the app. A similar issue happens when watching a repo, but will only crash after pressing unwatch. That may be its own issue in itself. Tech wise, I am using a Pixel 3XL on Android 10

**Comment by maniac103** [comment]
This was already fixed in commit https://github.com/slapperwan/gh4a/commit/d884ec297f9c93f1597f84c5060eb93aa3febaaa ... a new release will come in a few days.
